<?php
      $TIPS[]=array(
         'id_ref' => 'tip_pkts_block',	'tip_type' => 'cfg',	'url' => '',
         'date' => '',     'tip_class' => 1,	'name' => 'Descripcion',
         'descr' => 'Mide: <strong>policyPacketsDropped.0|policyPacketsBlocked.0</strong> a partir de los siguientes atributos de la mib TPT-POLICY:<br><br><strong>TPT-POLICY::policyPacketsDropped.0 (COUNTER):</strong> "The total number of packets discarded due to network congestion."
<strong>TPT-POLICY::policyPacketsBlocked.0 (COUNTER):</strong> "The cumulative number of packets blocked because of policy actions."
',
      );


      $TIPS[]=array(
         'id_ref' => 'tip_pkts_flow',	'tip_type' => 'cfg',	'url' => '',
         'date' => '',     'tip_class' => 1,	'name' => 'Descripcion',
         'descr' => 'Mide: <strong>policyPacketsIncoming.0|policyPacketsOutgoing.0</strong> a partir de los siguientes atributos de la mib TPT-POLICY:<br><br><strong>TPT-POLICY::policyPacketsIncoming.0 (COUNTER):</strong> "The total number of incoming packets."
<strong>TPT-POLICY::policyPacketsOutgoing.0 (COUNTER):</strong> "The total number of outgoing packets."
',
      );


      $TIPS[]=array(
         'id_ref' => 'tip_pkts_perm',	'tip_type' => 'cfg',	'url' => '',
         'date' => '',     'tip_class' => 1,	'name' => 'Descripcion',
         'descr' => 'Mide: <strong>policyPacketsPermitted.0</strong> a partir de los siguientes atributos de la mib TPT-POLICY:<br><br><strong>TPT-POLICY::policyPacketsPermitted.0 (COUNTER):</strong> "The cumulative number of packets permitted because of policy actions."
',
      );


      $TIPS[]=array(
         'id_ref' => 'tip_pkts_inval',	'tip_type' => 'cfg',	'url' => '',
         'date' => '',     'tip_class' => 1,	'name' => 'Descripcion',
         'descr' => 'Mide: <strong>policyPacketsInvalid.0</strong> a partir de los siguientes atributos de la mib TPT-POLICY:<br><br><strong>TPT-POLICY::policyPacketsInvalid.0 (COUNTER):</strong> "The total number of packets discarded because they were invalid."
',
      );


      $TIPS[]=array(
         'id_ref' => 'tip_alerts_proto',	'tip_type' => 'cfg',	'url' => '',
         'date' => '',     'tip_class' => 1,	'name' => 'Descripcion',
         'descr' => 'Mide: <strong>protocolAlertCount</strong> a partir de los siguientes atributos de la mib TPT-POLICY:<br><br><strong>TPT-POLICY::protocolAlertCount (GAUGE):</strong> "The count of alerts generated by all policies of a given protocol."
',
      );


?>
