# This playbook contains common plays that will be run on all nodes.
- include_vars: /cfg/cnm_vars.yml

- name: DB Init 
  shell: /usr/bin/mysql -u onm -p{{ db_pwd }} < /opt/cnm/os/debian8/roles/cnm-init/files/{{ item }}
  with_items:
    - onm_init.sql
    - cnm_init.sql
  tags: cnm-init

- name: db-manage
  shell: php /update/db/db-manage.php 2>&1 > /tmp/update_db.log
  tags: cnm-init

- name: Flush rrds
  shell: /bin/rm -rf /opt/data/rrd/elements/*
  tags: cnm-init

