---
# This playbook contains common plays that will be run on all nodes.
- include_vars: /cfg/cnm_vars.yml

- name: Set hosts file
  template: src=hosts.j2 dest=/etc/hosts
  when: hostname is defined
  tags: host-name

- name: Set hostname file
  template: src=hostname.j2 dest=/etc/hostname
  when: hostname is defined
  tags: host-name

- name: Refresh hostname
  command: hostnamectl set-hostname {{ hostname }}
  when: hostname is defined
  tags: host-name

- name: Set hostname in onm.conf
  command: /opt/cnm/crawler/bin/support/cnm-set-cfg-key -k HOST_NAME -v {{ hostname }}
  when: hostname is defined
  tags: host-name

#Only for the appliance setup
- name: Check /etc/drbd.d/store.res
  stat: path=/etc/drbd.d/store.res
  register: store_res
  tags: host-name

- name: Set store.res file
  template: src=store.res.j2 dest=/etc/drbd.d/store.res
  when: hostname is defined and store_res.stat.exists is defined and store_res.stat.exists==1

#domain {{ domain }}
#nameserver {{ dns }}

...
