---
# This playbook contains common plays that will be run on all nodes.
- include_vars: /cfg/cnm_vars.yml
  tags: mysql

- name: Install packages
  apt:
    name: [ 'libdbd-mysql-perl', 'mariadb-client', 'mariadb-server', 'mariadb-common', 'default-libmysqlclient-dev', 'php7.4-mysql', 'python3-mysqldb' ]
    state: present
    force: yes
    update_cache: yes
  become: true
  tags: mysql

- name: Start MySQL service
  become: yes
  become_user: root
  become_method: sudo
  service: name=mysql state=restarted enabled=true
  tags: mysql

- name: Se actualiza la clave de root para todas las cuentas
  mysql_user: name=root host={{ item }} password={{ db_root_password }} priv=*.*:ALL,GRANT
  with_items:
     - "{{ ansible_hostname }}"
     - 127.0.0.1
     - ::1
     - localhost
  when: db_root_password is defined
  tags: mysql

- name: Create .my.cnf file with root password credentials
  become: yes
  become_user: root
  become_method: sudo
  template: src=my.cnf.root.j2 dest=/root/.my.cnf owner=root group=root mode=0600
  when: db_root_password is defined
  tags: mysql
  notify:
  - restart mysql

- name: Create 50-server.cnf config file 
  become: yes
  become_user: root
  become_method: sudo
  template: src=50-server.cnf.j2 dest=/etc/mysql/mariadb.conf.d/50-server.cnf owner=root group=root mode=0644
  when: db_max_connections is defined
  tags: mysql
  notify:
  - restart mysql

- name: MariaDb config Files
  copy: src="{{ item }}" dest="/etc/mysql/mariadb.conf.d/{{ item }}"  owner=root group=root mode=0644
  with_items:
    - 50-client.cnf
    - 50-mysql-clients.cnf
    - 50-mysqld_safe.cnf
    - 60-galera.cnf
  tags: mysql
  notify:
   - restart mysql

- name: delete anonymous MySQL server user for localhost
  action: mysql_user user="" host=localhost state="absent"
  tags: mysql

- name: remove the MySQL test database
  action: mysql_db db=test state=absent
  tags: mysql

- name: Create databases
  mysql_db: name={{ item }} state=present
  with_items:
   - onm
   - cnm
  tags: mysql

- name: Create onm user and set privileges
  mysql_user: name={{db_user}} password={{db_pwd}} host=localhost priv=*.*:ALL,GRANT state=present
  tags: mysql

- name: logrotate config
  copy: src=mysql-server.logrotate dest=/etc/logrotate.d/mysql-server  owner=root group=root mode=0640
  tags: mysql

#- name: Script de arranque
#  copy: src=mysql.init dest=/etc/init.d/mysql  owner=root group=root mode=0755
#  tags: mysql

- meta: flush_handlers

...

