---
# This playbook contains common plays that will be run on all nodes.
- include_vars: /cfg/cnm_vars.yml

- name: Install packages
  apt: name={{item}} state=installed force=yes update_cache=yes
  with_items:
   - acpi
   - acpid
   - adduser
   - ant
   - apache2
   - apache2-mpm-prefork
   - apache2-dev
   - apache2-utils
   - apache2.2-common
   - apt
   - apt-utils
   - aptitude
   - arping
   - at
   - autoconf
   - automake1.11
   - autotools-dev
   - base-files
   - base-passwd
   - bash
   - bc
   - bind9-host
   - binutils
   - binutils-dev
   - bsdmainutils
   - bsdutils
   - build-essential
   - busybox
   - bzip2
   - ca-certificates
   - comerr-dev
   - console-common
   - console-data
   - coreutils
   - cpio
   - cpp
   - cron
   - curl
   - curlftpfs
   - dc
   - debconf
   - debconf-i18n
   - debian-archive-keyring
   - debianutils
   - isc-dhcp-client
   - isc-dhcp-common
   - dictionaries-common
   - dmidecode
   - dnsutils
   - doc-debian
   - dpkg
   - dpkg-dev
   - dselect
   - e2fslibs
   - e2fsprogs
   - ed
   - eject
   - exim4
   - exim4-base
   - exim4-config
   - exim4-daemon-light
   - expect
   - fastjar
   - file
   - findutils
   - finger
   - fontconfig-config
   - ftp
   - g++
   - gcc
   - gcj-4.9
   - gettext-base
   - gnupg
   - gpgv
   - grep
   - groff-base
   - grub-legacy
   - gzip
   - hostname
   - iamerican
   - ibritish
   - ifupdown
   - imagemagick
   - info
   - initramfs-tools
   - initscripts
   - installation-report
   - iptables
   - iputils-ping
   - ispell
   - java-common
   - gcj-jre
   - klibc-utils
   - laptop-detect
   - ldap-utils
   - less
   - libacl1
   - libapache2-mod-perl2
   - libapache2-mod-php5
   - libapr1
   - libapr1-dev
   - libaprutil1
   - libaprutil1-dev
   - libart-2.0-2
   - libasound2
   - libattr1
   - libbcel-java
   - libbind9-90
   - libblkid1
   - libbz2-1.0
   - libc6
   - libc6-dev
   - libcap2
   - libcomerr2
   - libcommons-beanutils-java
   - libcommons-collections4-java
   - libcommons-dbcp-java
   - libcommons-digester-java
   - libcommons-el-java
   - libcommons-launcher-java
   - libcommons-logging-java
   - libcommons-modeler-java
   - libcommons-pool-java
   - libcups2
   - libcurl3
   - libcurl4-openssl-dev
   - libcurl3-gnutls
   - libdb5.3
   - libdb5.3-dev
   - libdbd-mysql-perl
   - libdbi-perl
   - libdevel-symdump-perl
   - libdevmapper1.02.1
   - libdns100
   - libedit2
   - libevent-2.0-5
   - libexpat1
   - libexpat1-dev
   - libfontconfig1
   - libfreetype6
   - libfuse2
   - libgc1c2
   - libgcc1
   - libgcj-common
   - libgcj14
   - libgcrypt20
   - libgd2-xpm-dev
   - libgdbm3
   - libglib2.0-0
   - libgnutls-deb0-28
   - libgpg-error0
   - libhtml-parser-perl
   - libhtml-tagset-perl
   - libhtml-tree-perl
   - libice6
   - libidn11
   - libidn11-dev
   - libiodbc2
   - libisc95
   - libisccc90
   - libisccfg90
   - libjasper1
   - libjaxp1.3-java
   - libjpeg62-turbo
   - libklibc
   - libkrb5-dev
   - libkrb5-3
   - liblcms2-2
   - libldap-2.4-2
   - libldap2-dev
   - liblocale-gettext-perl
   - liblockfile1
   - liblog4j1.2-java
   - libltdl7
   - liblwres90
   - liblzo2-2
   - libmagic1
   - libmx4j-java
   - libmysqlclient-dev
   - libmysqlclient18
   - libncurses5
   - libncursesw5
   - libneon27
   - libnet-daemon-perl
   - libnet1
   - libnewt0.52
   - libnfsidmap2
   - libnss-ldap
   - libpam-ldap
   - libpam-modules
   - libpam-runtime
   - libpam0g
   - libpcap0.8
   - libpci3
   - libpcre3
   - libpcre3-dev
   - libpcrecpp0
   - libperl5.20
   - libprpc-perl
   - libpng12-0
   - libpopt0
   - libpq-dev
   - libpq5
   - libreadline5
   - libregexp-java
   - librpcsecgss3
   - librrd4
   - librrds-perl
   - libsasl2-2
   - libsasl2-modules
   - libselinux1
   - libsemanage1
   - libsensors4
   - libsensors4-dev
   - libsepol1
   - libservlet3.1-java
   - libsigc++-2.0-0c2a
   - libslang2
   - libslp1
   - libsm6
   - libsqlite3-0
   - libsqlite3-dev
   - libss2
   - libssl-dev
   - libssl1.0.0
   - libstdc++6
   - libstdc++-4.9-dev
   - libsvn1
   - libsysfs2
   - libtasn1-bin
   - libtasn1-6
   - libtext-charwidth-perl
   - libtext-iconv-perl
   - libtext-wrapi18n-perl
   - libtiff5
   - libtomcat8-java
   - libtool
   - liburi-perl
   - libusb-0.1-4
   - libuuid1
   - libwrap0
   - libwrap0-dev
   - libwww-perl
   - libx11-6
   - libx11-data
   - libxau6
   - libxdmcp6
   - libxerces2-java
   - libxext6
   - libxml2
   - libxpm4
   - libxt6
   - locales
   - login
   - logrotate
   - lsb-base
   - lsof
   - m4
   - make
   - makedev
   - man-db
   - manpages
   - mawk
   - mime-support
   - mktemp
   - module-init-tools
   - mount
   - mpack
   - mtools
   - mtr-tiny
   - mutt
   - mysql-client
   - mysql-common
   - mysql-server
   - nano
   - ncurses-base
   - ncurses-bin
   - ncurses-term
   - net-tools
   - netbase
   - netcat
   - nfs-common
   - nmap
   - nscd
   - ntpdate
   - odbcinst1debian2
   - openbsd-inetd
   - openssh-blacklist
   - openssh-client
   - openssh-server
   - openssl
   - passwd
   - patch
   - pciutils
   - perl
   - perl-base
   - perl-modules
   - perl-doc
   - php-db
   - php-fpdf
   - php-mail
   - php-net-smtp
   - php-net-socket
   - php-pear
   - php-xml-parser
   - php5
   - php5-cli
   - php5-common
   - php5-dev
   - php5-gd
   - php5-mysql
   - php5-raphf
   - php5-raphf-dev
   - php5-propro
   - php5-propro-dev
   - php5-curl
   - pidentd
   - pkg-config
   - policycoreutils
   - rpcbind
   - procmail
   - procps
   - psmisc
   - python
   - python-minimal
   - python-newt
   - python-selinux
   - python-semanage
   - python-support
   - python3
   - python3-minimal
   - readline-common
   - reportbug
   - rng-tools
   - rrdtool
   - samba
   - samba-common
   - samba-doc
   - sed
   - sharutils
   - shtool
   - slapd
   - smbclient
   - strace
   - subversion
   - sudo
   - syslog-ng
   - sysstat
   - sysv-rc
   - sysvinit
   - sysvinit-utils
   - tar
   - tasksel
   - tasksel-data
   - tcl8.5
   - tcpd
   - tcpdump
   - tcsh
   - telnet
   - texinfo
   - time
   - tofrodos
   - traceroute
   - ttf-dejavu
   - tzdata
   - ucf
   - udev
   - unixodbc
   - unzip
   - update-inetd
   - usbutils
   - util-linux
   - uuid-dev
   - vim
   - vim-common
   - vim-runtime
   - vim-tiny
   - w3m
   - wamerican
   - wget
   - whiptail
   - whois
   - x11-common
   - zip
   - zlib1g
   - zlib1g-dev
   - re2c
   - libevent-dev
   - minicom
   - liboping-dev
   - liboping0
   - setserial
   - php5-xsl
   - libxml2-dev
   - chrpath
   - libgmp3-dev
   - syslog-ng
   - ssl-cert
   - openvpn
   - git
   - libapache2-mod-proxy-html
   - iotop
   - uuid
   - ipmitool
   - php5-ldap
   - libpcap0.8-dev
   - freeipmi-common
   - freeipmi-tools
   - ipmitool
   - libfreeipmi16
   - libipmiconsole2
   - libipmidetect0
   - libipmimonitoring5a
   - php5-imap
#   - php5-pecl-http
#   - php5-pecl-http-dev
   - php5-apcu
   - sblim-wbemcli
   - bmon
   - ethtool
   - sysvinit-core
   - drbd8-utils
  tags: base

- name: Install PERL modules
  shell: /opt/cnm/crawler/bin/support/chk-perl > /tmp/chk-perl.out 2>&1
  tags: base

...
