CREATE DATABASE IF NOT EXISTS `cnm`;
CREATE DATABASE IF NOT EXISTS `onm`;

GRANT ALL PRIVILEGES ON cnm.* TO 'onm'@'%' IDENTIFIED BY 'onm1234' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON onm.* TO 'onm'@'%' IDENTIFIED BY 'onm1234' WITH GRANT OPTION;

SET PASSWORD FOR 'root'@'localhost' = 'cnmManag3r';
FLUSH PRIVILEGES;
