---
# This playbook contains common plays that will be run on all nodes.
- include_vars: /cfg/cnm_vars.yml
  tags: cnm-docker

- name: Se asigna repositorio
  apt_repository: repo="{{ cnm_apt_repo }}" state=present
  tags: cnm-docker

#- name: Se asigna repositorio
#  debug: msg="Usando repositorio {{ cnm_git_repo }}"
#  tags: cnm-docker

- name: Install packages
  apt:
    name: [ 'apt-transport-https', 'ca-certificates', 'curl', 'gnupg2', 'software-properties-common' ]
    state: present
    force: yes
  become: true
  tags: cnm-docker

#curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
- name: Install docker apt key
  shell: curl -fsSL https://download.docker.com/linux/$(. /etc/os-release; echo "$ID")/gpg | sudo apt-key add -
  tags: cnm-docker

#Verify with:
#sudo apt-key fingerprint 0EBFCD88

#- name: Add docker repository
#  command: sudo add-apt-repository \
#   "deb [arch=amd64] https://download.docker.com/linux/$(. /etc/os-release; echo "$ID") \
#   $(lsb_release -cs) \
#   stable"
#  tags: cnm-docker
#
#deb [arch=amd64] https://download.docker.com/linux/debian jessie stable

- name: Se asigna repositorio
  apt_repository: repo="deb https://download.docker.com/linux/debian jessie stable" state=present update_cache=yes
  tags: cnm-docker

- name: Install docker package
  apt: name=docker-ce=18.06.3~ce~3-0~debian state=installed force=yes
  tags: cnm-docker

...
