# This playbook contains common plays that will be run on all nodes.
- include_vars: /cfg/cnm_vars.yml

- name: Check /usr/bin/wmic
  stat: path=/usr/bin/wmic
  register: wmic_binary
  tags: wmic

- name: Remove /tmp/src/wmic
  file: path=/tmp/src/wmic state=absent
  when: wmic_binary.stat.exists is defined and wmic_binary.stat.exists==0
  tags: wmic

- name: Create /tmp/src/wmic
  file: path=/tmp/src/wmic state=directory owner=root group=root mode=0640
  when: wmic_binary.stat.exists is defined and wmic_binary.stat.exists==0
  tags: wmic

- name: Extract from source
  command: tar -C /tmp/src/wmic -xjvf /opt/cnm-extras/src/wmic/wmi-1.3.14.tar.bz2
  when: wmic_binary.stat.exists is defined and wmic_binary.stat.exists==0
  tags: wmic

- name: Copy patches
  copy: src="/opt/cnm-extras/src/wmic/{{ item }}" dest="/tmp/src/wmic/{{ item }}" owner=root group=root mode=0640
  with_items:
    - openvas-wmi-1.3.14.patch
    - openvas-wmi-1.3.14.patch2
    - openvas-wmi-1.3.14.patch3
    - openvas-wmi-1.3.14.patch4
    - openvas-wmi-1.3.14.patch5
    - openvas-wmi-1.3.14.patch6
  when: wmic_binary.stat.exists is defined and wmic_binary.stat.exists==0
  tags: wmic

- name: Aply patches
  shell: "cd /tmp/src/wmic && patch -d wmi-1.3.14 -p1 < {{ item }}"
  with_items:
    - openvas-wmi-1.3.14.patch
    - openvas-wmi-1.3.14.patch2
    - openvas-wmi-1.3.14.patch3
    - openvas-wmi-1.3.14.patch4
    - openvas-wmi-1.3.14.patch5
    - openvas-wmi-1.3.14.patch6
  when: wmic_binary.stat.exists is defined and wmic_binary.stat.exists==0
  tags: wmic

- name: Make and install
  command: make -C /tmp/src/wmic/wmi-1.3.14 DESTDIR=/usr "CPP=gcc -E -ffreestanding"
  when: wmic_binary.stat.exists is defined and wmic_binary.stat.exists==0
  tags: wmic

#  shell: "{{ item }}"
#  with_items:
#    - cd /tmp/src/wmic/wmi-1.3.14
#    - make DESTDIR=/usr "CPP=gcc -E -ffreestanding"   
#  tags: wmic



#  command: "cd /tmp/src/wmic/wmi-1.3.14 , make DESTDIR=/usr 'CPP=gcc -E -ffreestanding'"
#  tags: wmic

#- name: Build net-snmp
#  shell: "{{ item }}"
#  args:
#    chdir: /tmp/src/net-snmp/net-snmp-5.7.3
#    register: out
#    debug: var=out.stdout_lines
#  with_items:
#    - ./configure --with-perl-modules --prefix=/opt/snmp --with-sys-contact="cnm-admin" --with-sys-location="CNM Room" --with-default-snmp-version="3" --with-logfile="/var/log/snmpd.log" --with-persistent-directory="/var/net-snmp"
#    - make
#    - make install

