# This playbook contains common plays that will be run on all nodes.
- include_vars: /cfg/cnm_vars.yml

- name: Check /usr/bin/wmic
  stat: path=/usr/bin/wmic
  register: wmic_binary
  tags: wmic

- name: Remove /tmp/src/wmic
  file: path=/tmp/src/wmic state=absent
  when: wmic_binary.stat.exists is defined and wmic_binary.stat.exists==0
  tags: wmic

- name: Create /tmp/src/wmic
  file: path=/tmp/src/wmic state=directory owner=root group=root mode=0640
  when: wmic_binary.stat.exists is defined and wmic_binary.stat.exists==0
  tags: wmic

- name: Extract from source
  command: tar -C /tmp/src/wmic -xvf /opt/cnm-extras/src/wmic/wmi-1.4.0.tar
  when: wmic_binary.stat.exists is defined and wmic_binary.stat.exists==0
  tags: wmic

- name: Make and install (tail -f /tmp/wmic.log)
  shell: make -C /tmp/src/wmic/wmi-1.4.0 DESTDIR=/usr CPP=gcc -E -ffreestanding > /tmp/wmic.log 2>&1
  when: wmic_binary.stat.exists is defined and wmic_binary.stat.exists==0
  tags: wmic


