---
# This playbook contains common plays that will be run on all nodes.
- include_vars: /cfg/cnm_vars.yml

# Add specified repository into sources list.
- name: Verify repository
  apt_repository: repo="{{ cnm_apt_repo }}" state=present
  tags: mysql

- name: Install packages
  apt:
    name: [ 'libdbd-mysql-perl', 'mariadb-client', 'mariadb-server', 'mariadb-common', 'default-libmysqlclient-dev', 'php7.3-mysql', 'python-mysqldb' ]
    state: present
    force: yes
  become: true
  tags: mysql

- name: Start MySQL service
  become: yes
  become_user: root
  become_method: sudo
  service: name=mysql state=restarted enabled=true
  tags: mysql

- name: Se actualiza la clave de root para todas las cuentas
  mysql_user: name=root host={{ item }} password={{ db_root_password }} priv=*.*:ALL,GRANT
  with_items:
     - "{{ ansible_hostname }}"
     - 127.0.0.1
     - ::1
     - localhost
  when: db_root_password is defined
  tags: mysql

- name: Create .my.cnf file with root password credentials
  become: yes
  become_user: root
  become_method: sudo
  template: src=my.cnf.root.j2 dest=/root/.my.cnf owner=root group=root mode=0600
  when: db_root_password is defined
  tags: mysql
  notify:
  - restart mysql

- name: Create my.cnf file for runtime operation
  become: yes
  become_user: root
  become_method: sudo
  template: src=my.cnf.j2 dest=/etc/mysql/my.cnf owner=root group=root mode=0600
  when: db_root_password is defined
  tags: mysql
  notify:
  - restart mysql

- name: delete anonymous MySQL server user for localhost
  action: mysql_user user="" host=localhost state="absent"
  tags: mysql

- name: remove the MySQL test database
  action: mysql_db db=test state=absent
  tags: mysql

- name: Create databases
  mysql_db: name={{ item }} state=present
  with_items:
   - onm
   - cnm
  tags: mysql

- name: Create onm user and set privileges
  mysql_user: name={{db_user}} password={{db_pwd}} host=localhost priv=*.*:ALL,GRANT state=present
  tags: mysql

- name: logrotate config
  copy: src=mysql-server.logrotate dest=/etc/logrotate.d/mysql-server  owner=root group=root mode=0640
  tags: mysql

- name: Script de arranque
  copy: src=mysql.init dest=/etc/init.d/mysql  owner=root group=root mode=0755
  tags: mysql

- meta: flush_handlers

...

