<?php
      $TIPS[]=array(
         'id_ref' => 'app_winnt_cpu_usage',  'tip_type' => 'app', 'url' => '',
         'date' => 1430852307,     'tip_class' => 1, 'name' => 'Descripcion',
         'descr' => '<strong>Muestra la tabla de uso de CPU de un Windows NT 4.0</strong><br>Utiliza la tabla SNMP WINDOWS-NT-PERFORMANCE::cpuprocessorTable (Enterprise=00311)<br><br><strong>WINDOWS-NT-PERFORMANCE::cpuprocessorIndex (GAUGE):</strong><br>"Index."
<strong>WINDOWS-NT-PERFORMANCE::cpuPercentProcessorTime (GAUGE):</strong><br>"Processor Time is expressed as a percentage of the elapsed time that a processor is busy executing a non-Idle thread.  It can be viewed as the fraction of the time spent doing useful work.  Each processor is assigned an Idle thread in the Idle process which consumes those unproductive processor cycles not used by any other threads."
<strong>WINDOWS-NT-PERFORMANCE::cpuPercentUserTime (GAUGE):</strong><br>"User Time is the percentage of processor time spent in User Mode in non-Idle threads.  All application code and subsystem code execute in User Mode.  The graphics engine, graphics device drivers, printer device drivers, and the window manager also execute in User Mode.  Code executing in User Mode cannot damage the integrity of the Windows NT Executive, Kernel, and device drivers.  Unlike some early operating systems, Windows NT uses process boundaries for subsystem protection in addition to the traditional protection of User and Privileged modes.  These subsystem processes provide additional protection.  Therefore, some work done by Windows NT on behalf of your application may appear in other subsystem processes in addition to the Privileged Time in your process."
<strong>WINDOWS-NT-PERFORMANCE::cpuPercentPrivilegedTime (GAUGE):</strong><br>"Privileged Time is the percentage of processor time spent in Privileged Mode in non-Idle threads.  The Windows NT service layer, the Executive routines, and the Windows NT Kernel execute in Privileged Mode.  Device drivers for most devices other than graphics adapters and printers also execute in Privileged Mode.  Unlike some early operating systems, Windows NT uses process boundaries for subsystem protection in addition to the traditional protection of User and Privileged modes.  These subsystem processes provide additional protection.  Therefore, some work done by Windows NT on behalf of your application may appear in other subsystem processes in addition to the Privileged Time in your process."
<strong>WINDOWS-NT-PERFORMANCE::cpuInterruptsPerSec (COUNTER):</strong><br>"Interrupts/sec is the number of device interrupts the processor is experiencing.  A device interrupts the processor when it has completed a task or when it otherwise requires attention.  Normal thread execution is suspended during interrupts.  An interrupt may cause the processor to switch to another, higher priority thread.  Clock interrupts are frequent and periodic and create a background of interrupt activity."
<strong>WINDOWS-NT-PERFORMANCE::cpuPercentDPCTime (GAUGE):</strong><br>"% DPC Time is the percentage of elapsed time that the Processor spent in Deferred Procedure Calls.  When a hardware device interrupts the Processor, the Interrupt Handler may elect to execute the majority of its work in a DPC.  DPCs run at lower priority than Interrupts, and so permit Interrupts to occur while DPCs being execute.  Deferred Procedure Calls are executed in Privileged Mode, so this is a component of Processor: % Privileged Time.  This counter can help determine the source of excessive time being spent in Privileged Mode."
<strong>WINDOWS-NT-PERFORMANCE::cpuPercentInterruptTime (GAUGE):</strong><br>"% Interrupt Time is the percentage of elapsed time that the Processor spent handling hardware Interrupts.  When a hardware device interrupts the Processor, the Interrupt Handler will execute to handle the condition, usually by signaling I/O completion and possibly issuing another pending I/O request.  Some of this work may be done in a Deferred Procedure Call (see % DPC Time.)  However, time spent in DPCs is not counted as time in Interrupts.  Interrupts are executed in Privileged Mode, so this is a component of Processor: % Privileged Time.  This counter can help determine the source of excessive time being spent in Privileged Mode."
<strong>WINDOWS-NT-PERFORMANCE::cpuDPCsQueuedPerSec (COUNTER):</strong><br>"DPCs Queued/sec is the rate DPC objects are queued to this processors DPC queue."
<strong>WINDOWS-NT-PERFORMANCE::cpuDPCRate (GAUGE):</strong><br>"DPC Rate is the average rate DPC objects are queued to this processors DPC queue per clock tick."
<strong>WINDOWS-NT-PERFORMANCE::cpuDPCBypassesPerSec (COUNTER):</strong><br>"DPC Bypasses/sec is the rate Dispatch interrupts were short-circuited."
<strong>WINDOWS-NT-PERFORMANCE::cpuAPCBypassesPerSec (COUNTER):</strong><br>"APC Bypasses/sec is the rate kernel APC interrupts were short-circuited."
',
      );


?>
