<?php
      $TIPS[]=array(
         'id_ref' => 'app_tip_top_ten_table',  'tip_type' => 'app', 'url' => '',
         'date' => 1430853507,     'tip_class' => 1, 'name' => 'Descripcion',
         'descr' => '<strong>Muestra las 10 vulnerabilidades con mayor numero de ocurrencias</strong><br>Utiliza la tabla SNMP TPT-POLICY::topTenHitsByPolicyTable (Enterprise=10734)<br><br><strong>TPT-POLICY::policyHitCount (GAUGE):</strong><br>"The count of alerts generated by a policy."
<strong>TPT-POLICY::tppolicyName (GAUGE):</strong><br>"The human-readable name of a policy."
<strong>TPT-POLICY::policyUUID (GAUGE):</strong><br>"The global identifier of a policy."
',
      );


?>
