---
# This playbook contains common plays that will be run on all nodes.
- include_vars: /cfg/cnm_vars.yml
  tags: ldap

- name: Install packages
  apt:
    name: [ 'slapd', 'ldap-utils', 'libldap-2.4-2', 'libnss-ldap', 'libpam-ldap', 'php7.4-ldap' ]
    state: present
    force: yes
    update_cache: yes
  become: true
  tags: ldap
  
- name: Check directory /etc/ldap
  file: path=/etc/ldap state=directory owner=root group=root mode=0755
  tags: ldap

- name: /etc/ldap/ldap.conf
  copy: src=ldap.conf dest=/etc/ldap/ldap.conf  owner=root group=root mode=0644
  tags: ldap

...
