<?php

// itil_type: operacion 1, configuracion 2, capacidad 3, disponibilidad 4, seguridad 5
// apptype: app.xxx os.xxx net.xxx serv.xxx user.xxx

	// ----------------------------------------------------------------------
	// TABLA cfg_monitor
	// Repositorio de metricas tcp/ip + metricas tcp/ip configuradas
	// ----------------------------------------------------------------------

      // -------------------------------------------------------------------
   	$CFG_MONITOR[]=array(
         'monitor' => 'disp_icmp',
         'description' => 'DISPONIBILIDAD ICMP (ping)',
         'info' => 'Envia 5 pings (icmp request) de 64 bytes al equipo remoto. Si pierde mas de 2 genera un error. Monitoriza la disponibilidad cada minuto',
         'port' => 'NULL',
         'shtml' => 'mon_icmp.shtml',
         'subtype' => 'mon_icmp',
         'params' => '',
         'severity' => '1',
         'items' => 'Disponible|No computable|No Disponible|Desconocido',
			'lapse' => 60,
         'mtype' => 'H0_SOLID',
         'vlabel' => 'estado',
        	'module' => 'mod_monitor_ext:ext_dispo_base',
         'top_value'=>1,
         'mode' => 'GAUGE',
         'cfg' => 1,
			'include'=> 1,
			'itil_type'=>4, 	'apptype'=>'IPSERV.PING',
      );

		// -------------------------------------------------------------------
		$CFG_MONITOR[]=array(
			'monitor' => 'mon_icmp',
			'description' => 'SERVICIO ICMP (ping)',
         'info' => 'Envia 5 pings (icmp request) de 64 bytes al equipo remoto. Si pierde mas de 2 genera un error. Monitoriza el tiempo de respuesta',
			'port' => 'NULL',
         'shtml' => 'mon_icmp.shtml',
         'subtype' => 'mon_icmp',
         'params' => '',
         'severity' => '1',
			'items' => 'Tiempo de Respuesta',
			'lapse' => 300,
			'mtype' => 'STD_BASEIP1',
			'vlabel' => 'segs',
			'module' => 'mod_monitor',
			'top_value'=>1,
			'mode' => 'GAUGE',
         'cfg' => 1,
			'include'=> 1,
			'itil_type'=>4, 	'apptype'=>'IPSERV.PING',
		);

      // -------------------------------------------------------------------
      $CFG_MONITOR[]=array(
         'monitor' => 'mon_ip_icmp2',
         'description' => 'SERVICIO ICMP - PRIORIDAD MEDIA (ping)',
         'info' => 'Envia 5 pings (icmp request) de 64 bytes al equipo remoto. Si pierde mas de 2 genera un error. Monitoriza el tiempo de respuesta',
         'port' => 'NULL',
         'shtml' => 'mon_icmp.shtml',
         'subtype' => 'mon_icmp',
         'params' => '',
         'severity' => '2',
         'items' => 'Tiempo de Respuesta',
         'lapse' => 300,
         'mtype' => 'STD_BASEIP1',
         'vlabel' => 'segs',
         'module' => 'mod_monitor',
         'top_value'=>1,
         'mode' => 'GAUGE',
         'cfg' => 1,
         'include'=> 1,
			'itil_type'=>4, 	'apptype'=>'IPSERV.PING',
      );
      // -------------------------------------------------------------------
      $CFG_MONITOR[]=array(
         'monitor' => 'mon_ip_icmp3',
         'description' => 'SERVICIO ICMP - PRIORIDAD BAJA (ping)',
         'info' => 'Envia 5 pings (icmp request) de 64 bytes al equipo remoto. Si pierde mas de 2 genera un error. Monitoriza el tiempo de respuesta',
         'port' => 'NULL',
         'shtml' => 'mon_icmp.shtml',
         'subtype' => 'mon_icmp',
         'params' => '',
         'severity' => '3',
         'items' => 'Tiempo de Respuesta',
         'lapse' => 300,
         'mtype' => 'STD_BASEIP1',
         'vlabel' => 'segs',
         'module' => 'mod_monitor',
         'top_value'=>1,
         'mode' => 'GAUGE',
         'cfg' => 1,
         'include'=> 1,
			'itil_type'=>4, 	'apptype'=>'IPSERV.PING',
      );

		// -------------------------------------------------------------------
      $CFG_MONITOR[]=array(
         'monitor' => 'mon_http',
         'description' => 'WWW - TIEMPO DE RESPUESTA',
         'info' => 'Hace una peticion HTTP/HTTPS (GET/POST). Monitoriza el tiempo de respuesta del servidor WEB y genera un error si no hay respuesta',
         'port' => '80',
         'shtml' => 'mon_http.shtml',
         'subtype' => 'mon_http',
         'params' => 'url|url_type|port|url_params|use_proxy|proxy_user|proxy_pwd|proxy_host|proxy_port|use_realm|realm_user|realm_pwd',
         'severity' => '1',
			'items' => 'Tiempo de Respuesta',
			'lapse' => 300,
         'mtype' => 'STD_BASEIP1',
         'vlabel' => 'segs',
         'module' => 'mod_monitor',
			'top_value'=>1,
         'mode' => 'GAUGE',
         'cfg' => 0,
			'include'=> 0,
			'itil_type'=>4, 	'apptype'=>'IPSERV.WWW',
      );
      $CFG_MONITOR[]=array(
         'monitor' => 'mon_httprc',
         'description' => 'WWW - RESPUESTA DEL SERVIDOR',
         'info' => 'Hace una peticion HTTP/HTTPS (GET/POST). Devuelve el codigo de respuesta del servidor segun el siguiente criterio: 1xx=>1, 2xx=>2, 3xx=>3 , 4xx=>4, 5xx=>5.',
         'port' => '80',
         'shtml' => 'mon_httprc.shtml',
         'subtype' => 'mon_httprc',
         'params' => 'url|url_type|port|url_params|use_proxy|proxy_user|proxy_pwd|proxy_host|proxy_port|use_realm|realm_user|realm_pwd',
         'severity' => '1',
			'items' => 'Codigo de Respuesta',
			'lapse' => 300,
         'mtype' => 'STD_BASEIP1',
         'vlabel' => 'tiempo',
         'module' => 'mod_monitor',
			'top_value'=>1,
         'mode' => 'GAUGE',
         'cfg' => 0,
			'include'=> 0,
			'itil_type'=>4, 	'apptype'=>'IPSERV.WWW',
      );
      $CFG_MONITOR[]=array(
         'monitor' => 'mon_httplinks',
         'description' => 'WWW - NUMERO DE ENLACES',
         'info' => 'Hace una peticion HTTP/HTTPS (GET/POST). Obtiene el numero de enlaces de una pagina WEB.',
         'port' => '80',
         'shtml' => 'mon_httplinks.shtml',
         'subtype' => 'mon_httplinks',
         'params' => 'url|url_type|port|url_params|use_proxy|proxy_user|proxy_pwd|proxy_host|proxy_port|use_realm|realm_user|realm_pwd',
         'severity' => '1',
			'items' => 'Numero de Enlaces',
			'lapse' => 300,
         'mtype' => 'STD_BASEIP1',
         'vlabel' => 'num',
         'module' => 'mod_monitor',
			'top_value'=>1,
         'mode' => 'GAUGE',
         'cfg' => 0,
			'include'=> 0,
			'itil_type'=>4, 	'apptype'=>'IPSERV.WWW',
      );
      $CFG_MONITOR[]=array(
         'monitor' => 'mon_httppage',
         'description' => 'WWW - DIFERENCIAS EN LA PAGINA',
         'info' => 'Hace una peticion HTTP/HTTPS (GET/POST). Comprueba el contenido de la pagina obtenida con una que tiene como referencia y obtiene el nuero de diferencias.',
         'port' => '80',
         'shtml' => 'mon_httppage.shtml',
         'subtype' => 'mon_httppage',
         'params' => 'url|url_type|port|url_params|page|use_proxy|proxy_user|proxy_pwd|proxy_host|proxy_port|use_realm|realm_user|realm_pwd',
         'severity' => '1',
			'items' => 'Numero de Diferencias',
			'lapse' => 300,
         'mtype' => 'STD_BASEIP1',
         'vlabel' => 'diffs',
         'module' => 'mod_monitor',
			'top_value'=>1,
         'mode' => 'GAUGE',
         'cfg' => 0,
			'include'=> 0,
			'itil_type'=>4, 	'apptype'=>'IPSERV.WWW',
      );

		// -------------------------------------------------------------------
      $CFG_MONITOR[]=array(
         'monitor' => 'mon_pop3',
         'description' => 'POP3',
         'info' => 'Efectua un login POP3, para ello requiere usuario y password. Monitoriza el tiempo de respuesta',
         'port' => '110',
         'shtml' => 'mon_pop3.shtml',
         'subtype' => 'mon_pop3',
         'params' => 'user|pwd|port=110',
         'severity' => '1',
			'items' => 'Tiempo de Respuesta',
			'lapse' => 300,
         'mtype' => 'STD_BASEIP1',
         'vlabel' => 'tiempo',
         'module' => 'mod_monitor',
			'top_value'=>1,
         'mode' => 'GAUGE',
         'cfg' => 0,
			'include'=> 0,
			'itil_type'=>4, 	'apptype'=>'IPSERV.POP3',
      );
      $CFG_MONITOR[]=array(
         'monitor' => 'mon_imap',
         'description' => 'IMAP',
         'info' => 'Efectua un login IMAP4, para ello requiere usuario y password. Monitoriza el tiempo de respuesta',
         'port' => '143',
         'shtml' => 'mon_imap.shtml',
         'subtype' => 'mon_imap',
         'params' => 'user|pwd|port=143',
         'severity' => '1',
			'items' => 'Tiempo de Respuesta',
			'lapse' => 300,
         'mtype' => 'STD_BASEIP1',
         'vlabel' => 'tiempo',
         'module' => 'mod_monitor',
			'top_value'=>1,
         'mode' => 'GAUGE',
         'cfg' => 0,
			'include'=> 0,
			'itil_type'=>4, 	'apptype'=>'IPSERV.IMAP4',
      );
      $CFG_MONITOR[]=array(
         'monitor' => 'mon_smtp',
         'description' => 'SMTP',
         'info' => 'Efectua un HELO SMTP. Monitoriza el tiempo de respuesta',
         'port' => '25',
         'shtml' => 'mon_smtp.shtml',
         'subtype' => 'mon_smtp',
         'params' => 'port=25',
         'severity' => '1',
			'items' => 'Tiempo de Respuesta',
			'lapse' => 300,
         'mtype' => 'STD_BASEIP1',
         'vlabel' => 'tiempo',
         'module' => 'mod_monitor',
			'top_value'=>1,
         'mode' => 'GAUGE',
         'cfg' => 0,
			'include'=> 0,
			'itil_type'=>4, 	'apptype'=>'IPSERV.SMTP',
      );
		// -------------------------------------------------------------------
      $CFG_MONITOR[]=array(
         'monitor' => 'mon_dns',
         'description' => 'DNS',
         'info' => 'Efectua un query DNS a un registro de tipo A. Monitoriza el tiempo de respuesta',
         'port' => '53',
         'shtml' => 'mon_dns.shtml',
         'subtype' => 'mon_dns',
         'params' => 'rr|port=53',
         'severity' => '1',
			'items' => 'Tiempo de Respuesta',
			'lapse' => 300,
         'mtype' => 'STD_BASEIP1',
         'vlabel' => 'tiempo',
         'module' => 'mod_monitor',
			'top_value'=>1,
         'mode' => 'GAUGE',
         'cfg' => 0,
			'include'=> 0,
			'itil_type'=>4, 	'apptype'=>'IPSERV.DNS',
      );
		// -------------------------------------------------------------------
      $CFG_MONITOR[]=array(
         'monitor' => 'mon_tcp',
         'description' => 'TCP PORT',
         'info' => 'Envia un TCP SYN al puerto servidor especificado. Monitoriza el tiempo de respuesta',
         'port' => 'NULL',
         'shtml' => 'mon_tcp.shtml',
         'subtype' => 'mon_tcp',
         'params' => 'port',
         'severity' => '1',
			'items' => 'Tiempo de Respuesta',
			'lapse' => 300,
         'mtype' => 'STD_BASEIP1',
         'vlabel' => 'tiempo',
         'module' => 'mod_monitor',
			'top_value'=>1,
         'mode' => 'GAUGE',
         'cfg' => 0,
			'include'=> 0,
			'itil_type'=>4, 	'apptype'=>'IPSERV.TCP',
      );
		// -------------------------------------------------------------------
      $CFG_MONITOR[]=array(
         'monitor' => 'mon_ssh',
         'description' => 'SSH',
         'info' => 'Obtiene el banner inicial de una sesion SSH. Monitoriza el tiempo de respuesta',
         'port' => '22',
         'shtml' => 'mon_ssh.shtml',
         'subtype' => 'mon_ssh',
         'params' => 'port=22',
         'severity' => '1',
			'items' => 'Tiempo de Respuesta',
			'lapse' => 300,
         'mtype' => 'STD_BASEIP1',
         'vlabel' => 'tiempo',
         'module' => 'mod_monitor',
			'top_value'=>1,
         'mode' => 'GAUGE',
         'cfg' => 0,
			'include'=> 0,
			'itil_type'=>4, 	'apptype'=>'IPSERV.SSH',
      );
		// -------------------------------------------------------------------
      $CFG_MONITOR[]=array(
         'monitor' => 'mon_snmp',
         'description' => 'Monitor de variable snmp',
         'info' => 'Monitoriza una o varias variables SNMP. Monitoriza el tiempo de respuesta',
         'port' => '161',
         'shtml' => 'mon_snmp.shtml',
         'subtype' => 'mon_snmp',
         'params' => 'community|version|port',
         'severity' => '1',
			'items' => 'Tiempo de Respuesta',
			'lapse' => 300,
         'mtype' => 'STD_BASEIP1',
         'vlabel' => 'tiempo',
         'module' => 'mod_monitor',
			'top_value'=>1,
         'mode' => 'GAUGE',
         'cfg' => 0,
			'include'=> 0,
			'itil_type'=>4, 	'apptype'=>'IPSERV.SNMP',
      );
		// -------------------------------------------------------------------
      $CFG_MONITOR[]=array(
         'monitor' => 'mon_smb',
         'description' => 'SMB/CIFS - ACCESO A FICHERO',
         'info' => 'Comprueba la existencia de un fichero compartido por SMB/CIFS.',
         'port' => '445',
         'shtml' => 'mon_smb.shtml',
         'subtype' => 'mon_smb',
         'params' => 'user|pwd|share|f|port=445',
         'severity' => '1',
			'items' => 'Size',
			'lapse' => 300,
         'mtype' => 'STD_BASEIP1',
         'vlabel' => 'bytes',
         'module' => 'mod_monitor',
			'top_value'=>1,
         'mode' => 'GAUGE',
         'cfg' => 0,
			'include'=> 0,
			'itil_type'=>4, 	'apptype'=>'IPSERV.SMB',
      );
		// -------------------------------------------------------------------
      $CFG_MONITOR[]=array(
         'monitor' => 'mon_ntp',
         'description' => 'NTP',
         'info' => 'Hace una peticion NTP. Monitoriza el tiempo de respuesta',
         'port' => '123',
         'shtml' => 'mon_ntp.shtml',
         'subtype' => 'mon_ntp',
         'params' => 'port=123',
         'severity' => '1',
			'items' => 'Tiempo de Respuesta',
			'lapse' => 300,
         'mtype' => 'STD_BASEIP1',
         'vlabel' => 'tiempo',
         'module' => 'mod_monitor',
			'top_value'=>1,
         'mode' => 'GAUGE',
         'cfg' => 0,
			'include'=> 0,
			'itil_type'=>4, 	'apptype'=>'IPSERV.NTP',
      );
		// -------------------------------------------------------------------
      $CFG_MONITOR[]=array(
         'monitor' => 'mon_xagent',
         'description' => 'MONITOR DE AGENTE REMOTO (XAGENT)',
         'info' => 'Monitoriza que el agente remoto (xagent) este funcionando.',
         'port' => '7691',
         'shtml' => 'mon_snmp.shtml',
         'subtype' => 'mon_xagent',
         'params' => 'port',
         'severity' => '1',
			'items' => 'Tiempo de Respuesta',
			'lapse' => 300,
         'mtype' => 'STD_BASEIP1',
         'vlabel' => 'tiempo',
         'module' => 'mod_monitor',
			'top_value'=>1,
         'mode' => 'GAUGE',
         'cfg' => 0,
			'include'=> 0,
			'itil_type'=>4, 	'apptype'=>'IPSERV.TCP',
      );
      // -------------------------------------------------------------------
      $CFG_MONITOR[]=array(
         'monitor' => 'mon_ldap',
         'description' => 'LDAP',
         'info' => 'Accede al elemento especificados del directorio LDAP para obtener el tiempo de respuesta.',
         'port' => '389',
         'shtml' => 'mon_ldap.shtml',
         'subtype' => 'mon_ldap',
         'params' => 'user|pwd|version|base_dn|filter|port=389',
         'severity' => '1',
         'items' => 'tiempo',
         'lapse' => 300,
         'mtype' => 'STD_BASEIP1',
         'vlabel' => 'tiempo',
         'module' => 'mod_monitor',
         'top_value'=>1,
         'mode' => 'GAUGE',
         'cfg' => 0,
         'include'=> 0,
			'itil_type'=>4, 	'apptype'=>'IPSERV.LDAP',
      );

      $CFG_MONITOR[]=array(
         'monitor' => 'mon_ldap_attr',
         'description' => 'LDAP - ATTR',
         'info' => 'Comprueba si el valor del atributo especificado del directorio LDAP coincide con el valor suministrado.',
         'port' => '389',
         'shtml' => 'mon_ldap.shtml',
         'subtype' => 'mon_ldap_attr',
         'params' => 'user|pwd|version|base_dn|filter|attr|check_value|port=389',
         'severity' => '1',
         'items' => '0 NOK, 1 OK',
         'lapse' => 300,
         'mtype' => 'STD_BASEIP1',
         'vlabel' => 'tiempo',
         'module' => 'mod_monitor',
         'top_value'=>1,
         'mode' => 'GAUGE',
         'cfg' => 0,
         'include'=> 0,
         'itil_type'=>4,   'apptype'=>'IPSERV.LDAP',
      );

      $CFG_MONITOR[]=array(
         'monitor' => 'mon_ldap_val',
         'description' => 'LDAP - VAL',
         'info' => 'Comprueba si el valor del atributo especificado del directorio LDAP.',
         'port' => '389',
         'shtml' => 'mon_ldap.shtml',
         'subtype' => 'mon_ldap_attr',
         'params' => 'user|pwd|version|base_dn|filter|attr|port=389',
         'severity' => '1',
         'items' => 'valor',
         'lapse' => 300,
         'mtype' => 'STD_BASEIP1',
         'vlabel' => 'tiempo',
         'module' => 'mod_monitor',
         'top_value'=>1,
         'mode' => 'GAUGE',
         'cfg' => 0,
         'include'=> 0,
         'itil_type'=>4,   'apptype'=>'IPSERV.LDAP',
      );



?>
