---
# This playbook contains common plays that will be run on all nodes.
#- include_vars: /cfg/cnm_vars.yml

- name: HOST Config for Apache - Create /store/cnm-api/etc/apache2 configuration located in host
  unarchive: src=apache2-config-dir.tar.gz dest=/store/cnm-api/etc/
  tags: cnm-api-setup

- name: HOST Global Config - Create /store/cnm-global/cfg/cnm-services.json
  copy: src=cnm-services.json dest=/store/cnm-global/cfg/ owner=root group=root mode=0644
  tags: cnm-api-setup

- name: HOST Global Config - Create /store/cnm-global/cfg/onm.conf
  copy: src=onm.conf dest=/store/cnm-global/cfg/ owner=root group=root mode=0644
  tags: cnm-api-setup

- name: HOST Apache Logs Directory - Create /store/cnm-api/log/apache2
  file: path=/store/cnm-api/log/apache2 state=directory owner=root group=root mode=0755
  tags: cnm-api-setup

#- name: cnm_default.pem
#  copy: src=cnm_default.pem dest=/store/cnm-api/etc/apache2  owner=root group=root mode=0600
#  tags: apache
#
#- name: PHP Apache config file
#  copy: src=php.ini.apache dest=/etc/php5/apache2/php.ini  owner=root group=root mode=0644
#  tags: apache
#  notify:
#   - restart apache2
#
#- name: PHP CLI config file
#  copy: src=php.ini.cli dest=/etc/php5/cli/php.ini  owner=root group=root mode=0644
#  tags: apache


#- name: Check for HTTPREQUEST PHP module
#  shell: php -i|grep -i 'http support'|wc -l
#  register: http_support


#  copy: src=apache2.conf dest=/etc/apache2/apache2.conf  owner=root group=root mode=0644
#  tags: apache
#  notify:
#   - restart apache2
#
#- name: Verify 000-default -> sites-enabled
#  copy: src=000-default dest=/etc/apache2/sites-enabled/000-default  owner=root group=root mode=0644
#  tags: apache
#  notify:
#   - restart apache2
#
#- meta: flush_handlers

...
