<?
	$TIPS[]=array(
		'id_ref' => 'CISCO-SYSLOG-MIB::clogMessageGenerated',
		'tip_type' => 'remote',
		'name' => 'CNM-Info',
		'descr' => '"When a syslog message is generated by the device a
 		clogMessageGenerated notification is sent.  The
 		sending of these notifications can be enabled/disabled
 		via the clogNotificationsEnabled object."
v1: <strong>clogHistFacility</strong><br>"Name of the facility that generated this message.
 		For example: SYS."
<br>OCTET STRING (1..20) 
   <br>v2: <strong>clogHistSeverity</strong><br>"The severity of the message."
<br>INTEGER {emergency(1), alert(2), critical(3), error(4), warning(5), notice(6), info(7), debug(8)} 
   <br>v3: <strong>clogHistMsgName</strong><br>"A textual identification for the message type.  A 
 		facility name in conjunction with a message name 
 		uniquely identifies a message type."
<br>OCTET STRING (1..30) 
   <br>v4: <strong>clogHistMsgText</strong><br>"The text of the message.  If the text of the message
 		exceeds 255 bytes, the message will be truncated to
 		254 bytes and a * character will be appended -
 		indicating that the message has been truncated."
<br>OCTET STRING (1..255) 
   <br>v5: <strong>clogHistTimestamp</strong><br>"The value of sysUpTime when this message was generated."
<br>TimeTicks
   <br>',
	);

	$TIPS[]=array(
		'id_ref' => 'CISCO-SYSLOG-MIB::clogMessageGenerated',
		'tip_type' => 'remote',
		'name' => 'CNM-Info',
		'descr' => '"When a syslog message is generated by the device a
 		clogMessageGenerated notification is sent.  The
 		sending of these notifications can be enabled/disabled
 		via the clogNotificationsEnabled object."
v1: <strong>clogHistFacility</strong><br>"Name of the facility that generated this message.
 		For example: SYS."
<br>OCTET STRING (1..20) 
   <br>v2: <strong>clogHistSeverity</strong><br>"The severity of the message."
<br>INTEGER {emergency(1), alert(2), critical(3), error(4), warning(5), notice(6), info(7), debug(8)} 
   <br>v3: <strong>clogHistMsgName</strong><br>"A textual identification for the message type.  A 
 		facility name in conjunction with a message name 
 		uniquely identifies a message type."
<br>OCTET STRING (1..30) 
   <br>v4: <strong>clogHistMsgText</strong><br>"The text of the message.  If the text of the message
 		exceeds 255 bytes, the message will be truncated to
 		254 bytes and a * character will be appended -
 		indicating that the message has been truncated."
<br>OCTET STRING (1..255) 
   <br>v5: <strong>clogHistTimestamp</strong><br>"The value of sysUpTime when this message was generated."
<br>TimeTicks
   <br>',
	);

	$TIPS[]=array(
		'id_ref' => 'CISCO-SYSLOG-MIB::clogMessageGenerated',
		'tip_type' => 'remote',
		'name' => 'CNM-Info',
		'descr' => '"When a syslog message is generated by the device a
 		clogMessageGenerated notification is sent.  The
 		sending of these notifications can be enabled/disabled
 		via the clogNotificationsEnabled object."
v1: <strong>clogHistFacility</strong><br>"Name of the facility that generated this message.
 		For example: SYS."
<br>OCTET STRING (1..20) 
   <br>v2: <strong>clogHistSeverity</strong><br>"The severity of the message."
<br>INTEGER {emergency(1), alert(2), critical(3), error(4), warning(5), notice(6), info(7), debug(8)} 
   <br>v3: <strong>clogHistMsgName</strong><br>"A textual identification for the message type.  A 
 		facility name in conjunction with a message name 
 		uniquely identifies a message type."
<br>OCTET STRING (1..30) 
   <br>v4: <strong>clogHistMsgText</strong><br>"The text of the message.  If the text of the message
 		exceeds 255 bytes, the message will be truncated to
 		254 bytes and a * character will be appended -
 		indicating that the message has been truncated."
<br>OCTET STRING (1..255) 
   <br>v5: <strong>clogHistTimestamp</strong><br>"The value of sysUpTime when this message was generated."
<br>TimeTicks
   <br>',
	);

?>
