---
# This playbook contains common plays that will be run on all nodes.
- include_vars: /cfg/cnm_vars.yml

# Add specified repository into sources list.
- name: Verify repository
  apt_repository: repo="{{ cnm_apt_repo }}" state=present
  tags: cnm-runtime

- name: Verify directories
  file: path={{ item }} state=directory owner=root group=root mode=0755
  with_items:
    - /var/log/tmark
  tags: cnm-runtime
 
- name: Verify directories
  file: path=/var/www/logs state=directory owner=root group=www-data mode=0755
  with_items:
    - /var/www/log
  tags: cnm-runtime

- name: Verify /var/www/logs/error_cgi.log
  file: path=/var/www/logs/error_cgi.log state=touch owner=www-data group=www-data mode=0755
  tags: cnm-runtime

- name: Verify www-user directories
  file: path={{ item }} state=directory owner=www-data group=www-data mode=0777
  with_items:
    - /store/www-user/background
    - /store/www-user/images
    - /store/www-user/gui_templates
    - /store/www-user/resources
    - /store/www-user/tmp
    - /store/www-user/files
    - /store/www-user/remote_cfgs
  tags: cnm-runtime

- name: crontab
  copy: src=crontab dest=/etc/crontab  owner=root group=root mode=0640
  tags: cnm-runtime

- name: Verify directories 
  file: path={{ item }} state=directory owner=root group=root mode=0755
  with_items:
    - /etc/cron.fast
    - /etc/cron.daily12
  tags: cnm-runtime

- name: cnm-hourly -> cron.hourly
  copy: src=cnm-hourly dest=/etc/cron.hourly/cnm-hourly  owner=root group=root mode=0755
  tags: cnm-runtime

- name: cnm-daily -> cron.daily
  copy: src=cnm-daily dest=/etc/cron.daily/cnm-daily  owner=root group=root mode=0755
  tags: cnm-runtime

- name: logrotate -> cron.daily12
  copy: src=logrotate dest=/etc/cron.daily12/logrotate owner=root group=root mode=0755
  tags: cnm-runtime

- name: Clean logrotate in cron.daily DEBUG
  file: path=/etc/cron.daily/logrotate state=absent
  tags: cnm-runtime

- name: logrotate-hourly.conf -> /etc
  copy: src=logrotate-hourly.conf dest=/etc/logrotate-hourly.conf owner=root group=root mode=0644
  tags: cnm-runtime

- name: logrotate-hourly -> cron.hourly
  copy: src=logrotate-hourly dest=/etc/cron.hourly/logrotate-hourly owner=root group=root mode=0755
  tags: cnm-runtime

- name: cnm-watch -> cron.fast
  copy: src=cnm-watch dest=/etc/cron.fast/cnm-watch  owner=root group=root mode=0755
  tags: cnm-runtime

- name: Check if drbd is mounted
  shell: cat /proc/mounts |grep drbd1|wc -l
  register: drbd_mounted
  tags: cnm-runtime

- name: Remove mysql from startup
  command: update-rc.d -f mysql remove
  when: drbd_mounted.stdout=="1"
  tags: cnm-runtime

- name: crawler -> logrotate
  copy: src=crawler.logrotate dest=/etc/logrotate.d/crawler  owner=root group=root mode=0640
  tags: cnm-runtime

- name: Init script
  copy: src=cnmd.init dest=/etc/init.d/cnmd  owner=root group=root mode=0755
  tags: cnm-runtime

- name: CNM User profile
  copy: src=.profile.cnm dest=/home/cnm/.profile  owner=cnm group=cnm mode=0640
  tags: cnm-runtime

- name: CNM root profile
  copy: src=.profile.root dest=/root/.profile  owner=root group=root mode=0640
  tags: cnm-runtime

- name: CNM home directory 
  file: path=/home/cnm state=directory owner=cnm group=www-data mode=0710
  tags: cnm-runtime

- name: CNM Backup directory
  file: path=/home/cnm/backup state=directory owner=cnm group=www-data mode=0777
  tags: cnm-runtime

- name: /etc/client.crt
  copy: src=client.crt dest=/etc/client.crt  owner=root group=root mode=0644
  tags: cnm-runtime

- name: /etc/client.key
  copy: src=client.key dest=/etc/client.key  owner=root group=root mode=0644
  tags: cnm-runtime

- name: /etc/ld.so.conf
  copy: src=ld.so.conf dest=/etc/ld.so.conf owner=root group=root mode=0644
  tags: cnm-runtime

- name: /etc/rc.local
  copy: src=rc.local dest=/etc/rc.local owner=root group=root mode=0755
  tags: cnm-runtime

- name: /etc/sudoers
  copy: src=sudoers dest=/etc/sudoers owner=root group=root mode=0640
  tags: cnm-runtime

- name: /etc/rng-tools
  copy: src=rng-tools dest=/etc/default/rng-tools owner=root group=root mode=0640
  tags: cnm-runtime

- name: /etc/udev/rules.d/z25_persistent-net.rules
  copy: src=z25_persistent-net.rules dest=/etc/udev/rules.d/z25_persistent-net.rules owner=root group=root mode=0640
  tags: cnm-runtime

- name: /etc/udev/rules.d/z45_persistent-net-generator.rules
  copy: src=z45_persistent-net-generator.rules dest=/etc/udev/rules.d/z45_persistent-net-generator.rules owner=root group=root mode=0640
  tags: cnm-runtime

- name: /etc/security/limits.conf
  copy: src=limits.conf dest=/etc/security/limits.conf owner=root group=root mode=0640
  tags: cnm-runtime

#- name: dhtmlx_gpl
#  file: path=/var/www/html/onm/libs/dhtmlx src=/var/www/html/onm/libs/dhtmlx_gpl state=link owner=root group=root mode=0755
#  tags: cnm-runtime

- name: Store CNM version
  shell: /opt/cnm/crawler/bin/support/cnm-set-version -p{{ db_pwd }}
  tags: cnm-runtime

- name: Update OIDs
  shell: php /update/db/update/oids_update.php 2>&1 | tee /tmp/oids_update.log
  tags: cnm-runtime


# Stand alone API

- name: Check API base directory
  file: path=/var/www/html/onm state=directory owner=www-data group=www-data mode=0755
  tags: cnm-runtime

- name: Check API link 
  file: src=/opt/cnm/api/src dest=/var/www/html/onm/api state=link owner=www-data group=www-data
  tags: cnm-runtime

# Legacy tasks directory

- name: Legacy tasks directory
  file: path=/var/www/html/onm/files/tasks state=directory owner=www-data group=www-data mode=0755 recurse=yes
  tags: cnm-runtime

...
