<?php

		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'ns_cpu_usage_perc',
            'class' => 'NETSCREEN',
            'lapse' => '300',
            'descr' => 'USO DE CPU (%)',
            'items' => 'nsResCpuAvg.0|nsResCpuLast1Min.0|nsResCpuLast5Min.0|nsResCpuLast15Min.0',
            'oid' => '.1.3.6.1.4.1.3224.16.1.1.0|.1.3.6.1.4.1.3224.16.1.2.0|.1.3.6.1.4.1.3224.16.1.3.0|.1.3.6.1.4.1.3224.16.1.4.0',
            'get_iid' => '',
            'oidn' => 'NETSCREEN-RESOURCE-MIB::nsResCpuAvg.0|NETSCREEN-RESOURCE-MIB::nsResCpuLast1Min.0|NETSCREEN-RESOURCE-MIB::nsResCpuLast5Min.0|NETSCREEN-RESOURCE-MIB::nsResCpuLast15Min.0',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'NETSCREEN-RESOURCE-MIB::nsResCpuAvg.0',
            'enterprise' => '3224',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.NETSCREEN',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'ns_mem_usage',
            'class' => 'NETSCREEN',
            'lapse' => '300',
            'descr' => 'USO DE MEMORIA',
            'items' => 'nsResMemAllocate.0|nsResMemLeft.0|nsResMemFrag.0',
            'oid' => '.1.3.6.1.4.1.3224.16.2.1.0|.1.3.6.1.4.1.3224.16.2.2.0|.1.3.6.1.4.1.3224.16.2.3.0',
            'get_iid' => '',
            'oidn' => 'NETSCREEN-RESOURCE-MIB::nsResMemAllocate.0|NETSCREEN-RESOURCE-MIB::nsResMemLeft.0|NETSCREEN-RESOURCE-MIB::nsResMemFrag.0',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'NETSCREEN-RESOURCE-MIB::nsResMemAllocate.0',
            'enterprise' => '3224',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.NETSCREEN',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'ns_session_usage',
            'class' => 'NETSCREEN',
            'lapse' => '300',
            'descr' => 'USO DE SESIONES',
            'items' => 'nsResSessAllocate.0|nsResSessFailed.0|nsResSessMaxium.0',
            'oid' => '.1.3.6.1.4.1.3224.16.3.2.0|.1.3.6.1.4.1.3224.16.3.4.0|.1.3.6.1.4.1.3224.16.3.3.0',
            'get_iid' => '',
            'oidn' => 'NETSCREEN-RESOURCE-MIB::nsResSessAllocate.0|NETSCREEN-RESOURCE-MIB::nsResSessFailed.0|NETSCREEN-RESOURCE-MIB::nsResSessMaxium.0',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'NETSCREEN-RESOURCE-MIB::nsResSessAllocate.0',
            'enterprise' => '3224',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.NETSCREEN',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'ns_active_users',
            'class' => 'NETSCREEN',
            'lapse' => '300',
            'descr' => 'USUARIOS ACTIVOS',
            'items' => 'nsUACActiveUsers.0',
            'oid' => '.1.3.6.1.4.1.3224.22.1.0',
            'get_iid' => '',
            'oidn' => 'NETSCREEN-UAC-MIB::nsUACActiveUsers.0',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'NETSCREEN-UAC-MIB::nsUACActiveUsers.0',
            'enterprise' => '3224',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.NETSCREEN',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'ns_url_filter_stat',
            'class' => 'NETSCREEN',
            'lapse' => '300',
            'descr' => 'ESTADO DEL FILTRO WEB',
            'items' => 'running(1)|N/A(2)|Down(3)',
            'oid' => '.1.3.6.1.4.1.3224.7.4.5.0',
            'get_iid' => '',
            'oidn' => 'NETSCREEN-SET-URL-FILTER-MIB::nsSetUrlServerStatus.0',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_SOLID',
            'vlabel' => 'estado',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'NETSCREEN-SET-URL-FILTER-MIB::nsSetUrlServerStatus.0',
            'enterprise' => '3224',
            'esp' => 'MAP(0)(0,1,0)|MAP(1)(1,0,0)|MAP(2)(0,0,1)',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.NETSCREEN',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'ns_power_status',
            'class' => 'NETSCREEN',
            'lapse' => '300',
            'descr' => 'ESTADO DE LA FUENTE',
            'items' => 'Good(1)|Fail(0)|Not Installed(2)',
            'oid' => '.1.3.6.1.4.1.3224.21.1.1.2.IID',
            'get_iid' => 'nsPowerDesc',
            'oidn' => 'nsPowerStatus.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_SOLID',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'NETSCREEN-CHASSIS-MIB::nsPowerTable',
            'enterprise' => '3224',
            'esp' => 'MAP(0)(0,0,1)|MAP(1)(1,0,0)|MAP(2)(0,1,0)',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.NETSCREEN',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'ns_slot_status',
            'class' => 'NETSCREEN',
            'lapse' => '300',
            'descr' => 'ESTADO DEL SLOT',
            'items' => 'Good(1)|Fail(0)|Not Installed(2)',
            'oid' => '.1.3.6.1.4.1.3224.21.5.1.3.IID',
            'get_iid' => 'nsSlotType',
            'oidn' => 'nsSlotStatus.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_SOLID',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'NETSCREEN-CHASSIS-MIB::nsSlotTable',
            'enterprise' => '3224',
            'esp' => 'MAP(0)(0,0,1)|MAP(1)(1,0,0)|MAP(2)(0,1,0)',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.NETSCREEN',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'ns_tunnel_status',
            'class' => 'NETSCREEN',
            'lapse' => '300',
            'descr' => 'ESTADO DEL TUNEL',
            'items' => 'Up(1)|Unk(2)|Down(0)',
            'oid' => '.1.3.6.1.4.1.3224.4.1.1.1.20.IID',
            'get_iid' => 'nsVpnMonVpnName',
            'oidn' => 'nsVpnMonTunnelState.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_SOLID',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'NETSCREEN-VPN-MON-MIB::nsVpnMonTable',
            'enterprise' => '3224',
            'esp' => 'MAP(0)(0,0,1)|MAP(2)(0,1,0)|MAP(1)(1,0,0)',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.NETSCREEN',
      );


?>
