<?php

		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'ironport_cpu_usage',
            'class' => 'IRONPORT',
            'lapse' => '300',
            'descr' => 'USO DE CPU (%)',
            'items' => 'perCentCPUUtilization.0',
            'oid' => '.1.3.6.1.4.1.15497.1.1.1.2.0',
            'get_iid' => '',
            'oidn' => 'ASYNCOS-MAIL-MIB::perCentCPUUtilization.0',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'ASYNCOS-MAIL-MIB::perCentCPUUtilization.0',
            'enterprise' => '15497',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.IRONPORT',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'ironport_memory_usage',
            'class' => 'IRONPORT',
            'lapse' => '300',
            'descr' => 'USO DE MEMORIA (%)',
            'items' => 'perCentMemoryUtilization.0',
            'oid' => '.1.3.6.1.4.1.15497.1.1.1.1.0',
            'get_iid' => '',
            'oidn' => 'ASYNCOS-MAIL-MIB::perCentMemoryUtilization.0',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'ASYNCOS-MAIL-MIB::perCentMemoryUtilization.0',
            'enterprise' => '15497',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.IRONPORT',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'ironport_disk_usage',
            'class' => 'IRONPORT',
            'lapse' => '300',
            'descr' => 'USO DE DISCO (%)',
            'items' => 'perCentDiskIOUtilization.0',
            'oid' => '.1.3.6.1.4.1.15497.1.1.1.3.0',
            'get_iid' => '',
            'oidn' => 'ASYNCOS-MAIL-MIB::perCentDiskIOUtilization.0',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'ASYNCOS-MAIL-MIB::perCentDiskIOUtilization.0',
            'enterprise' => '15497',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.IRONPORT',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'ironport_queue_usage',
            'class' => 'IRONPORT',
            'lapse' => '300',
            'descr' => 'USO DE LA COLA (%)',
            'items' => 'perCentQueueUtilization.0',
            'oid' => '.1.3.6.1.4.1.15497.1.1.1.4.0',
            'get_iid' => '',
            'oidn' => 'ASYNCOS-MAIL-MIB::perCentQueueUtilization.0',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'ASYNCOS-MAIL-MIB::perCentQueueUtilization.0',
            'enterprise' => '15497',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.IRONPORT',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'ironport_open_files',
            'class' => 'IRONPORT',
            'lapse' => '300',
            'descr' => 'FICHEROS/SOCKETS ABIERTOS',
            'items' => 'openFilesOrSockets.0',
            'oid' => '.1.3.6.1.4.1.15497.1.1.1.19.0',
            'get_iid' => '',
            'oidn' => 'ASYNCOS-MAIL-MIB::openFilesOrSockets.0',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'ASYNCOS-MAIL-MIB::openFilesOrSockets.0',
            'enterprise' => '15497',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.IRONPORT',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'ironport_mail_threads',
            'class' => 'IRONPORT',
            'lapse' => '300',
            'descr' => 'THREADS DE CORREO',
            'items' => 'mailTransferThreads.0',
            'oid' => '.1.3.6.1.4.1.15497.1.1.1.20.0',
            'get_iid' => '',
            'oidn' => 'ASYNCOS-MAIL-MIB::mailTransferThreads.0',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'ASYNCOS-MAIL-MIB::mailTransferThreads.0',
            'enterprise' => '15497',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.IRONPORT',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'ironport_dns_failures',
            'class' => 'IRONPORT',
            'lapse' => '300',
            'descr' => 'FALLOS EN DNS',
            'items' => 'outstandingDNSRequests.0|pendingDNSRequests.0',
            'oid' => '.1.3.6.1.4.1.15497.1.1.1.15.0|.1.3.6.1.4.1.15497.1.1.1.16.0',
            'get_iid' => '',
            'oidn' => 'ASYNCOS-MAIL-MIB::outstandingDNSRequests.0|ASYNCOS-MAIL-MIB::pendingDNSRequests.0',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'ASYNCOS-MAIL-MIB::outstandingDNSRequests.0',
            'enterprise' => '15497',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.IRONPORT',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'ironport_queue_messages',
            'class' => 'IRONPORT',
            'lapse' => '300',
            'descr' => 'MENSAJES EN LA COLA DE TRABAJO',
            'items' => 'workQueueMessages.0',
            'oid' => '.1.3.6.1.4.1.15497.1.1.1.11.0',
            'get_iid' => '',
            'oidn' => 'ASYNCOS-MAIL-MIB::workQueueMessages.0',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'ASYNCOS-MAIL-MIB::workQueueMessages.0',
            'enterprise' => '15497',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.IRONPORT',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'ironport_oldest_message',
            'class' => 'IRONPORT',
            'lapse' => '300',
            'descr' => 'TIEMPO EN COLA DEL MENSAJE MAS ANTIGUO',
            'items' => 'oldestMessageAge.0',
            'oid' => '.1.3.6.1.4.1.15497.1.1.1.14.0',
            'get_iid' => '',
            'oidn' => 'ASYNCOS-MAIL-MIB::oldestMessageAge.0',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'ASYNCOS-MAIL-MIB::oldestMessageAge.0',
            'enterprise' => '15497',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.IRONPORT',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'ironport_fanrpms1',
            'class' => 'IRONPORT',
            'lapse' => '300',
            'descr' => 'VELOCIDAD VENTILADOR (FAN 1)',
            'items' => 'fanRPMs.1',
            'oid' => '.1.3.6.1.4.1.15497.1.1.1.10.1.2.1',
            'get_iid' => '',
            'oidn' => 'ASYNCOS-MAIL-MIB::fanRPMs.1',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'ASYNCOS-MAIL-MIB::fanRPMs.1',
            'enterprise' => '15497',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.IRONPORT',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'ironport_fanrpms2',
            'class' => 'IRONPORT',
            'lapse' => '300',
            'descr' => 'VELOCIDAD VENTILADOR (FAN 2)',
            'items' => 'fanRPMs.2',
            'oid' => '.1.3.6.1.4.1.15497.1.1.1.10.1.2.2',
            'get_iid' => '',
            'oidn' => 'ASYNCOS-MAIL-MIB::fanRPMs.2',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'ASYNCOS-MAIL-MIB::fanRPMs.2',
            'enterprise' => '15497',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.IRONPORT',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'ironport_temperature1',
            'class' => 'IRONPORT',
            'lapse' => '300',
            'descr' => 'TEMPERATURA',
            'items' => 'degreesCelsius.1',
            'oid' => '.1.3.6.1.4.1.15497.1.1.1.9.1.2.1',
            'get_iid' => '',
            'oidn' => 'ASYNCOS-MAIL-MIB::degreesCelsius.1',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'ASYNCOS-MAIL-MIB::degreesCelsius.1',
            'enterprise' => '15497',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.IRONPORT',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'ironport_keyexpiration',
            'class' => 'IRONPORT',
            'lapse' => '300',
            'descr' => 'CADUCIDAD DE LICENCIAS',
            'items' => 'Dias hasta la caducidad',
            'oid' => '.1.3.6.1.4.1.15497.1.1.1.12.1.4.IID',
            'get_iid' => 'keyDescription',
            'oidn' => 'keySecondsUntilExpire.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'Dias',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'ASYNCOS-MAIL-MIB::keyExpirationTable',
            'enterprise' => '15497',
            'esp' => 'o1/86400',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.IRONPORT',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'ironport_update_fail',
            'class' => 'IRONPORT',
            'lapse' => '300',
            'descr' => 'FALLOS AL ACTUALIZAR',
            'items' => 'updateFailures',
            'oid' => '.1.3.6.1.4.1.15497.1.1.1.13.1.4.IID',
            'get_iid' => 'updateServiceName',
            'oidn' => 'updateFailures.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'COUNTER',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'ASYNCOS-MAIL-MIB::updateTable',
            'enterprise' => '15497',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.IRONPORT',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'ironport_update_rate',
            'class' => 'IRONPORT',
            'lapse' => '300',
            'descr' => 'TASA DE ACTUALIZACIONES',
            'items' => 'updates',
            'oid' => '.1.3.6.1.4.1.15497.1.1.1.13.1.3.IID',
            'get_iid' => 'updateServiceName',
            'oidn' => 'updates.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'COUNTER',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'ASYNCOS-MAIL-MIB::updateTable',
            'enterprise' => '15497',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.IRONPORT',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'ironport_raid_status',
            'class' => 'IRONPORT',
            'lapse' => '300',
            'descr' => 'ESTADO DEL RAID',
            'items' => 'driveHealthy(1)|driveRebuild(3)|driveFailure(2)|unk',
            'oid' => '.1.3.6.1.4.1.15497.1.1.1.18.1.2.IID',
            'get_iid' => 'raidID',
            'oidn' => 'raidStatus.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_SOLID',
            'vlabel' => 'estado',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'ASYNCOS-MAIL-MIB::raidTable',
            'enterprise' => '15497',
            'esp' => 'MAP(1)(1,0,0,0)|MAP(3)(0,1,0,0)|MAP(2)(0,0,1,0)|MAP(4)(0,0,0,1)',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.IRONPORT',
      );


?>
