<?php

		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'dell_powersup_stat',
            'class' => 'DELL',
            'lapse' => '300',
            'descr' => 'FUENTE DE ALIMENTACION - ESTADO',
            'items' => 'Full(8)|Loading(7)|Down(1)|Attempt(2)|Init(3)|2W(4)|ExchSt(5)|Exch(6)',
            'oid' => '.1.3.6.1.4.1.674.10892.1.600.12.1.5.IID',
            'get_iid' => 'powerSupplyLocationName',
            'oidn' => 'powerSupplyStatus.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_SOLID',
            'vlabel' => 'estado',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '0',
            'myrange' => 'MIB-Dell-10892::powerSupplyTable',
            'enterprise' => '674',
            'esp' => 'MAP(8)(1,0,0,0,0,0,0,0)|MAP(7)(0,1,0,0,0,0,0,0)|MAP(1)(0,0,1,0,0,0,0,0)|MAP(2)(0,0,0,1,0,0,0,0)|MAP(3)(0,0,0,0,1,0,0,0)|MAP(4)(0,0,0,0,0,1,0,0)|MAP(5)(0,0,0,0,0,0,1,0)|MAP(6)(0,0,0,0,0,0,0,1)',
            'params' => '',
            'itil_type' => '4',
            'apptype' => 'HW.DELL',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'dell_powersup_gstat',
            'class' => 'DELL',
            'lapse' => '300',
            'descr' => 'FUENTE DE ALIMENTACION - ESTADO GLOBAL',
            'items' => 'ok(3)|unknown(2)|critical(5)|nonCritical(4)|nonRecoverable(6)|other(1)',
            'oid' => '.1.3.6.1.4.1.674.10892.1.200.10.1.9.IID',
            'get_iid' => 'systemStatechassisIndex',
            'oidn' => 'systemStatePowerSupplyStatusCombined.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_SOLID',
            'vlabel' => 'estado',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '0',
            'myrange' => 'MIB-Dell-10892::systemStateTable',
            'enterprise' => '674',
            'esp' => 'MAP(3)(0,0,0,0,0,1)|MAP(2)(0,0,0,0,1,0)|MAP(5)(0,0,0,1,0,0)|MAP(4)(0,0,1,0,0,0)|MAP(6)(0,1,0,0,0,0)|MAP(1)(1,0,0,0,0,0)',
            'params' => '',
            'itil_type' => '4',
            'apptype' => 'HW.DELL',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'dell_volt_gstat',
            'class' => 'DELL',
            'lapse' => '300',
            'descr' => 'VOLTAJE - ESTADO GLOBAL',
            'items' => 'ok(3)|unknown(2)|critical(5)|nonCritical(4)|nonRecoverable(6)|other(1)',
            'oid' => '.1.3.6.1.4.1.674.10892.1.200.10.1.12.IID',
            'get_iid' => 'systemStatechassisIndex',
            'oidn' => 'systemStateVoltageStatusCombined.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_SOLID',
            'vlabel' => 'estado',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '0',
            'myrange' => 'MIB-Dell-10892::systemStateTable',
            'enterprise' => '674',
            'esp' => 'MAP(3)(0,0,0,0,0,1)|MAP(2)(0,0,0,0,1,0)|MAP(5)(0,0,0,1,0,0)|MAP(4)(0,0,1,0,0,0)|MAP(6)(0,1,0,0,0,0)|MAP(1)(1,0,0,0,0,0)',
            'params' => '',
            'itil_type' => '4',
            'apptype' => 'HW.DELL',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'dell_coold_gstat',
            'class' => 'DELL',
            'lapse' => '300',
            'descr' => 'VENTILADORES - ESTADO GLOBAL',
            'items' => 'ok(3)|unknown(2)|critical(5)|nonCritical(4)|nonRecoverable(6)|other(1)',
            'oid' => '.1.3.6.1.4.1.674.10892.1.200.10.1.21.IID',
            'get_iid' => 'systemStatechassisIndex',
            'oidn' => 'systemStateCoolingDeviceStatusCombined.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_SOLID',
            'vlabel' => 'estado',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '0',
            'myrange' => 'MIB-Dell-10892::systemStateTable',
            'enterprise' => '674',
            'esp' => 'MAP(3)(0,0,0,0,0,1)|MAP(2)(0,0,0,0,1,0)|MAP(5)(0,0,0,1,0,0)|MAP(4)(0,0,1,0,0,0)|MAP(6)(0,1,0,0,0,0)|MAP(1)(1,0,0,0,0,0)',
            'params' => '',
            'itil_type' => '4',
            'apptype' => 'HW.DELL',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'dell_temp_gstat',
            'class' => 'DELL',
            'lapse' => '300',
            'descr' => 'TEMPERATURA - ESTADO GLOBAL',
            'items' => 'ok(3)|unknown(2)|critical(5)|nonCritical(4)|nonRecoverable(6)|other(1)',
            'oid' => '.1.3.6.1.4.1.674.10892.1.200.10.1.24.IID',
            'get_iid' => 'systemStatechassisIndex',
            'oidn' => 'systemStateTemperatureStatusCombined.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_SOLID',
            'vlabel' => 'estado',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '0',
            'myrange' => 'MIB-Dell-10892::systemStateTable',
            'enterprise' => '674',
            'esp' => 'MAP(3)(0,0,0,0,0,1)|MAP(2)(0,0,0,0,1,0)|MAP(5)(0,0,0,1,0,0)|MAP(4)(0,0,1,0,0,0)|MAP(6)(0,1,0,0,0,0)|MAP(1)(1,0,0,0,0,0)',
            'params' => '',
            'itil_type' => '4',
            'apptype' => 'HW.DELL',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'dell_memory_gstat',
            'class' => 'DELL',
            'lapse' => '300',
            'descr' => 'MEMORIA - ESTADO GLOBAL',
            'items' => 'ok(3)|unknown(2)|critical(5)|nonCritical(4)|nonRecoverable(6)|other(1)',
            'oid' => '.1.3.6.1.4.1.674.10892.1.200.10.1.27.IID',
            'get_iid' => 'systemStatechassisIndex',
            'oidn' => 'systemStateMemoryDeviceStatusCombined.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_SOLID',
            'vlabel' => 'estado',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '0',
            'myrange' => 'MIB-Dell-10892::systemStateTable',
            'enterprise' => '674',
            'esp' => 'MAP(3)(0,0,0,0,0,1)|MAP(2)(0,0,0,0,1,0)|MAP(5)(0,0,0,1,0,0)|MAP(4)(0,0,1,0,0,0)|MAP(6)(0,1,0,0,0,0)|MAP(1)(1,0,0,0,0,0)',
            'params' => '',
            'itil_type' => '4',
            'apptype' => 'HW.DELL',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'dell_chasis_gstat',
            'class' => 'DELL',
            'lapse' => '300',
            'descr' => 'INTRUSION CHASIS - ESTADO GLOBAL',
            'items' => 'ok(3)|unknown(2)|critical(5)|nonCritical(4)|nonRecoverable(6)|other(1)',
            'oid' => '.1.3.6.1.4.1.674.10892.1.200.10.1.30.IID',
            'get_iid' => 'systemStatechassisIndex',
            'oidn' => 'systemStateChassisIntrusionStatusCombined.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_SOLID',
            'vlabel' => 'estado',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '0',
            'myrange' => 'MIB-Dell-10892::systemStateTable',
            'enterprise' => '674',
            'esp' => 'MAP(3)(0,0,0,0,0,1)|MAP(2)(0,0,0,0,1,0)|MAP(5)(0,0,0,1,0,0)|MAP(4)(0,0,1,0,0,0)|MAP(6)(0,1,0,0,0,0)|MAP(1)(1,0,0,0,0,0)',
            'params' => '',
            'itil_type' => '4',
            'apptype' => 'HW.DELL',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'dell_power_gstat',
            'class' => 'DELL',
            'lapse' => '300',
            'descr' => 'POTENCIA - ESTADO GLOBAL',
            'items' => 'ok(3)|unknown(2)|critical(5)|nonCritical(4)|nonRecoverable(6)|other(1)',
            'oid' => '.1.3.6.1.4.1.674.10892.1.200.10.1.42.IID',
            'get_iid' => 'systemStatechassisIndex',
            'oidn' => 'systemStatePowerUnitStatusCombined.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_SOLID',
            'vlabel' => 'estado',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '0',
            'myrange' => 'MIB-Dell-10892::systemStateTable',
            'enterprise' => '674',
            'esp' => 'MAP(3)(0,0,0,0,0,1)|MAP(2)(0,0,0,0,1,0)|MAP(5)(0,0,0,1,0,0)|MAP(4)(0,0,1,0,0,0)|MAP(6)(0,1,0,0,0,0)|MAP(1)(1,0,0,0,0,0)',
            'params' => '',
            'itil_type' => '4',
            'apptype' => 'HW.DELL',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'dell_coolu_gstat',
            'class' => 'DELL',
            'lapse' => '300',
            'descr' => 'VENTILACION - ESTADO GLOBAL',
            'items' => 'ok(3)|unknown(2)|critical(5)|nonCritical(4)|nonRecoverable(6)|other(1)',
            'oid' => '.1.3.6.1.4.1.674.10892.1.200.10.1.44.IID',
            'get_iid' => 'systemStatechassisIndex',
            'oidn' => 'systemStateCoolingUnitStatusCombined.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_SOLID',
            'vlabel' => 'estado',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '0',
            'myrange' => 'MIB-Dell-10892::systemStateTable',
            'enterprise' => '674',
            'esp' => 'MAP(3)(0,0,0,0,0,1)|MAP(2)(0,0,0,0,1,0)|MAP(5)(0,0,0,1,0,0)|MAP(4)(0,0,1,0,0,0)|MAP(6)(0,1,0,0,0,0)|MAP(1)(1,0,0,0,0,0)',
            'params' => '',
            'itil_type' => '4',
            'apptype' => 'HW.DELL',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'dell_proc_gstat',
            'class' => 'DELL',
            'lapse' => '300',
            'descr' => 'PROCESADOR - ESTADO GLOBAL',
            'items' => 'ok(3)|unknown(2)|critical(5)|nonCritical(4)|nonRecoverable(6)|other(1)',
            'oid' => '.1.3.6.1.4.1.674.10892.1.200.10.1.50.IID',
            'get_iid' => 'systemStatechassisIndex',
            'oidn' => 'systemStateProcessorDeviceStatusCombined.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_SOLID',
            'vlabel' => 'estado',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '0',
            'myrange' => 'MIB-Dell-10892::systemStateTable',
            'enterprise' => '674',
            'esp' => 'MAP(3)(0,0,0,0,0,1)|MAP(2)(0,0,0,0,1,0)|MAP(5)(0,0,0,1,0,0)|MAP(4)(0,0,1,0,0,0)|MAP(6)(0,1,0,0,0,0)|MAP(1)(1,0,0,0,0,0)',
            'params' => '',
            'itil_type' => '4',
            'apptype' => 'HW.DELL',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'dell_battery_gstat',
            'class' => 'DELL',
            'lapse' => '300',
            'descr' => 'BATERIA - ESTADO GLOBAL',
            'items' => 'ok(3)|unknown(2)|critical(5)|nonCritical(4)|nonRecoverable(6)|other(1)',
            'oid' => '.1.3.6.1.4.1.674.10892.1.200.10.1.52.IID',
            'get_iid' => 'systemStatechassisIndex',
            'oidn' => 'systemStateBatteryStatusCombined.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_SOLID',
            'vlabel' => 'estado',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '0',
            'myrange' => 'MIB-Dell-10892::systemStateTable',
            'enterprise' => '674',
            'esp' => 'MAP(3)(0,0,0,0,0,1)|MAP(2)(0,0,0,0,1,0)|MAP(5)(0,0,0,1,0,0)|MAP(4)(0,0,1,0,0,0)|MAP(6)(0,1,0,0,0,0)|MAP(1)(1,0,0,0,0,0)',
            'params' => '',
            'itil_type' => '4',
            'apptype' => 'HW.DELL',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'dell_adisk_stat',
            'class' => 'DELL',
            'lapse' => '300',
            'descr' => 'ARRAY DE DISCOS - ESTADO DISCO',
            'items' => 'ok(3)|unknown(2)|critical(5)|nonCritical(4)|nonRecoverable(6)|other(1)',
            'oid' => '.1.3.6.1.4.1.674.10893.1.20.130.4.1.4.IID',
            'get_iid' => 'arrayDiskName',
            'oidn' => 'arrayDiskState.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_SOLID',
            'vlabel' => 'estado',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '0',
            'myrange' => 'StorageManagement-MIB::arrayDiskTable',
            'enterprise' => '674',
            'esp' => 'MAP(3)(0,0,0,0,0,1)|MAP(2)(0,0,0,0,1,0)|MAP(5)(0,0,0,1,0,0)|MAP(4)(0,0,1,0,0,0)|MAP(6)(0,1,0,0,0,0)|MAP(1)(1,0,0,0,0,0)',
            'params' => '',
            'itil_type' => '4',
            'apptype' => 'HW.DELL',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'dell_adisk_cstat',
            'class' => 'DELL',
            'lapse' => '300',
            'descr' => 'ARRAY DE DISCOS - ESTADO CONTROLADOR',
            'items' => 'ready(1)|offline(4)|failed(2)|degraded(6)|online(3)',
            'oid' => '.1.3.6.1.4.1.674.10893.1.20.130.1.1.5.IID',
            'get_iid' => 'controllerNumber',
            'oidn' => 'controllerState.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_SOLID',
            'vlabel' => 'estado',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '0',
            'myrange' => 'StorageManagement-MIB::controllerTable',
            'enterprise' => '674',
            'esp' => 'MAP(1)(0,0,0,0,1)|MAP(4)(0,0,0,1,0)|MAP(2)(0,0,1,0,0)|MAP(6)(0,1,0,0,0)|MAP(3)(1,0,0,0,0)',
            'params' => '',
            'itil_type' => '4',
            'apptype' => 'HW.DELL',
      );


?>
