<?php

		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'finjan_scan_reqs',
            'class' => 'FINJAN',
            'lapse' => '300',
            'descr' => 'TASA DE ESCANEO',
            'items' => 'vsScannerReqs-per-second.0',
            'oid' => '.1.3.6.1.4.1.6790.1.1.30.20.10.2.0',
            'get_iid' => '',
            'oidn' => 'FINJAN-MIB::vsScannerReqs-per-second.0',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'FINJAN-MIB::vsScannerReqs-per-second.0',
            'enterprise' => '6790',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.FINJAN',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'finjan_scan_thro',
            'class' => 'FINJAN',
            'lapse' => '300',
            'descr' => 'TASA DE TRANSFERENCIA',
            'items' => 'vsScannerThroughput-in-total.0|vsScannerThroughput-out-total.0',
            'oid' => '.1.3.6.1.4.1.6790.1.1.30.20.10.5.0|.1.3.6.1.4.1.6790.1.1.30.20.10.6.0',
            'get_iid' => '',
            'oidn' => 'FINJAN-MIB::vsScannerThroughput-in-total.0|FINJAN-MIB::vsScannerThroughput-out-total.0',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'FINJAN-MIB::vsScannerThroughput-in-total.0',
            'enterprise' => '6790',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.FINJAN',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'finjan_sum_block',
            'class' => 'FINJAN',
            'lapse' => '300',
            'descr' => 'PETICIONES BLOQUEADAS (TOTALES)',
            'items' => 'vsSummaryBlocked-total.0',
            'oid' => '.1.3.6.1.4.1.6790.1.1.30.20.11.1.0',
            'get_iid' => '',
            'oidn' => 'FINJAN-MIB::vsSummaryBlocked-total.0',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'COUNTER',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'FINJAN-MIB::vsSummaryBlocked-total.0',
            'enterprise' => '6790',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.FINJAN',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'finjan_det_block',
            'class' => 'FINJAN',
            'lapse' => '300',
            'descr' => 'PETICIONES BLOQUEADAS (DETALLE)',
            'items' => 'vsScannerBlocked-AV-total.0|vsScannerBlocked-BA-total.0|vsScannerBlocked-blackList-total.0|vsScannerBlocked-URLCat-total.0',
            'oid' => '.1.3.6.1.4.1.6790.1.1.30.20.11.2.0|.1.3.6.1.4.1.6790.1.1.30.20.11.3.0|.1.3.6.1.4.1.6790.1.1.30.20.11.4.0|.1.3.6.1.4.1.6790.1.1.30.20.11.5.0',
            'get_iid' => '',
            'oidn' => 'FINJAN-MIB::vsScannerBlocked-AV-total.0|FINJAN-MIB::vsScannerBlocked-BA-total.0|FINJAN-MIB::vsScannerBlocked-blackList-total.0|FINJAN-MIB::vsScannerBlocked-URLCat-total.0',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'COUNTER',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'FINJAN-MIB::vsScannerBlocked-AV-total.0',
            'enterprise' => '6790',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.FINJAN',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'finjan_sum_log',
            'class' => 'FINJAN',
            'lapse' => '300',
            'descr' => 'PETICIONES REGISTRADAS (TOTALES)',
            'items' => 'vsScannerLogged-total.0',
            'oid' => '.1.3.6.1.4.1.6790.1.1.30.20.12.1.0',
            'get_iid' => '',
            'oidn' => 'FINJAN-MIB::vsScannerLogged-total.0',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'COUNTER',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'FINJAN-MIB::vsScannerLogged-total.0',
            'enterprise' => '6790',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.FINJAN',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'finjan_det_log',
            'class' => 'FINJAN',
            'lapse' => '300',
            'descr' => 'PETICIONES REGISTRADAS (DETALLE)',
            'items' => 'vsScannerLogged-logsDb-total.0|vsScannerLogged-archive-total.0|vsScannerLogged-reportsDb-total.0|vsScannerLogged-syslog-total.0',
            'oid' => '.1.3.6.1.4.1.6790.1.1.30.20.12.2.0|.1.3.6.1.4.1.6790.1.1.30.20.12.3.0|.1.3.6.1.4.1.6790.1.1.30.20.12.4.0|.1.3.6.1.4.1.6790.1.1.30.20.12.5.0',
            'get_iid' => '',
            'oidn' => 'FINJAN-MIB::vsScannerLogged-logsDb-total.0|FINJAN-MIB::vsScannerLogged-archive-total.0|FINJAN-MIB::vsScannerLogged-reportsDb-total.0|FINJAN-MIB::vsScannerLogged-syslog-total.0',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'COUNTER',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'FINJAN-MIB::vsScannerLogged-logsDb-total.0',
            'enterprise' => '6790',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.FINJAN',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'finjan_scan_reqs_tot',
            'class' => 'FINJAN',
            'lapse' => '300',
            'descr' => 'PETICIONES ESCANEADAS (TOTALES)',
            'items' => 'vsScannerReqs-total.0',
            'oid' => '.1.3.6.1.4.1.6790.1.1.30.20.10.1.0',
            'get_iid' => '',
            'oidn' => 'FINJAN-MIB::vsScannerReqs-total.0',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'COUNTER',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'FINJAN-MIB::vsScannerReqs-total.0',
            'enterprise' => '6790',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.FINJAN',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'finjan_scan_reqs_det',
            'class' => 'FINJAN',
            'lapse' => '300',
            'descr' => 'PETICIONES ESCANEADAS (DETALLE)',
            'items' => 'vsHTTPReqs-total.0|vsHTTPSReqs-total.0|vsFTPReqs-total.0|vsICAPReqs-total.0',
            'oid' => '.1.3.6.1.4.1.6790.1.1.30.21.10.1.0|.1.3.6.1.4.1.6790.1.1.30.22.10.1.0|.1.3.6.1.4.1.6790.1.1.30.23.10.1.0|.1.3.6.1.4.1.6790.1.1.30.24.10.1.0',
            'get_iid' => '',
            'oidn' => 'FINJAN-MIB::vsHTTPReqs-total.0|FINJAN-MIB::vsHTTPSReqs-total.0|FINJAN-MIB::vsFTPReqs-total.0|FINJAN-MIB::vsICAPReqs-total.0',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'COUNTER',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'FINJAN-MIB::vsHTTPReqs-total.0',
            'enterprise' => '6790',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.FINJAN',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'finjan_http_thro',
            'class' => 'FINJAN',
            'lapse' => '300',
            'descr' => 'TASA DE TRANSFERENCIA HTTP',
            'items' => 'vsHTTPThroughput-in-total.0|vsHTTPThroughput-out-total.0',
            'oid' => '.1.3.6.1.4.1.6790.1.1.30.21.10.5.0|.1.3.6.1.4.1.6790.1.1.30.21.10.6.0',
            'get_iid' => '',
            'oidn' => 'FINJAN-MIB::vsHTTPThroughput-in-total.0|FINJAN-MIB::vsHTTPThroughput-out-total.0',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'FINJAN-MIB::vsHTTPThroughput-in-total.0',
            'enterprise' => '6790',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.FINJAN',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'finjan_http_block',
            'class' => 'FINJAN',
            'lapse' => '300',
            'descr' => 'PETICIONES HTTP BLOQUEADAS (TOTALES)',
            'items' => 'vsHTTPBlocked-total.0',
            'oid' => '.1.3.6.1.4.1.6790.1.1.30.21.11.1.0',
            'get_iid' => '',
            'oidn' => 'FINJAN-MIB::vsHTTPBlocked-total.0',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'COUNTER',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'FINJAN-MIB::vsHTTPBlocked-total.0',
            'enterprise' => '6790',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.FINJAN',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'finjan_http_block_det',
            'class' => 'FINJAN',
            'lapse' => '300',
            'descr' => 'PETICIONES HTTP BLOQUEADAS (DETALLE)',
            'items' => 'vsHTTPBlocked-AV-total.0|vsHTTPBlocked-BA-total.0|vsHTTPBlocked-blackList-total.0|vsHTTPBlocked-URLCat-total.0',
            'oid' => '.1.3.6.1.4.1.6790.1.1.30.21.11.2.0|.1.3.6.1.4.1.6790.1.1.30.21.11.3.0|.1.3.6.1.4.1.6790.1.1.30.21.11.4.0|.1.3.6.1.4.1.6790.1.1.30.21.11.5.0',
            'get_iid' => '',
            'oidn' => 'FINJAN-MIB::vsHTTPBlocked-AV-total.0|FINJAN-MIB::vsHTTPBlocked-BA-total.0|FINJAN-MIB::vsHTTPBlocked-blackList-total.0|FINJAN-MIB::vsHTTPBlocked-URLCat-total.0',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'COUNTER',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'FINJAN-MIB::vsHTTPBlocked-AV-total.0',
            'enterprise' => '6790',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.FINJAN',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'finjan_https_thro',
            'class' => 'FINJAN',
            'lapse' => '300',
            'descr' => 'TASA DE TRANSFERENCIA HTTPS',
            'items' => 'vsHTTPSThroughput-in-total.0|vsHTTPSThroughput-out-total.0',
            'oid' => '.1.3.6.1.4.1.6790.1.1.30.22.10.5.0|.1.3.6.1.4.1.6790.1.1.30.22.10.6.0',
            'get_iid' => '',
            'oidn' => 'FINJAN-MIB::vsHTTPSThroughput-in-total.0|FINJAN-MIB::vsHTTPSThroughput-out-total.0',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'FINJAN-MIB::vsHTTPSThroughput-in-total.0',
            'enterprise' => '6790',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.FINJAN',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'finjan_https_block',
            'class' => 'FINJAN',
            'lapse' => '300',
            'descr' => 'PETICIONES HTTPS BLOQUEADAS (TOTALES)',
            'items' => 'vsHTTPSBlocked-total.0',
            'oid' => '.1.3.6.1.4.1.6790.1.1.30.22.11.1.0',
            'get_iid' => '',
            'oidn' => 'FINJAN-MIB::vsHTTPSBlocked-total.0',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'COUNTER',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'FINJAN-MIB::vsHTTPSBlocked-total.0',
            'enterprise' => '6790',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.FINJAN',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'finjan_https_block_det',
            'class' => 'FINJAN',
            'lapse' => '300',
            'descr' => 'PETICIONES HTTPS BLOQUEADAS (DETALLE)',
            'items' => 'vsHTTPSBlocked-AV-total.0|vsHTTPSBlocked-BA-total.0|vsHTTPSBlocked-blackList-total.0|vsHTTPSBlocked-URLCat-total.0',
            'oid' => '.1.3.6.1.4.1.6790.1.1.30.22.11.2.0|.1.3.6.1.4.1.6790.1.1.30.22.11.3.0|.1.3.6.1.4.1.6790.1.1.30.22.11.4.0|.1.3.6.1.4.1.6790.1.1.30.22.11.5.0',
            'get_iid' => '',
            'oidn' => 'FINJAN-MIB::vsHTTPSBlocked-AV-total.0|FINJAN-MIB::vsHTTPSBlocked-BA-total.0|FINJAN-MIB::vsHTTPSBlocked-blackList-total.0|FINJAN-MIB::vsHTTPSBlocked-URLCat-total.0',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'COUNTER',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'FINJAN-MIB::vsHTTPSBlocked-AV-total.0',
            'enterprise' => '6790',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.FINJAN',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'finjan_ftp_thro',
            'class' => 'FINJAN',
            'lapse' => '300',
            'descr' => 'TASA DE TRANSFERENCIA FTP',
            'items' => 'vsFTPThroughput-in-total.0|vsFTPThroughput-out-total.0',
            'oid' => '.1.3.6.1.4.1.6790.1.1.30.23.10.5.0|.1.3.6.1.4.1.6790.1.1.30.23.10.6.0',
            'get_iid' => '',
            'oidn' => 'FINJAN-MIB::vsFTPThroughput-in-total.0|FINJAN-MIB::vsFTPThroughput-out-total.0',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'FINJAN-MIB::vsFTPThroughput-in-total.0',
            'enterprise' => '6790',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.FINJAN',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'finjan_ftp_block',
            'class' => 'FINJAN',
            'lapse' => '300',
            'descr' => 'PETICIONES FTP BLOQUEADAS (TOTALES)',
            'items' => 'vsFTPBlocked-total.0',
            'oid' => '.1.3.6.1.4.1.6790.1.1.30.23.11.1.0',
            'get_iid' => '',
            'oidn' => 'FINJAN-MIB::vsFTPBlocked-total.0',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'COUNTER',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'FINJAN-MIB::vsFTPBlocked-total.0',
            'enterprise' => '6790',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.FINJAN',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'finjan_ftp_block_det',
            'class' => 'FINJAN',
            'lapse' => '300',
            'descr' => 'PETICIONES FTP BLOQUEADAS (DETALLE)',
            'items' => 'vsFTPBlocked-AV-total.0|vsFTPBlocked-BA-total.0|vsFTPBlocked-blackList-total.0|vsFTPBlocked-URLCat-total.0',
            'oid' => '.1.3.6.1.4.1.6790.1.1.30.23.11.2.0|.1.3.6.1.4.1.6790.1.1.30.23.11.3.0|.1.3.6.1.4.1.6790.1.1.30.23.11.4.0|.1.3.6.1.4.1.6790.1.1.30.23.11.5.0',
            'get_iid' => '',
            'oidn' => 'FINJAN-MIB::vsFTPBlocked-AV-total.0|FINJAN-MIB::vsFTPBlocked-BA-total.0|FINJAN-MIB::vsFTPBlocked-blackList-total.0|FINJAN-MIB::vsFTPBlocked-URLCat-total.0',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'COUNTER',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'FINJAN-MIB::vsFTPBlocked-AV-total.0',
            'enterprise' => '6790',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.FINJAN',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'finjan_icap_thro',
            'class' => 'FINJAN',
            'lapse' => '300',
            'descr' => 'TASA DE TRANSFERENCIA ICAP',
            'items' => 'vsICAPThroughput-in-total.0|vsICAPThroughput-out-total.0',
            'oid' => '.1.3.6.1.4.1.6790.1.1.30.24.10.5.0|.1.3.6.1.4.1.6790.1.1.30.24.10.6.0',
            'get_iid' => '',
            'oidn' => 'FINJAN-MIB::vsICAPThroughput-in-total.0|FINJAN-MIB::vsICAPThroughput-out-total.0',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'FINJAN-MIB::vsICAPThroughput-in-total.0',
            'enterprise' => '6790',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.FINJAN',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'finjan_icap_block',
            'class' => 'FINJAN',
            'lapse' => '300',
            'descr' => 'PETICIONES ICAP BLOQUEADAS (TOTALES)',
            'items' => 'vsICAPBlocked-total.0',
            'oid' => '.1.3.6.1.4.1.6790.1.1.30.24.11.1.0',
            'get_iid' => '',
            'oidn' => 'FINJAN-MIB::vsICAPBlocked-total.0',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'COUNTER',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'FINJAN-MIB::vsICAPBlocked-total.0',
            'enterprise' => '6790',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.FINJAN',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'finjan_icap_block_det',
            'class' => 'FINJAN',
            'lapse' => '300',
            'descr' => 'PETICIONES ICAP BLOQUEADAS (DETALLE)',
            'items' => 'vsICAPBlocked-AV-total.0|vsICAPBlocked-BA-total.0|vsICAPBlocked-blackList-total.0|vsICAPBlocked-URLCat-total.0',
            'oid' => '.1.3.6.1.4.1.6790.1.1.30.24.11.2.0|.1.3.6.1.4.1.6790.1.1.30.24.11.3.0|.1.3.6.1.4.1.6790.1.1.30.24.11.4.0|.1.3.6.1.4.1.6790.1.1.30.24.11.5.0',
            'get_iid' => '',
            'oidn' => 'FINJAN-MIB::vsICAPBlocked-AV-total.0|FINJAN-MIB::vsICAPBlocked-BA-total.0|FINJAN-MIB::vsICAPBlocked-blackList-total.0|FINJAN-MIB::vsICAPBlocked-URLCat-total.0',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'COUNTER',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'FINJAN-MIB::vsICAPBlocked-AV-total.0',
            'enterprise' => '6790',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.FINJAN',
      );


?>
