#!/usr/bin/perl -w
#-------------------------------------------------------------------------------------------
# Fichero: cnm-appliance-setup (Debian 13) 
#-------------------------------------------------------------------------------------------
use strict;
use Getopt::Std;
use Cwd;
use Data::Dumper;

#-------------------------------------------------------------------------------------------
BEGIN {
  	$ENV{'MIBS'}='ALL';
  	$ENV{'PATH'}='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin';
	$ENV{'DEBIAN_FRONTEND'} = 'noninteractive';
}

#-------------------------------------------------------------------------------------------
my $APT_GET="/usr/bin/apt-get";
my $GIT="/usr/bin/git";

#-------------------------------------------------------------------------------------------
my @fpth = split ('/',$0,10);
my @fname = split ('\.',$fpth[$#fpth],10);
my $VERSION="1.0";
my $USAGE = <<USAGE;
CNM Installer $VERSION (c) s30labs

$fpth[$#fpth] 
$fpth[$#fpth] -h

-h : Ayuda
USAGE

#-------------------------------------------------------------------------------------------
my %opts=();
getopts("h",\%opts);
if ($opts{h}) { die $USAGE;}

#-------------------------------------------------------------------------------------------
# Valida que es Debian 13. Se usa /etc/os-release (parte de base-files, siempre presente)
# en lugar de lsb_release, que requiere el paquete lsb-release (no garantizado en base minima).
#-------------------------------------------------------------------------------------------
my %os_info=();
open (my $osfh,'<','/etc/os-release') or die "No puedo leer /etc/os-release: $!\n";
while (my $line = <$osfh>) {
    chomp $line;
    next unless $line =~ /^([A-Z_]+)=(.*)$/;
    my ($k,$v) = ($1,$2);
    $v =~ s/^"//; $v =~ s/"$//;          # quita comillas
    $os_info{$k} = $v;
}
close $osfh;

if (($os_info{'ID'} // '') !~ /^debian$/i) {
    print Dumper(\%os_info);
    die "Not a Debian distro ...\n";
}
if (($os_info{'VERSION_ID'} // '') ne '13') {
    print Dumper(\%os_info);
    die "Not a Debian 13 distro ...\n";
}



#-------------------------------------------------------------------------------------------
#-------------------------------------------------------------------------------------------
# 00. Paquetes minimos necesarios (openssh-server, ansible, git, vim, cpanminus)
#-------------------------------------------------------------------------------------------
#`apt-get update`;
#`apt-get install -y openssh-server`;
#`apt-get install -y git vim sudo gnupg2`;

# update: solo aviso (un repo flaky no debe tumbar la instalacion)
if (system("$APT_GET update") != 0) {
    print "**WARN** 'apt-get update' devolvio error; continuo con la cache disponible\n";
}
run_or_die("$APT_GET install -y openssh-server git vim sudo gnupg2 curl wget");
run_or_die("$APT_GET install -y python3 python3-minimal python3-pip ansible");
run_or_die("$APT_GET install -y cpanminus");

# ansible 2.10.8
#`apt-get install -y gnupg2 curl wget`;
#system ("curl -s 'https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x93C4A3FD7BB9C367' | gpg --dearmor > /etc/apt/trusted.gpg.d/ansible-archive-keyring.gpg");
#`echo "deb http://ppa.launchpad.net/ansible/ansible/ubuntu bionic main" > /etc/apt/sources.list.d/ansible.list`;
#`apt-get update`;

#deb13 `apt-get install -y python python3 python3-minimal python3-pip ansible`;
#`apt-get install -y python3 python3-minimal python3-pip ansible`;
my $pv = `pip3 --version`;
chomp $pv;
my $pip_version=0;
my $extra_option='';
##pip 23.2.1 from /usr/local/lib/python3.9/dist-packages/pip (python 3.9)
#if ($pv=~/pip (\d+\.\d+\.\d+) from/) { $pip_version=$1; $pip_version=~s/\.//g; $pip_version+=0; }
#if ($pip_version>=2321) { $extra_option='--root-user-action=ignore'; }
#`python3 -m pip install $extra_option --upgrade pip`;
#`python3 -m pip install $extra_option --upgrade ansible`;

#`apt-get install -y cpanminus`;

#-------------------------------------------------------------------------------------------
# 01. Git config
#-------------------------------------------------------------------------------------------
print "-" x70 ."\n";
print "cnm-core ($$)\n";
print "-" x70 ."\n";

system ("$GIT config --global http.sslVerify false");
system ("$GIT config --global commit.template /opt/cnm/.gitmessage");
system ("$GIT config --global core.editor vim");
system ("$GIT config --global push.default simple"); #No sube los branches (si no hay que poner matching).
system ("$GIT config --global pull.rebase false");

#-----------------------------------------------------
# 02. Clone/checkout repos: cnm, cnm-os, cnm-mibs, cnm-lang, cnm-sp
#-----------------------------------------------------
#-----------------------------------------------------
my @features = (
	{ 'name' => 'cnm', 'url' => 'https://github.com/s30labs/cnm.git' },
	{ 'name' => 'cnm-sp', 'url'  =>'https://github.com/s30labs/cnm-sp.git' },
	{ 'name' => 'cnm-mibs', 'url'  => 'https://github.com/s30labs/cnm-mibs.git' },
	{ 'name' => 'cnm-extras', 'url'  => 'https://github.com/s30labs/cnm-extras.git' }
);
foreach my $feat (@features) {
	print "-" x70, "\n";
	print "GET $feat->{'name'}...\n";
	print "-" x70, "\n";
	get_feature($feat->{'name'},$feat->{'url'});
}

#-------------------------------------------------------------------------------------------
# 03. Se crea /cfg/cnm_vars.yml si no existe
#-------------------------------------------------------------------------------------------
my $CNM_CFG_DIR='/cfg';
my $CNM_VARS_FILE='/cfg/cnm_vars.yml';
my $CNM_VARS = <<"CNMVARS";
---
# CNM Global Vars

key: gpl
ntpserver: pool.ntp.org
mtu: 1450
ansible_python_interpreter: /usr/bin/python3

CNMVARS


if (! -d $CNM_CFG_DIR) { system ("/bin/mkdir -p $CNM_CFG_DIR"); }
if (! -f $CNM_VARS_FILE) {
  open (F,">$CNM_VARS_FILE");
  print F $CNM_VARS;
  close F;
}

#-------------------------------------------------------------------------------------------
# 04. Se crea /cfg/ansible.hosts si no existe
#-------------------------------------------------------------------------------------------
my $ANSIBLE_HOSTS_FILE='/cfg/ansible.hosts';

if (! -f $ANSIBLE_HOSTS_FILE) {
  open (F,">$ANSIBLE_HOSTS_FILE");
  print F 'localhost';
  close F;
}

#-------------------------------------------------------------------------------------------
# 07. Se instalan paquetes de Debian y modulos de PERL
#-------------------------------------------------------------------------------------------
run_or_die("$APT_GET install -y python3 python3-minimal python3-pip python-is-python3 ansible");
my $cwd = cwd();
chdir('/opt/cnm/os/debian13');
#if (! -l '/usr/bin/python') { `ln -s /usr/bin/python3.13 /usr/bin/python`; }
my $cmd = "ansible-playbook -c local -i /cfg/ansible.hosts --tags base cnm.yml | tee /tmp/cnm-install-role-base.log";
print "Ejecutando $cmd ...\n";
#`$cmd`;
chdir($cwd);

#-------------------------------------------------------------------------------------------
#-------------------------------------------------------------------------------------------
#-------------------------------------------------------------------------------------------
#-------------------------------------------------------------------------------------------
#-------------------------------------------------------------------------------------------
sub get_feature {
my ($feature,$url) = @_;

  	my $BRANCH = 'master';
  	my $GIT = "/usr/bin/git";
  	my $user = 'git';
  	my ($rc,$cmd) = (0,'');

  	my $dir_local = '/opt/'.$feature;

  	if ((-d $dir_local) && (-d "$dir_local/.git")) {
		
  		chdir($dir_local);
  		print "pull from $url ...\n";
  		$cmd = "$GIT pull";
  		$rc = system ($cmd);
  		if ($rc !=0) { print "**WARN** $cmd (rc=$rc)\n"; }
  		$cmd = "$GIT checkout";
  		$rc = system ($cmd);
  		if ($rc !=0) { print "**WARN** $cmd (rc=$rc)\n"; }

  	}
  	else {

  		print "clone from $url ...\n";
		if (-d $dir_local) { 
			$cmd = "/bin/rm -rf $dir_local"; 
  			$rc = system ($cmd);
  			if ($rc !=0) { print "$cmd (rc=$rc)\n"; }
		}
  		$cmd = "$GIT clone -b $BRANCH $url $dir_local";
  		$rc = system ($cmd);
  		if ($rc !=0) { print "$cmd (rc=$rc)\n"; }

  		chdir $dir_local;
  	}

}

#-------------------------------------------------------------------------------------------
#-------------------------------------------------------------------------------------------
sub run_or_die {
my ($cmd) = @_;
   print "+ $cmd\n";
   my $rc = system($cmd);
   if ($rc != 0) {
      die "ERROR ejecutando: $cmd (rc=".($rc >> 8).")\n";
   }
}
