<?php

		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'cpq_fan_status',
            'class' => 'COMPAQ',
            'lapse' => '300',
            'descr' => 'ESTADO DEL VENTILADOR',
            'items' => 'cpqHeThermalSystemFanStatus.0',
            'oid' => '.1.3.6.1.4.1.232.6.2.6.4.0',
            'get_iid' => '',
            'oidn' => 'CPQHLTH-MIB::cpqHeThermalSystemFanStatus.0',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'CPQHLTH-MIB::cpqHeThermalSystemFanStatus.0',
            'enterprise' => '232',
            'esp' => '',
            'params' => '',
            'itil_type' => '4',
            'apptype' => 'HW.HP',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'cpq_tmp_status',
            'class' => 'COMPAQ',
            'lapse' => '300',
            'descr' => 'TEMPERATURA DEL SISTEMA',
            'items' => 'cpqHeThermalTempStatus.0',
            'oid' => '.1.3.6.1.4.1.232.6.2.6.3.0',
            'get_iid' => '',
            'oidn' => 'CPQHLTH-MIB::cpqHeThermalTempStatus.0',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'CPQHLTH-MIB::cpqHeThermalTempStatus.0',
            'enterprise' => '232',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'HW.HP',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'cpq_cpu_status',
            'class' => 'COMPAQ',
            'lapse' => '300',
            'descr' => 'TEMPERATURA DE LA CPU',
            'items' => 'cpqHeThermalCpuFanStatus.0',
            'oid' => '.1.3.6.1.4.1.232.6.2.6.5.0',
            'get_iid' => '',
            'oidn' => 'CPQHLTH-MIB::cpqHeThermalCpuFanStatus.0',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'CPQHLTH-MIB::cpqHeThermalCpuFanStatus.0',
            'enterprise' => '232',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'HW.HP',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'cpq_os_threads',
            'class' => 'COMPAQ',
            'lapse' => '300',
            'descr' => 'THREADS DE SISTEMA OPERATIVO',
            'items' => 'cpqOsSystemThreads.0',
            'oid' => '.1.3.6.1.4.1.232.19.2.2.3.0',
            'get_iid' => '',
            'oidn' => 'CPQOS-MIB::cpqOsSystemThreads.0',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'CPQOS-MIB::cpqOsSystemThreads.0',
            'enterprise' => '232',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'HW.HP',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'cpq_os_context',
            'class' => 'COMPAQ',
            'lapse' => '300',
            'descr' => 'CAMBIOS DE CONTEXTO EN SISTEMA OPERATIVO',
            'items' => 'cpqOsSysContextSwitchesPersec.0',
            'oid' => '.1.3.6.1.4.1.232.19.2.2.4.0',
            'get_iid' => '',
            'oidn' => 'CPQOS-MIB::cpqOsSysContextSwitchesPersec.0',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'CPQOS-MIB::cpqOsSysContextSwitchesPersec.0',
            'enterprise' => '232',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'HW.HP',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'cpq_os_cpu_queue',
            'class' => 'COMPAQ',
            'lapse' => '300',
            'descr' => 'TRHEADS EN COLA DE PROCESO',
            'items' => 'cpqOsSysCpuQueueLength.0',
            'oid' => '.1.3.6.1.4.1.232.19.2.2.5.0',
            'get_iid' => '',
            'oidn' => 'CPQOS-MIB::cpqOsSysCpuQueueLength.0',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'CPQOS-MIB::cpqOsSysCpuQueueLength.0',
            'enterprise' => '232',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'HW.HP',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'cpq_os_processes',
            'class' => 'COMPAQ',
            'lapse' => '300',
            'descr' => 'NUMERO DE PROCESOS',
            'items' => 'cpqOsSysProcesses.0',
            'oid' => '.1.3.6.1.4.1.232.19.2.2.6.0',
            'get_iid' => '',
            'oidn' => 'CPQOS-MIB::cpqOsSysProcesses.0',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'CPQOS-MIB::cpqOsSysProcesses.0',
            'enterprise' => '232',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'HW.HP',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'cpq_processor_status',
            'class' => 'COMPAQ',
            'lapse' => '300',
            'descr' => 'ESTADO DEL PROCESADOR',
            'items' => 'cpqOsProcessorStatus.0',
            'oid' => '.1.3.6.1.4.1.232.19.2.3.1.0',
            'get_iid' => '',
            'oidn' => 'CPQOS-MIB::cpqOsProcessorStatus.0',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'CPQOS-MIB::cpqOsProcessorStatus.0',
            'enterprise' => '232',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'HW.HP',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'cpq_tcp_errors',
            'class' => 'COMPAQ',
            'lapse' => '300',
            'descr' => 'ERRORES EN CONEXIONES TCP',
            'items' => 'cpqOsTcpConnectionFailures.1',
            'oid' => '.1.3.6.1.4.1.232.19.2.11.2.1.7.1',
            'get_iid' => '',
            'oidn' => 'CPQOS-MIB::cpqOsTcpConnectionFailures.1',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'CPQOS-MIB::cpqOsTcpConnectionFailures.1',
            'enterprise' => '232',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'HW.HP',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'cpq_powersup_stat',
            'class' => 'COMPAQ',
            'lapse' => '300',
            'descr' => 'FUENTE DE ALIMENTACION - ESTADO',
            'items' => 'cpqHeFltTolPowerSupplyCondition',
            'oid' => '.1.3.6.1.4.1.232.6.2.9.3.1.4.IID',
            'get_iid' => 'cpqHeFltTolPowerSupplyBay',
            'oidn' => 'cpqHeFltTolPowerSupplyCondition.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'CPQHLTH-MIB::cpqHeFltTolPowerSupplyTable',
            'enterprise' => '232',
            'esp' => '',
            'params' => '',
            'itil_type' => '4',
            'apptype' => 'HW.HP',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'cpq_powersup_capacity',
            'class' => 'COMPAQ',
            'lapse' => '300',
            'descr' => 'FUENTE DE ALIMENTACION - POTENCIA EN USO',
            'items' => 'cpqHeFltTolPowerSupplyCapacityUsed',
            'oid' => '.1.3.6.1.4.1.232.6.2.9.3.1.7.IID',
            'get_iid' => 'cpqHeFltTolPowerSupplyBay',
            'oidn' => 'cpqHeFltTolPowerSupplyCapacityUsed.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'CPQHLTH-MIB::cpqHeFltTolPowerSupplyTable',
            'enterprise' => '232',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'HW.HP',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'cpq_cpu_usage',
            'class' => 'COMPAQ',
            'lapse' => '300',
            'descr' => 'CPU - PORCENTAJE DE USO',
            'items' => 'cpqHoCpuUtilFiveMin',
            'oid' => '.1.3.6.1.4.1.232.11.2.3.1.1.3.IID',
            'get_iid' => 'cpqHoCpuUtilUnitIndex',
            'oidn' => 'cpqHoCpuUtilFiveMin.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'CPQHOST-MIB::cpqHoCpuUtilTable',
            'enterprise' => '232',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'HW.HP',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'cpq_disk_usage',
            'class' => 'COMPAQ',
            'lapse' => '300',
            'descr' => 'USO DE DISCO',
            'items' => 'cpqHoFileSysSpaceUsed|cpqHoFileSysSpaceTotal',
            'oid' => '.1.3.6.1.4.1.232.11.2.4.1.1.4.IID|.1.3.6.1.4.1.232.11.2.4.1.1.3.IID',
            'get_iid' => 'cpqHoFileSysDesc',
            'oidn' => 'cpqHoFileSysSpaceUsed.IID|cpqHoFileSysSpaceTotal.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'CPQHOST-MIB::cpqHoFileSysTable',
            'enterprise' => '232',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'HW.HP',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'cpq_cpu_interrupts',
            'class' => 'COMPAQ',
            'lapse' => '300',
            'descr' => 'CPU - INTERRUPCIONES POR SEGUNDO',
            'items' => 'cpqOsCpuInterruptsPerSec',
            'oid' => '.1.3.6.1.4.1.232.19.2.3.2.1.3.IID',
            'get_iid' => 'cpqOsCpuInstance',
            'oidn' => 'cpqOsCpuInterruptsPerSec.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'CPQOS-MIB::cpqOsProcessorTable',
            'enterprise' => '232',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'HW.HP',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'cpq_da_log_status',
            'class' => 'COMPAQ',
            'lapse' => '300',
            'descr' => 'ESTADO LOGICO DEL ARRAY DE DISCOS',
            'items' => 'cpqDaLogDrvStatus',
            'oid' => '.1.3.6.1.4.1.232.3.2.3.1.1.4.IID',
            'get_iid' => 'cpqDaLogDrvIndex',
            'oidn' => 'cpqDaLogDrvStatus.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'CPQIDA-MIB::cpqDaLogDrvTable',
            'enterprise' => '232',
            'esp' => '',
            'params' => '',
            'itil_type' => '4',
            'apptype' => 'HW.HP',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'cpq_da_phy_status',
            'class' => 'COMPAQ',
            'lapse' => '300',
            'descr' => 'ESTADO FISICO DEL ARRAY DE DISCOS',
            'items' => 'cpqDaPhyDrvStatus',
            'oid' => '.1.3.6.1.4.1.232.3.2.5.1.1.6.IID',
            'get_iid' => 'cpqDaPhyDrvIndex',
            'oidn' => 'cpqDaPhyDrvStatus.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'CPQIDA-MIB::cpqDaPhyDrvTable',
            'enterprise' => '232',
            'esp' => '',
            'params' => '',
            'itil_type' => '4',
            'apptype' => 'HW.HP',
      );


?>
