<?php

		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'pkteer_link_bytes',
            'class' => 'PACKETEER',
            'lapse' => '300',
            'descr' => 'ACTIVIDAD (BYTES) EN EL LINK',
            'items' => 'linkByteCount',
            'oid' => '.1.3.6.1.4.1.2334.2.1.2.2.1.3.IID',
            'get_iid' => 'linkName',
            'oidn' => 'linkByteCount.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'COUNTER',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'PACKETEER-MIB::linkTable',
            'enterprise' => '2334',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.PACKETEER',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'pkteer_link_pkts',
            'class' => 'PACKETEER',
            'lapse' => '300',
            'descr' => 'ACTIVIDAD (PAQUETES POR TIPO) EN EL LINK',
            'items' => 'linkPkts|linkDataPkts',
            'oid' => '.1.3.6.1.4.1.2334.2.1.2.2.1.5.IID|.1.3.6.1.4.1.2334.2.1.2.2.1.6.IID',
            'get_iid' => 'linkName',
            'oidn' => 'linkPkts.IID|linkDataPkts.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'COUNTER',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'PACKETEER-MIB::linkTable',
            'enterprise' => '2334',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.PACKETEER',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'pkteer_link_ret_bytes',
            'class' => 'PACKETEER',
            'lapse' => '300',
            'descr' => 'RETRANSMISIONES (BYTES) TCP EN EL LINK',
            'items' => 'linkReTxByteCount',
            'oid' => '.1.3.6.1.4.1.2334.2.1.2.2.1.28.IID',
            'get_iid' => 'linkName',
            'oidn' => 'linkReTxByteCount.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'COUNTER',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'PACKETEER-MIB::linkTable',
            'enterprise' => '2334',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.PACKETEER',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'pkteer_link_ret_pkts',
            'class' => 'PACKETEER',
            'lapse' => '300',
            'descr' => 'RETRANSMISIONES (PAQUETES) TCP EN EL LINK',
            'items' => 'linkReTxs|linkReTxTosses',
            'oid' => '.1.3.6.1.4.1.2334.2.1.2.2.1.7.IID|.1.3.6.1.4.1.2334.2.1.2.2.1.8.IID',
            'get_iid' => 'linkName',
            'oidn' => 'linkReTxs.IID|linkReTxTosses.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'COUNTER',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'PACKETEER-MIB::linkTable',
            'enterprise' => '2334',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.PACKETEER',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'pkteer_link_tcp_peak',
            'class' => 'PACKETEER',
            'lapse' => '300',
            'descr' => 'CONEXIONES TCP MAXIMAS EN EL LINK',
            'items' => 'linkPeakTcpConns',
            'oid' => '.1.3.6.1.4.1.2334.2.1.2.2.1.12.IID',
            'get_iid' => 'linkName',
            'oidn' => 'linkPeakTcpConns.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'PACKETEER-MIB::linkTable',
            'enterprise' => '2334',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.PACKETEER',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'pkteer_link_tcp',
            'class' => 'PACKETEER',
            'lapse' => '300',
            'descr' => 'CONEXIONES TCP EN EL LINK',
            'items' => 'linkTcpConnInits|linkTcpConnRefuses|linkTcpConnIgnores|linkTcpConnAborts',
            'oid' => '.1.3.6.1.4.1.2334.2.1.2.2.1.13.IID|.1.3.6.1.4.1.2334.2.1.2.2.1.15.IID|.1.3.6.1.4.1.2334.2.1.2.2.1.16.IID|.1.3.6.1.4.1.2334.2.1.2.2.1.17.IID',
            'get_iid' => 'linkName',
            'oidn' => 'linkTcpConnInits.IID|linkTcpConnRefuses.IID|linkTcpConnIgnores.IID|linkTcpConnAborts.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'COUNTER',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'PACKETEER-MIB::linkTable',
            'enterprise' => '2334',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.PACKETEER',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'pkteer_link_pkts_tot',
            'class' => 'PACKETEER',
            'lapse' => '300',
            'descr' => 'ACTIVIDAD (PAQUETES TOTALES) EN EL LINK',
            'items' => 'linkTotalRxPkts|linkTotalTxPkts',
            'oid' => '.1.3.6.1.4.1.2334.2.1.2.2.1.30.IID|.1.3.6.1.4.1.2334.2.1.2.2.1.31.IID',
            'get_iid' => 'linkName',
            'oidn' => 'linkTotalRxPkts.IID|linkTotalTxPkts.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'COUNTER',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'PACKETEER-MIB::linkTable',
            'enterprise' => '2334',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.PACKETEER',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'pkteer_link_pkts_drop',
            'class' => 'PACKETEER',
            'lapse' => '300',
            'descr' => 'PAQUETES PERDIDOS EN EL LINK',
            'items' => 'linkRxPktDrops|linkTxPktDrops',
            'oid' => '.1.3.6.1.4.1.2334.2.1.2.2.1.33.IID|.1.3.6.1.4.1.2334.2.1.2.2.1.34.IID',
            'get_iid' => 'linkName',
            'oidn' => 'linkRxPktDrops.IID|linkTxPktDrops.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'COUNTER',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'PACKETEER-MIB::linkTable',
            'enterprise' => '2334',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.PACKETEER',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'pkteer_link_pkts_err',
            'class' => 'PACKETEER',
            'lapse' => '300',
            'descr' => 'ERRORES EN EL LINK',
            'items' => 'linkRxErrors|linkTxErrors',
            'oid' => '.1.3.6.1.4.1.2334.2.1.2.2.1.35.IID|.1.3.6.1.4.1.2334.2.1.2.2.1.36.IID',
            'get_iid' => 'linkName',
            'oidn' => 'linkRxErrors.IID|linkTxErrors.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'COUNTER',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'PACKETEER-MIB::linkTable',
            'enterprise' => '2334',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.PACKETEER',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'pkteer_class_bytes',
            'class' => 'PACKETEER',
            'lapse' => '300',
            'descr' => 'ACTIVIDAD (BYTES) EN LA CLASE',
            'items' => 'classByteCount',
            'oid' => '.1.3.6.1.4.1.2334.2.1.4.2.1.5.IID',
            'get_iid' => 'className',
            'oidn' => 'classByteCount.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'COUNTER',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'PACKETEER-MIB::classTable',
            'enterprise' => '2334',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.PACKETEER',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'pkteer_class_pkts',
            'class' => 'PACKETEER',
            'lapse' => '300',
            'descr' => 'ACTIVIDAD (PAQUETES) EN LA CLASE',
            'items' => 'classPkts|classDataPkts',
            'oid' => '.1.3.6.1.4.1.2334.2.1.4.2.1.7.IID|.1.3.6.1.4.1.2334.2.1.4.2.1.8.IID',
            'get_iid' => 'className',
            'oidn' => 'classPkts.IID|classDataPkts.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'COUNTER',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'PACKETEER-MIB::classTable',
            'enterprise' => '2334',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.PACKETEER',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'pkteer_class_ret_bytes',
            'class' => 'PACKETEER',
            'lapse' => '300',
            'descr' => 'RETRANSMISIONES (BYTES) TCP EN LA CLASE',
            'items' => 'classReTxByteCount',
            'oid' => '.1.3.6.1.4.1.2334.2.1.4.2.1.34.IID',
            'get_iid' => 'className',
            'oidn' => 'classReTxByteCount.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'COUNTER',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'PACKETEER-MIB::classTable',
            'enterprise' => '2334',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.PACKETEER',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'pkteer_class_ret_pkts',
            'class' => 'PACKETEER',
            'lapse' => '300',
            'descr' => 'RETRANSMISIONES (PAQUETES) TCP EN LA CLASE',
            'items' => 'classReTxs|classReTxTosses',
            'oid' => '.1.3.6.1.4.1.2334.2.1.4.2.1.9.IID|.1.3.6.1.4.1.2334.2.1.4.2.1.10.IID',
            'get_iid' => 'className',
            'oidn' => 'classReTxs.IID|classReTxTosses.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'COUNTER',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'PACKETEER-MIB::classTable',
            'enterprise' => '2334',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.PACKETEER',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'pkteer_class_tcp',
            'class' => 'PACKETEER',
            'lapse' => '300',
            'descr' => 'CONEXIONES TCP EN LA CLASE',
            'items' => 'classTcpConnInits|classTcpConnRefuses|classTcpConnIgnores|classTcpConnAborts',
            'oid' => '.1.3.6.1.4.1.2334.2.1.4.2.1.15.IID|.1.3.6.1.4.1.2334.2.1.4.2.1.17.IID|.1.3.6.1.4.1.2334.2.1.4.2.1.18.IID|.1.3.6.1.4.1.2334.2.1.4.2.1.19.IID',
            'get_iid' => 'className',
            'oidn' => 'classTcpConnInits.IID|classTcpConnRefuses.IID|classTcpConnIgnores.IID|classTcpConnAborts.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'COUNTER',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'PACKETEER-MIB::classTable',
            'enterprise' => '2334',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.PACKETEER',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'pkteer_class_rate',
            'class' => 'PACKETEER',
            'lapse' => '300',
            'descr' => 'TASA (bps) LA CLASE',
            'items' => 'classCurrentRate',
            'oid' => '.1.3.6.1.4.1.2334.2.1.4.2.1.37.IID',
            'get_iid' => 'className',
            'oidn' => 'classCurrentRate.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'PACKETEER-MIB::classTable',
            'enterprise' => '2334',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.PACKETEER',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'pkteer_class_exchtime',
            'class' => 'PACKETEER',
            'lapse' => '300',
            'descr' => 'DURACION DE LAS CONEXIONES EN LA CLASE',
            'items' => 'classPktExchangeTime',
            'oid' => '.1.3.6.1.4.1.2334.2.1.4.2.1.38.IID',
            'get_iid' => 'className',
            'oidn' => 'classPktExchangeTime.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'COUNTER',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'PACKETEER-MIB::classTable',
            'enterprise' => '2334',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.PACKETEER',
      );


?>
