<?php

		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'jun_fwdd_cpu',
            'class' => 'JUNIPER',
            'lapse' => '300',
            'descr' => 'USO DE CPU DEL FWDD',
            'items' => 'jnxFwddMicroKernelCPUUsage.0|jnxFwddRtThreadsCPUUsage.0',
            'oid' => '.1.3.6.1.4.1.2636.3.34.1.1.0|.1.3.6.1.4.1.2636.3.34.1.2.0',
            'get_iid' => '',
            'oidn' => 'JUNIPER-CHASSIS-FWDD-MIB::jnxFwddMicroKernelCPUUsage.0|JUNIPER-CHASSIS-FWDD-MIB::jnxFwddRtThreadsCPUUsage.0',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => '%',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'JUNIPER-CHASSIS-FWDD-MIB::jnxFwddMicroKernelCPUUsage.0',
            'enterprise' => '2636',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.JUNIPER',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'jun_fwdd_heap',
            'class' => 'JUNIPER',
            'lapse' => '300',
            'descr' => 'USO DE HEAP DEL FWDD',
            'items' => 'jnxFwddHeapUsage.0',
            'oid' => '.1.3.6.1.4.1.2636.3.34.1.3.0',
            'get_iid' => '',
            'oidn' => 'JUNIPER-CHASSIS-FWDD-MIB::jnxFwddHeapUsage.0',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => '%',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'JUNIPER-CHASSIS-FWDD-MIB::jnxFwddHeapUsage.0',
            'enterprise' => '2636',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.JUNIPER',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'jun_fwdd_dma',
            'class' => 'JUNIPER',
            'lapse' => '300',
            'descr' => 'USO DE DMA DEL FWDD',
            'items' => 'jnxFwddDmaMemUsage.0',
            'oid' => '.1.3.6.1.4.1.2636.3.34.1.4.0',
            'get_iid' => '',
            'oidn' => 'JUNIPER-CHASSIS-FWDD-MIB::jnxFwddDmaMemUsage.0',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => '%',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'JUNIPER-CHASSIS-FWDD-MIB::jnxFwddDmaMemUsage.0',
            'enterprise' => '2636',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.JUNIPER',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'jun_spu_cpu',
            'class' => 'JUNIPER',
            'lapse' => '300',
            'descr' => 'USO DE CPU EN SPU',
            'items' => 'jnxJsSPUMonitoringCPUUsage',
            'oid' => '.1.3.6.1.4.1.2636.3.39.1.12.1.1.1.4.IID',
            'get_iid' => 'JUNIPER-SRX5000-SPU-MONITORING-MIB::jnxJsSPUMonitoringIndex',
            'oidn' => 'jnxJsSPUMonitoringCPUUsage.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'JUNIPER-SRX5000-SPU-MONITORING-MIB::jnxJsSPUMonitoringObjectsTable',
            'enterprise' => '2636',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.JUNIPER',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'jun_spu_mem',
            'class' => 'JUNIPER',
            'lapse' => '300',
            'descr' => 'USO DE MEMORIA EN SPU',
            'items' => 'jnxJsSPUMonitoringMemoryUsage',
            'oid' => '.1.3.6.1.4.1.2636.3.39.1.12.1.1.1.5.IID',
            'get_iid' => 'JUNIPER-SRX5000-SPU-MONITORING-MIB::jnxJsSPUMonitoringIndex',
            'oidn' => 'jnxJsSPUMonitoringMemoryUsage.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'JUNIPER-SRX5000-SPU-MONITORING-MIB::jnxJsSPUMonitoringObjectsTable',
            'enterprise' => '2636',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.JUNIPER',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'jun_spu_ses',
            'class' => 'JUNIPER',
            'lapse' => '300',
            'descr' => 'SESIONES EN SPU',
            'items' => 'jnxJsSPUMonitoringCurrentFlowSession',
            'oid' => '.1.3.6.1.4.1.2636.3.39.1.12.1.1.1.6.IID',
            'get_iid' => 'JUNIPER-SRX5000-SPU-MONITORING-MIB::jnxJsSPUMonitoringIndex',
            'oidn' => 'jnxJsSPUMonitoringCurrentFlowSession.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'JUNIPER-SRX5000-SPU-MONITORING-MIB::jnxJsSPUMonitoringObjectsTable',
            'enterprise' => '2636',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.JUNIPER',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'jun_spu_cp_ses',
            'class' => 'JUNIPER',
            'lapse' => '300',
            'descr' => 'SESIONES CP EN SPU',
            'items' => 'jnxJsSPUMonitoringCurrentCPSession',
            'oid' => '.1.3.6.1.4.1.2636.3.39.1.12.1.1.1.8.IID',
            'get_iid' => 'JUNIPER-SRX5000-SPU-MONITORING-MIB::jnxJsSPUMonitoringIndex',
            'oidn' => 'jnxJsSPUMonitoringCurrentCPSession.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'JUNIPER-SRX5000-SPU-MONITORING-MIB::jnxJsSPUMonitoringObjectsTable',
            'enterprise' => '2636',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.JUNIPER',
      );


?>
