<?php

		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'zfs_cache_size',
            'class' => 'ZFS',
            'lapse' => '300',
            'descr' => 'ZFS - ESPACIO DE CACHE',
            'items' => 'zfsARCSizeKB.0|zfsARCMetadataSizeKB.0|zfsARCDataSizeKB.0',
            'oid' => '.1.3.6.1.4.1.25359.1.2.1.0|.1.3.6.1.4.1.25359.1.2.2.0|.1.3.6.1.4.1.25359.1.2.3.0',
            'get_iid' => '',
            'oidn' => 'NYMNETWORKS-MIB::zfsARCSizeKB.0|NYMNETWORKS-MIB::zfsARCMetadataSizeKB.0|NYMNETWORKS-MIB::zfsARCDataSizeKB.0',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'NYMNETWORKS-MIB::zfsARCSizeKB.0',
            'enterprise' => '25359',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'HW.ZFS',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'zfs_cache_hits_Arc',
            'class' => 'ZFS',
            'lapse' => '300',
            'descr' => 'ZFS - ACCESOS A CACHE ARC',
            'items' => 'zfsARCHits.0|zfsARCMisses.0',
            'oid' => '.1.3.6.1.4.1.25359.1.2.4.0|.1.3.6.1.4.1.25359.1.2.5.0',
            'get_iid' => '',
            'oidn' => 'NYMNETWORKS-MIB::zfsARCHits.0|NYMNETWORKS-MIB::zfsARCMisses.0',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'NYMNETWORKS-MIB::zfsARCHits.0',
            'enterprise' => '25359',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'HW.ZFS',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'zfs_cache_hits_l2arc',
            'class' => 'ZFS',
            'lapse' => '300',
            'descr' => 'ZFS - ACCESOS A CACHE L2ARC',
            'items' => 'zfsL2ARCHits.0|zfsL2ARCMisses.0',
            'oid' => '.1.3.6.1.4.1.25359.1.3.1.0|.1.3.6.1.4.1.25359.1.3.2.0',
            'get_iid' => '',
            'oidn' => 'NYMNETWORKS-MIB::zfsL2ARCHits.0|NYMNETWORKS-MIB::zfsL2ARCMisses.0',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'NYMNETWORKS-MIB::zfsL2ARCHits.0',
            'enterprise' => '25359',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'HW.ZFS',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'zfs_cache_l2arc_rw',
            'class' => 'ZFS',
            'lapse' => '300',
            'descr' => 'ZFS - ACTIVIDAD EN CACHE L2ARC',
            'items' => 'zfsL2ARCReads.0|zfsL2ARCWrites.0',
            'oid' => '.1.3.6.1.4.1.25359.1.3.3.0|.1.3.6.1.4.1.25359.1.3.4.0',
            'get_iid' => '',
            'oidn' => 'NYMNETWORKS-MIB::zfsL2ARCReads.0|NYMNETWORKS-MIB::zfsL2ARCWrites.0',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'NYMNETWORKS-MIB::zfsL2ARCReads.0',
            'enterprise' => '25359',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'HW.ZFS',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'zfs_cache_rw',
            'class' => 'ZFS',
            'lapse' => '300',
            'descr' => 'ZFS - LECTURAS/ESCRITURAS',
            'items' => 'zfsReadKB.0|zfsReaddirKB.0|zfsWriteKB.0',
            'oid' => '.1.3.6.1.4.1.25359.1.4.1.0|.1.3.6.1.4.1.25359.1.4.2.0|.1.3.6.1.4.1.25359.1.4.3.0',
            'get_iid' => '',
            'oidn' => 'NYMNETWORKS-MIB::zfsReadKB.0|NYMNETWORKS-MIB::zfsReaddirKB.0|NYMNETWORKS-MIB::zfsWriteKB.0',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'NYMNETWORKS-MIB::zfsReadKB.0',
            'enterprise' => '25359',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'HW.ZFS',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'zfs_disk_usage_vol1',
            'class' => 'ZFS',
            'lapse' => '300',
            'descr' => 'ZFS - USO DE DISCO VOL1',
            'items' => 'zfsFilesystemAvailableMB.1|zfsFilesystemUsedMB.1',
            'oid' => '.1.3.6.1.4.1.25359.1.1.12.1|.1.3.6.1.4.1.25359.1.1.13.1',
            'get_iid' => '',
            'oidn' => 'NYMNETWORKS-MIB::zfsFilesystemAvailableMB.1|NYMNETWORKS-MIB::zfsFilesystemUsedMB.1',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'NYMNETWORKS-MIB::zfsFilesystemAvailableMB.1',
            'enterprise' => '25359',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'HW.ZFS',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'zfs_disk_usage_vol2',
            'class' => 'ZFS',
            'lapse' => '300',
            'descr' => 'ZFS - USO DE DISCO VOL2',
            'items' => 'zfsFilesystemAvailableMB.2|zfsFilesystemUsedMB.2',
            'oid' => '.1.3.6.1.4.1.25359.1.1.12.2|.1.3.6.1.4.1.25359.1.1.13.2',
            'get_iid' => '',
            'oidn' => 'NYMNETWORKS-MIB::zfsFilesystemAvailableMB.2|NYMNETWORKS-MIB::zfsFilesystemUsedMB.2',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'NYMNETWORKS-MIB::zfsFilesystemAvailableMB.2',
            'enterprise' => '25359',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'HW.ZFS',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'zfs_disk_usage_vol3',
            'class' => 'ZFS',
            'lapse' => '300',
            'descr' => 'ZFS - USO DE DISCO VOL3',
            'items' => 'zfsFilesystemAvailableMB.3|zfsFilesystemUsedMB.3',
            'oid' => '.1.3.6.1.4.1.25359.1.1.12.3|.1.3.6.1.4.1.25359.1.1.13.3',
            'get_iid' => '',
            'oidn' => 'NYMNETWORKS-MIB::zfsFilesystemAvailableMB.3|NYMNETWORKS-MIB::zfsFilesystemUsedMB.3',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'NYMNETWORKS-MIB::zfsFilesystemAvailableMB.3',
            'enterprise' => '25359',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'HW.ZFS',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'zfs_disk_usage_vol4',
            'class' => 'ZFS',
            'lapse' => '300',
            'descr' => 'ZFS - USO DE DISCO VOL4',
            'items' => 'zfsFilesystemAvailableMB.4|zfsFilesystemUsedMB.4',
            'oid' => '.1.3.6.1.4.1.25359.1.1.12.4|.1.3.6.1.4.1.25359.1.1.13.4',
            'get_iid' => '',
            'oidn' => 'NYMNETWORKS-MIB::zfsFilesystemAvailableMB.4|NYMNETWORKS-MIB::zfsFilesystemUsedMB.4',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'NYMNETWORKS-MIB::zfsFilesystemAvailableMB.4',
            'enterprise' => '25359',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'HW.ZFS',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'zfs_pool_health_vol1',
            'class' => 'ZFS',
            'lapse' => '300',
            'descr' => 'ZFS - ESTADO DEL POOL VOL1',
            'items' => 'online(1)|unknown(4)|faulted(3)|degraded(2)',
            'oid' => '.1.3.6.1.4.1.25359.1.1.4.1',
            'get_iid' => '',
            'oidn' => 'NYMNETWORKS-MIB::zfsPoolHealth.1',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_SOLID',
            'vlabel' => 'estado',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'NYMNETWORKS-MIB::zfsPoolHealth.1',
            'enterprise' => '25359',
            'esp' => 'MAP(1)(1,0,0,0)|MAP(4)(0,1,0,0)|MAP(3)(0,0,1,0)|MAP(2)(0,0,0,1)',
            'params' => '',
            'itil_type' => '4',
            'apptype' => 'HW.ZFS',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'zfs_pool_health_vol2',
            'class' => 'ZFS',
            'lapse' => '300',
            'descr' => 'ZFS - ESTADO DEL POOL VOL2',
            'items' => 'online(1)|unknown(4)|faulted(3)|degraded(2)',
            'oid' => '.1.3.6.1.4.1.25359.1.1.4.2',
            'get_iid' => '',
            'oidn' => 'NYMNETWORKS-MIB::zfsPoolHealth.2',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_SOLID',
            'vlabel' => 'estado',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'NYMNETWORKS-MIB::zfsPoolHealth.2',
            'enterprise' => '25359',
            'esp' => 'MAP(1)(1,0,0,0)|MAP(4)(0,1,0,0)|MAP(3)(0,0,1,0)|MAP(2)(0,0,0,1)',
            'params' => '',
            'itil_type' => '4',
            'apptype' => 'HW.ZFS',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'zfs_pool_health_vol3',
            'class' => 'ZFS',
            'lapse' => '300',
            'descr' => 'ZFS - ESTADO DEL POOL VOL3',
            'items' => 'online(1)|unknown(4)|faulted(3)|degraded(2)',
            'oid' => '.1.3.6.1.4.1.25359.1.1.4.3',
            'get_iid' => '',
            'oidn' => 'NYMNETWORKS-MIB::zfsPoolHealth.3',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_SOLID',
            'vlabel' => 'estado',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'NYMNETWORKS-MIB::zfsPoolHealth.3',
            'enterprise' => '25359',
            'esp' => 'MAP(1)(1,0,0,0)|MAP(4)(0,1,0,0)|MAP(3)(0,0,1,0)|MAP(2)(0,0,0,1)',
            'params' => '',
            'itil_type' => '4',
            'apptype' => 'HW.ZFS',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'zfs_pool_health_vol4',
            'class' => 'ZFS',
            'lapse' => '300',
            'descr' => 'ZFS - ESTADO DEL POOL VOL4',
            'items' => 'online(1)|unknown(4)|faulted(3)|degraded(2)',
            'oid' => '.1.3.6.1.4.1.25359.1.1.4.4',
            'get_iid' => '',
            'oidn' => 'NYMNETWORKS-MIB::zfsPoolHealth.4',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_SOLID',
            'vlabel' => 'estado',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'NYMNETWORKS-MIB::zfsPoolHealth.4',
            'enterprise' => '25359',
            'esp' => 'MAP(1)(1,0,0,0)|MAP(4)(0,1,0,0)|MAP(3)(0,0,1,0)|MAP(2)(0,0,0,1)',
            'params' => '',
            'itil_type' => '4',
            'apptype' => 'HW.ZFS',
      );


?>
