<?php

		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'ib_dns_nonaa_lat',
            'class' => 'INFOBLOX',
            'lapse' => '300',
            'descr' => 'LATENCIA DEL DNS (Non-AA)',
            'items' => 'ibNetworkMonitorDNSNonAAT5AvgLatency.0',
            'oid' => '.1.3.6.1.4.1.7779.3.1.1.2.1.3.1.2.2.1.0',
            'get_iid' => '',
            'oidn' => 'IB-PLATFORMONE-MIB::ibNetworkMonitorDNSNonAAT5AvgLatency.0',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'microseconds',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'IB-PLATFORMONE-MIB::ibNetworkMonitorDNSNonAAT5AvgLatency.0',
            'enterprise' => '7779',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.INFOBLOX',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'ib_dns_nonaa_cnt',
            'class' => 'INFOBLOX',
            'lapse' => '300',
            'descr' => 'CONSULTAS AL DNS (Non-AA)',
            'items' => 'ibNetworkMonitorDNSNonAAT5Count.0',
            'oid' => '.1.3.6.1.4.1.7779.3.1.1.2.1.3.1.2.2.2.0',
            'get_iid' => '',
            'oidn' => 'IB-PLATFORMONE-MIB::ibNetworkMonitorDNSNonAAT5Count.0',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num. queries',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'IB-PLATFORMONE-MIB::ibNetworkMonitorDNSNonAAT5Count.0',
            'enterprise' => '7779',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.INFOBLOX',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'ib_dns_aa_lat',
            'class' => 'INFOBLOX',
            'lapse' => '300',
            'descr' => 'LATENCIA DEL DNS (AA)',
            'items' => 'ibNetworkMonitorDNSAAT5AvgLatency.0',
            'oid' => '.1.3.6.1.4.1.7779.3.1.1.2.1.3.1.3.2.1.0',
            'get_iid' => '',
            'oidn' => 'IB-PLATFORMONE-MIB::ibNetworkMonitorDNSAAT5AvgLatency.0',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'microseconds',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'IB-PLATFORMONE-MIB::ibNetworkMonitorDNSAAT5AvgLatency.0',
            'enterprise' => '7779',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.INFOBLOX',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'ib_dns_aa_cnt',
            'class' => 'INFOBLOX',
            'lapse' => '300',
            'descr' => 'CONSULTAS AL DNS (AA)',
            'items' => 'ibNetworkMonitorDNSAAT5Count.0',
            'oid' => '.1.3.6.1.4.1.7779.3.1.1.2.1.3.1.3.2.2.0',
            'get_iid' => '',
            'oidn' => 'IB-PLATFORMONE-MIB::ibNetworkMonitorDNSAAT5Count.0',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num. queries',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'IB-PLATFORMONE-MIB::ibNetworkMonitorDNSAAT5Count.0',
            'enterprise' => '7779',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.INFOBLOX',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'ib_cpu_temperature',
            'class' => 'INFOBLOX',
            'lapse' => '300',
            'descr' => 'TEMPERATURA DE LA CPU',
            'items' => 'ibCPUTemperature.0',
            'oid' => '.1.3.6.1.4.1.7779.3.1.1.2.1.1.0',
            'get_iid' => '',
            'oidn' => 'IB-PLATFORMONE-MIB::ibCPUTemperature.0',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'grados C',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'IB-PLATFORMONE-MIB::ibCPUTemperature.0',
            'enterprise' => '7779',
            'esp' => 'INT(o1)',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.INFOBLOX',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'ib_cpu_usage',
            'class' => 'INFOBLOX',
            'lapse' => '300',
            'descr' => 'USO DE CPU',
            'items' => 'ibSystemMonitorCpuUsage.0',
            'oid' => '.1.3.6.1.4.1.7779.3.1.1.2.1.8.1.1.0',
            'get_iid' => '',
            'oidn' => 'IB-PLATFORMONE-MIB::ibSystemMonitorCpuUsage.0',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'promedio',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'IB-PLATFORMONE-MIB::ibSystemMonitorCpuUsage.0',
            'enterprise' => '7779',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.INFOBLOX',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'ib_mem_usage',
            'class' => 'INFOBLOX',
            'lapse' => '300',
            'descr' => 'USO DE MEMORIA',
            'items' => 'ibSystemMonitorMemUsage.0',
            'oid' => '.1.3.6.1.4.1.7779.3.1.1.2.1.8.2.1.0',
            'get_iid' => '',
            'oidn' => 'IB-PLATFORMONE-MIB::ibSystemMonitorMemUsage.0',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'promedio',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'IB-PLATFORMONE-MIB::ibSystemMonitorMemUsage.0',
            'enterprise' => '7779',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.INFOBLOX',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'ib_dns_monitor',
            'class' => 'INFOBLOX',
            'lapse' => '300',
            'descr' => 'ESTADO DNS MONITOR',
            'items' => 'Activo(1)',
            'oid' => '.1.3.6.1.4.1.7779.3.1.1.2.1.3.1.1.0',
            'get_iid' => '',
            'oidn' => 'IB-PLATFORMONE-MIB::ibNetworkMonitorDNSActive.0',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'estado',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'IB-PLATFORMONE-MIB::ibNetworkMonitorDNSActive.0',
            'enterprise' => '7779',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.INFOBLOX',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'ib_dhcp_disc_req',
            'class' => 'INFOBLOX',
            'lapse' => '300',
            'descr' => 'MENSAJES DISCOVER/REQUEST',
            'items' => 'ibDhcpTotalNoOfDiscovers.0|ibDhcpTotalNoOfRequests.0',
            'oid' => '.1.3.6.1.4.1.7779.3.1.1.4.1.3.1.0|.1.3.6.1.4.1.7779.3.1.1.4.1.3.2.0',
            'get_iid' => '',
            'oidn' => 'IB-DHCPONE-MIB::ibDhcpTotalNoOfDiscovers.0|IB-DHCPONE-MIB::ibDhcpTotalNoOfRequests.0',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num. of msgs',
            'mode' => 'COUNTER',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'IB-DHCPONE-MIB::ibDhcpTotalNoOfDiscovers.0',
            'enterprise' => '7779',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.INFOBLOX',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'ib_dhcp_rel_off',
            'class' => 'INFOBLOX',
            'lapse' => '300',
            'descr' => 'MENSAJES DE RELEASE/OFFER',
            'items' => 'ibDhcpTotalNoOfReleases.0|ibDhcpTotalNoOfOffers.0',
            'oid' => '.1.3.6.1.4.1.7779.3.1.1.4.1.3.3.0|.1.3.6.1.4.1.7779.3.1.1.4.1.3.4.0',
            'get_iid' => '',
            'oidn' => 'IB-DHCPONE-MIB::ibDhcpTotalNoOfReleases.0|IB-DHCPONE-MIB::ibDhcpTotalNoOfOffers.0',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num. of msgs',
            'mode' => 'COUNTER',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'IB-DHCPONE-MIB::ibDhcpTotalNoOfReleases.0',
            'enterprise' => '7779',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.INFOBLOX',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'ib_dhcp_ack_nack',
            'class' => 'INFOBLOX',
            'lapse' => '300',
            'descr' => 'MENSAJES ACK/NACK',
            'items' => 'ibDhcpTotalNoOfAcks.0|ibDhcpTotalNoOfNacks.0',
            'oid' => '.1.3.6.1.4.1.7779.3.1.1.4.1.3.5.0|.1.3.6.1.4.1.7779.3.1.1.4.1.3.6.0',
            'get_iid' => '',
            'oidn' => 'IB-DHCPONE-MIB::ibDhcpTotalNoOfAcks.0|IB-DHCPONE-MIB::ibDhcpTotalNoOfNacks.0',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num. of msgs',
            'mode' => 'COUNTER',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'IB-DHCPONE-MIB::ibDhcpTotalNoOfAcks.0',
            'enterprise' => '7779',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.INFOBLOX',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'ib_dhcp_other',
            'class' => 'INFOBLOX',
            'lapse' => '300',
            'descr' => 'MENSAJES DECLINE/INFORM/OTHER',
            'items' => 'ibDhcpTotalNoOfDeclines.0|ibDhcpTotalNoOfInforms.0|ibDhcpTotalNoOfOthers.0',
            'oid' => '.1.3.6.1.4.1.7779.3.1.1.4.1.3.7.0|.1.3.6.1.4.1.7779.3.1.1.4.1.3.8.0|.1.3.6.1.4.1.7779.3.1.1.4.1.3.9.0',
            'get_iid' => '',
            'oidn' => 'IB-DHCPONE-MIB::ibDhcpTotalNoOfDeclines.0|IB-DHCPONE-MIB::ibDhcpTotalNoOfInforms.0|IB-DHCPONE-MIB::ibDhcpTotalNoOfOthers.0',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num. of msgs',
            'mode' => 'COUNTER',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'IB-DHCPONE-MIB::ibDhcpTotalNoOfDeclines.0',
            'enterprise' => '7779',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.INFOBLOX',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'ib_status_dhcp',
            'class' => 'INFOBLOX',
            'lapse' => '300',
            'descr' => 'ESTADO SERVICIO DHCP',
            'items' => 'Ok(1)|Warn(2)|Failed(3)|Inactive(4)|Unk(5)',
            'oid' => '.1.3.6.1.4.1.7779.3.1.1.2.1.9.1.2.1',
            'get_iid' => '',
            'oidn' => 'IB-PLATFORMONE-MIB::ibServiceStatus.1',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_SOLID',
            'vlabel' => 'estado',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'IB-PLATFORMONE-MIB::ibServiceStatus.1',
            'enterprise' => '7779',
            'esp' => 'MAP(1)(1,0,0,0,0)|MAP(2)(0,1,0,0,0)|MAP(3)(0,0,1,0,0)|MAP(4)(0,0,0,1,0)|MAP(5)(0,0,0,0,1)',
            'params' => '',
            'itil_type' => '4',
            'apptype' => 'NET.INFOBLOX',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'ib_status_dns',
            'class' => 'INFOBLOX',
            'lapse' => '300',
            'descr' => 'ESTADO SERVICIO DNS',
            'items' => 'Ok(1)|Warn(2)|Failed(3)|Inactive(4)|Unk(5)',
            'oid' => '.1.3.6.1.4.1.7779.3.1.1.2.1.9.1.2.2',
            'get_iid' => '',
            'oidn' => 'IB-PLATFORMONE-MIB::ibServiceStatus.2',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_SOLID',
            'vlabel' => 'estado',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'IB-PLATFORMONE-MIB::ibServiceStatus.2',
            'enterprise' => '7779',
            'esp' => 'MAP(1)(1,0,0,0,0)|MAP(2)(0,1,0,0,0)|MAP(3)(0,0,1,0,0)|MAP(4)(0,0,0,1,0)|MAP(5)(0,0,0,0,1)',
            'params' => '',
            'itil_type' => '4',
            'apptype' => 'NET.INFOBLOX',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'ib_status_ntp',
            'class' => 'INFOBLOX',
            'lapse' => '300',
            'descr' => 'ESTADO SERVICIO NTP',
            'items' => 'Ok(1)|Warn(2)|Failed(3)|Inactive(4)|Unk(5)',
            'oid' => '.1.3.6.1.4.1.7779.3.1.1.2.1.9.1.2.3',
            'get_iid' => '',
            'oidn' => 'IB-PLATFORMONE-MIB::ibServiceStatus.3',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_SOLID',
            'vlabel' => 'estado',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'IB-PLATFORMONE-MIB::ibServiceStatus.3',
            'enterprise' => '7779',
            'esp' => 'MAP(1)(1,0,0,0,0)|MAP(2)(0,1,0,0,0)|MAP(3)(0,0,1,0,0)|MAP(4)(0,0,0,1,0)|MAP(5)(0,0,0,0,1)',
            'params' => '',
            'itil_type' => '4',
            'apptype' => 'NET.INFOBLOX',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'ib_status_radius',
            'class' => 'INFOBLOX',
            'lapse' => '300',
            'descr' => 'ESTADO SERVICIO RADIUS',
            'items' => 'Ok(1)|Warn(2)|Failed(3)|Inactive(4)|Unk(5)',
            'oid' => '.1.3.6.1.4.1.7779.3.1.1.2.1.9.1.2.4',
            'get_iid' => '',
            'oidn' => 'IB-PLATFORMONE-MIB::ibServiceStatus.4',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_SOLID',
            'vlabel' => 'estado',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'IB-PLATFORMONE-MIB::ibServiceStatus.4',
            'enterprise' => '7779',
            'esp' => 'MAP(1)(1,0,0,0,0)|MAP(2)(0,1,0,0,0)|MAP(3)(0,0,1,0,0)|MAP(4)(0,0,0,1,0)|MAP(5)(0,0,0,0,1)',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.INFOBLOX',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'ib_status_tftp',
            'class' => 'INFOBLOX',
            'lapse' => '300',
            'descr' => 'ESTADO SERVICIO TFTP',
            'items' => 'Ok(1)|Warn(2)|Failed(3)|Inactive(4)|Unk(5)',
            'oid' => '.1.3.6.1.4.1.7779.3.1.1.2.1.9.1.2.5',
            'get_iid' => '',
            'oidn' => 'IB-PLATFORMONE-MIB::ibServiceStatus.5',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_SOLID',
            'vlabel' => 'estado',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'IB-PLATFORMONE-MIB::ibServiceStatus.5',
            'enterprise' => '7779',
            'esp' => 'MAP(1)(1,0,0,0,0)|MAP(2)(0,1,0,0,0)|MAP(3)(0,0,1,0,0)|MAP(4)(0,0,0,1,0)|MAP(5)(0,0,0,0,1)',
            'params' => '',
            'itil_type' => '4',
            'apptype' => 'NET.INFOBLOX',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'ib_status_httpf',
            'class' => 'INFOBLOX',
            'lapse' => '300',
            'descr' => 'ESTADO SERVICIO HTTP-FILE-DIST',
            'items' => 'Ok(1)|Warn(2)|Failed(3)|Inactive(4)|Unk(5)',
            'oid' => '.1.3.6.1.4.1.7779.3.1.1.2.1.9.1.2.6',
            'get_iid' => '',
            'oidn' => 'IB-PLATFORMONE-MIB::ibServiceStatus.6',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_SOLID',
            'vlabel' => 'estado',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '0',
            'myrange' => 'IB-PLATFORMONE-MIB::ibServiceStatus.6',
            'enterprise' => '7779',
            'esp' => 'MAP(1)(1,0,0,0,0)|MAP(2)(0,1,0,0,0)|MAP(3)(0,0,1,0,0)|MAP(4)(0,0,0,1,0)|MAP(5)(0,0,0,0,1)',
            'params' => '',
            'itil_type' => '4',
            'apptype' => 'NET.INFOBLOX',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'ib_status_ftp',
            'class' => 'INFOBLOX',
            'lapse' => '300',
            'descr' => 'ESTADO SERVICIO FTP',
            'items' => 'Ok(1)|Warn(2)|Failed(3)|Inactive(4)|Unk(5)',
            'oid' => '.1.3.6.1.4.1.7779.3.1.1.2.1.9.1.2.7',
            'get_iid' => '',
            'oidn' => 'IB-PLATFORMONE-MIB::ibServiceStatus.7',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_SOLID',
            'vlabel' => 'estado',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '0',
            'myrange' => 'IB-PLATFORMONE-MIB::ibServiceStatus.7',
            'enterprise' => '7779',
            'esp' => 'MAP(1)(1,0,0,0,0)|MAP(2)(0,1,0,0,0)|MAP(3)(0,0,1,0,0)|MAP(4)(0,0,0,1,0)|MAP(5)(0,0,0,0,1)',
            'params' => '',
            'itil_type' => '4',
            'apptype' => 'NET.INFOBLOX',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'ib_status_btools_move',
            'class' => 'INFOBLOX',
            'lapse' => '300',
            'descr' => 'ESTADO SERVICIO BLOXTOOLS-MOVE',
            'items' => 'Ok(1)|Warn(2)|Failed(3)|Inactive(4)|Unk(5)',
            'oid' => '.1.3.6.1.4.1.7779.3.1.1.2.1.9.1.2.8',
            'get_iid' => '',
            'oidn' => 'IB-PLATFORMONE-MIB::ibServiceStatus.8',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_SOLID',
            'vlabel' => 'estado',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '0',
            'myrange' => 'IB-PLATFORMONE-MIB::ibServiceStatus.8',
            'enterprise' => '7779',
            'esp' => 'MAP(1)(1,0,0,0,0)|MAP(2)(0,1,0,0,0)|MAP(3)(0,0,1,0,0)|MAP(4)(0,0,0,1,0)|MAP(5)(0,0,0,0,1)',
            'params' => '',
            'itil_type' => '4',
            'apptype' => 'NET.INFOBLOX',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'ib_status_btools',
            'class' => 'INFOBLOX',
            'lapse' => '300',
            'descr' => 'ESTADO SERVICIO BLOXTOOLS',
            'items' => 'Ok(1)|Warn(2)|Failed(3)|Inactive(4)|Unk(5)',
            'oid' => '.1.3.6.1.4.1.7779.3.1.1.2.1.9.1.2.9',
            'get_iid' => '',
            'oidn' => 'IB-PLATFORMONE-MIB::ibServiceStatus.9',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_SOLID',
            'vlabel' => 'estado',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '0',
            'myrange' => 'IB-PLATFORMONE-MIB::ibServiceStatus.9',
            'enterprise' => '7779',
            'esp' => 'MAP(1)(1,0,0,0,0)|MAP(2)(0,1,0,0,0)|MAP(3)(0,0,1,0,0)|MAP(4)(0,0,0,1,0)|MAP(5)(0,0,0,0,1)',
            'params' => '',
            'itil_type' => '4',
            'apptype' => 'NET.INFOBLOX',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'ib_status_node',
            'class' => 'INFOBLOX',
            'lapse' => '300',
            'descr' => 'ESTADO SERVICIO DEL NODO',
            'items' => 'Ok(1)|Warn(2)|Failed(3)|Inactive(4)|Unk(5)',
            'oid' => '.1.3.6.1.4.1.7779.3.1.1.2.1.10.1.2.10',
            'get_iid' => '',
            'oidn' => 'IB-PLATFORMONE-MIB::ibNode1ServiceStatus.10',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_SOLID',
            'vlabel' => 'estado',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'IB-PLATFORMONE-MIB::ibNode1ServiceStatus.10',
            'enterprise' => '7779',
            'esp' => 'MAP(1)(1,0,0,0,0)|MAP(2)(0,1,0,0,0)|MAP(3)(0,0,1,0,0)|MAP(4)(0,0,0,1,0)|MAP(5)(0,0,0,0,1)',
            'params' => '',
            'itil_type' => '4',
            'apptype' => 'NET.INFOBLOX',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'ib_status_disk',
            'class' => 'INFOBLOX',
            'lapse' => '300',
            'descr' => 'ESTADO SERVICIO DISCO',
            'items' => 'Ok(1)|Warn(2)|Failed(3)|Inactive(4)|Unk(5)',
            'oid' => '.1.3.6.1.4.1.7779.3.1.1.2.1.10.1.2.11',
            'get_iid' => '',
            'oidn' => 'IB-PLATFORMONE-MIB::ibNode1ServiceStatus.11',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_SOLID',
            'vlabel' => 'estado',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'IB-PLATFORMONE-MIB::ibNode1ServiceStatus.11',
            'enterprise' => '7779',
            'esp' => 'MAP(1)(1,0,0,0,0)|MAP(2)(0,1,0,0,0)|MAP(3)(0,0,1,0,0)|MAP(4)(0,0,0,1,0)|MAP(5)(0,0,0,0,1)',
            'params' => '',
            'itil_type' => '4',
            'apptype' => 'NET.INFOBLOX',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'ib_status_lan1',
            'class' => 'INFOBLOX',
            'lapse' => '300',
            'descr' => 'ESTADO SERVICIO ETH-LAN1',
            'items' => 'Ok(1)|Warn(2)|Failed(3)|Inactive(4)|Unk(5)',
            'oid' => '.1.3.6.1.4.1.7779.3.1.1.2.1.10.1.2.12',
            'get_iid' => '',
            'oidn' => 'IB-PLATFORMONE-MIB::ibNode1ServiceStatus.12',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_SOLID',
            'vlabel' => 'estado',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '0',
            'myrange' => 'IB-PLATFORMONE-MIB::ibNode1ServiceStatus.12',
            'enterprise' => '7779',
            'esp' => 'MAP(1)(1,0,0,0,0)|MAP(2)(0,1,0,0,0)|MAP(3)(0,0,1,0,0)|MAP(4)(0,0,0,1,0)|MAP(5)(0,0,0,0,1)',
            'params' => '',
            'itil_type' => '4',
            'apptype' => 'NET.INFOBLOX',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'ib_status_lan2',
            'class' => 'INFOBLOX',
            'lapse' => '300',
            'descr' => 'ESTADO SERVICIO ETH-LAN2',
            'items' => 'Ok(1)|Warn(2)|Failed(3)|Inactive(4)|Unk(5)',
            'oid' => '.1.3.6.1.4.1.7779.3.1.1.2.1.10.1.2.13',
            'get_iid' => '',
            'oidn' => 'IB-PLATFORMONE-MIB::ibNode1ServiceStatus.13',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_SOLID',
            'vlabel' => 'estado',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '0',
            'myrange' => 'IB-PLATFORMONE-MIB::ibNode1ServiceStatus.13',
            'enterprise' => '7779',
            'esp' => 'MAP(1)(1,0,0,0,0)|MAP(2)(0,1,0,0,0)|MAP(3)(0,0,1,0,0)|MAP(4)(0,0,0,1,0)|MAP(5)(0,0,0,0,1)',
            'params' => '',
            'itil_type' => '4',
            'apptype' => 'NET.INFOBLOX',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'ib_status_lan_ha',
            'class' => 'INFOBLOX',
            'lapse' => '300',
            'descr' => 'ESTADO SERVICIO ETH-HA',
            'items' => 'Ok(1)|Warn(2)|Failed(3)|Inactive(4)|Unk(5)',
            'oid' => '.1.3.6.1.4.1.7779.3.1.1.2.1.10.1.2.14',
            'get_iid' => '',
            'oidn' => 'IB-PLATFORMONE-MIB::ibNode1ServiceStatus.14',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_SOLID',
            'vlabel' => 'estado',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '0',
            'myrange' => 'IB-PLATFORMONE-MIB::ibNode1ServiceStatus.14',
            'enterprise' => '7779',
            'esp' => 'MAP(1)(1,0,0,0,0)|MAP(2)(0,1,0,0,0)|MAP(3)(0,0,1,0,0)|MAP(4)(0,0,0,1,0)|MAP(5)(0,0,0,0,1)',
            'params' => '',
            'itil_type' => '4',
            'apptype' => 'NET.INFOBLOX',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'ib_status_lan_mgmt',
            'class' => 'INFOBLOX',
            'lapse' => '300',
            'descr' => 'ESTADO SERVICIO ETH-MGMT',
            'items' => 'Ok(1)|Warn(2)|Failed(3)|Inactive(4)|Unk(5)',
            'oid' => '.1.3.6.1.4.1.7779.3.1.1.2.1.10.1.2.15',
            'get_iid' => '',
            'oidn' => 'IB-PLATFORMONE-MIB::ibNode1ServiceStatus.15',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_SOLID',
            'vlabel' => 'estado',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '0',
            'myrange' => 'IB-PLATFORMONE-MIB::ibNode1ServiceStatus.15',
            'enterprise' => '7779',
            'esp' => 'MAP(1)(1,0,0,0,0)|MAP(2)(0,1,0,0,0)|MAP(3)(0,0,1,0,0)|MAP(4)(0,0,0,1,0)|MAP(5)(0,0,0,0,1)',
            'params' => '',
            'itil_type' => '4',
            'apptype' => 'NET.INFOBLOX',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'ib_status_lcd',
            'class' => 'INFOBLOX',
            'lapse' => '300',
            'descr' => 'ESTADO SERVICIO LCD',
            'items' => 'Ok(1)|Warn(2)|Failed(3)|Inactive(4)|Unk(5)',
            'oid' => '.1.3.6.1.4.1.7779.3.1.1.2.1.10.1.2.16',
            'get_iid' => '',
            'oidn' => 'IB-PLATFORMONE-MIB::ibNode1ServiceStatus.16',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_SOLID',
            'vlabel' => 'estado',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '0',
            'myrange' => 'IB-PLATFORMONE-MIB::ibNode1ServiceStatus.16',
            'enterprise' => '7779',
            'esp' => 'MAP(1)(1,0,0,0,0)|MAP(2)(0,1,0,0,0)|MAP(3)(0,0,1,0,0)|MAP(4)(0,0,0,1,0)|MAP(5)(0,0,0,0,1)',
            'params' => '',
            'itil_type' => '4',
            'apptype' => 'NET.INFOBLOX',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'ib_status_mem',
            'class' => 'INFOBLOX',
            'lapse' => '300',
            'descr' => 'ESTADO SERVICIO MEMORY',
            'items' => 'Ok(1)|Warn(2)|Failed(3)|Inactive(4)|Unk(5)',
            'oid' => '.1.3.6.1.4.1.7779.3.1.1.2.1.10.1.2.17',
            'get_iid' => '',
            'oidn' => 'IB-PLATFORMONE-MIB::ibNode1ServiceStatus.17',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_SOLID',
            'vlabel' => 'estado',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'IB-PLATFORMONE-MIB::ibNode1ServiceStatus.17',
            'enterprise' => '7779',
            'esp' => 'MAP(1)(1,0,0,0,0)|MAP(2)(0,1,0,0,0)|MAP(3)(0,0,1,0,0)|MAP(4)(0,0,0,1,0)|MAP(5)(0,0,0,0,1)',
            'params' => '',
            'itil_type' => '4',
            'apptype' => 'NET.INFOBLOX',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'ib_status_repli',
            'class' => 'INFOBLOX',
            'lapse' => '300',
            'descr' => 'ESTADO SERVICIO REPLICATION',
            'items' => 'Ok(1)|Warn(2)|Failed(3)|Inactive(4)|Unk(5)',
            'oid' => '.1.3.6.1.4.1.7779.3.1.1.2.1.10.1.2.18',
            'get_iid' => '',
            'oidn' => 'IB-PLATFORMONE-MIB::ibNode1ServiceStatus.18',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_SOLID',
            'vlabel' => 'estado',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'IB-PLATFORMONE-MIB::ibNode1ServiceStatus.18',
            'enterprise' => '7779',
            'esp' => 'MAP(1)(1,0,0,0,0)|MAP(2)(0,1,0,0,0)|MAP(3)(0,0,1,0,0)|MAP(4)(0,0,0,1,0)|MAP(5)(0,0,0,0,1)',
            'params' => '',
            'itil_type' => '4',
            'apptype' => 'NET.INFOBLOX',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'ib_status_dbobj',
            'class' => 'INFOBLOX',
            'lapse' => '300',
            'descr' => 'ESTADO SERVICIO DB_OBJECT',
            'items' => 'Ok(1)|Warn(2)|Failed(3)|Inactive(4)|Unk(5)',
            'oid' => '.1.3.6.1.4.1.7779.3.1.1.2.1.10.1.2.19',
            'get_iid' => '',
            'oidn' => 'IB-PLATFORMONE-MIB::ibNode1ServiceStatus.19',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_SOLID',
            'vlabel' => 'estado',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'IB-PLATFORMONE-MIB::ibNode1ServiceStatus.19',
            'enterprise' => '7779',
            'esp' => 'MAP(1)(1,0,0,0,0)|MAP(2)(0,1,0,0,0)|MAP(3)(0,0,1,0,0)|MAP(4)(0,0,0,1,0)|MAP(5)(0,0,0,0,1)',
            'params' => '',
            'itil_type' => '4',
            'apptype' => 'NET.INFOBLOX',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'ib_status_raid_sum',
            'class' => 'INFOBLOX',
            'lapse' => '300',
            'descr' => 'ESTADO SERVICIO RAID-SUMMARY',
            'items' => 'Ok(1)|Warn(2)|Failed(3)|Inactive(4)|Unk(5)',
            'oid' => '.1.3.6.1.4.1.7779.3.1.1.2.1.10.1.2.20',
            'get_iid' => '',
            'oidn' => 'IB-PLATFORMONE-MIB::ibNode1ServiceStatus.20',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_SOLID',
            'vlabel' => 'estado',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'IB-PLATFORMONE-MIB::ibNode1ServiceStatus.20',
            'enterprise' => '7779',
            'esp' => 'MAP(1)(1,0,0,0,0)|MAP(2)(0,1,0,0,0)|MAP(3)(0,0,1,0,0)|MAP(4)(0,0,0,1,0)|MAP(5)(0,0,0,0,1)',
            'params' => '',
            'itil_type' => '4',
            'apptype' => 'NET.INFOBLOX',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'ib_status_raid_disk1',
            'class' => 'INFOBLOX',
            'lapse' => '300',
            'descr' => 'ESTADO SERVICIO RAID-DISK1',
            'items' => 'Ok(1)|Warn(2)|Failed(3)|Inactive(4)|Unk(5)',
            'oid' => '.1.3.6.1.4.1.7779.3.1.1.2.1.10.1.2.21',
            'get_iid' => '',
            'oidn' => 'IB-PLATFORMONE-MIB::ibNode1ServiceStatus.21',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_SOLID',
            'vlabel' => 'estado',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '0',
            'myrange' => 'IB-PLATFORMONE-MIB::ibNode1ServiceStatus.21',
            'enterprise' => '7779',
            'esp' => 'MAP(1)(1,0,0,0,0)|MAP(2)(0,1,0,0,0)|MAP(3)(0,0,1,0,0)|MAP(4)(0,0,0,1,0)|MAP(5)(0,0,0,0,1)',
            'params' => '',
            'itil_type' => '4',
            'apptype' => 'NET.INFOBLOX',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'ib_status_raid_disk2',
            'class' => 'INFOBLOX',
            'lapse' => '300',
            'descr' => 'ESTADO SERVICIO RAID-DISK2',
            'items' => 'Ok(1)|Warn(2)|Failed(3)|Inactive(4)|Unk(5)',
            'oid' => '.1.3.6.1.4.1.7779.3.1.1.2.1.10.1.2.22',
            'get_iid' => '',
            'oidn' => 'IB-PLATFORMONE-MIB::ibNode1ServiceStatus.22',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_SOLID',
            'vlabel' => 'estado',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '0',
            'myrange' => 'IB-PLATFORMONE-MIB::ibNode1ServiceStatus.22',
            'enterprise' => '7779',
            'esp' => 'MAP(1)(1,0,0,0,0)|MAP(2)(0,1,0,0,0)|MAP(3)(0,0,1,0,0)|MAP(4)(0,0,0,1,0)|MAP(5)(0,0,0,0,1)',
            'params' => '',
            'itil_type' => '4',
            'apptype' => 'NET.INFOBLOX',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'ib_status_raid_disk3',
            'class' => 'INFOBLOX',
            'lapse' => '300',
            'descr' => 'ESTADO SERVICIO RAID-DISK3',
            'items' => 'Ok(1)|Warn(2)|Failed(3)|Inactive(4)|Unk(5)',
            'oid' => '.1.3.6.1.4.1.7779.3.1.1.2.1.10.1.2.23',
            'get_iid' => '',
            'oidn' => 'IB-PLATFORMONE-MIB::ibNode1ServiceStatus.23',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_SOLID',
            'vlabel' => 'estado',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '0',
            'myrange' => 'IB-PLATFORMONE-MIB::ibNode1ServiceStatus.23',
            'enterprise' => '7779',
            'esp' => 'MAP(1)(1,0,0,0,0)|MAP(2)(0,1,0,0,0)|MAP(3)(0,0,1,0,0)|MAP(4)(0,0,0,1,0)|MAP(5)(0,0,0,0,1)',
            'params' => '',
            'itil_type' => '4',
            'apptype' => 'NET.INFOBLOX',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'ib_status_raid_disk4',
            'class' => 'INFOBLOX',
            'lapse' => '300',
            'descr' => 'ESTADO SERVICIO RAID-DISK4',
            'items' => 'Ok(1)|Warn(2)|Failed(3)|Inactive(4)|Unk(5)',
            'oid' => '.1.3.6.1.4.1.7779.3.1.1.2.1.10.1.2.24',
            'get_iid' => '',
            'oidn' => 'IB-PLATFORMONE-MIB::ibNode1ServiceStatus.24',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_SOLID',
            'vlabel' => 'estado',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '0',
            'myrange' => 'IB-PLATFORMONE-MIB::ibNode1ServiceStatus.24',
            'enterprise' => '7779',
            'esp' => 'MAP(1)(1,0,0,0,0)|MAP(2)(0,1,0,0,0)|MAP(3)(0,0,1,0,0)|MAP(4)(0,0,0,1,0)|MAP(5)(0,0,0,0,1)',
            'params' => '',
            'itil_type' => '4',
            'apptype' => 'NET.INFOBLOX',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'ib_status_fan1',
            'class' => 'INFOBLOX',
            'lapse' => '300',
            'descr' => 'ESTADO SERVICIO FAN1',
            'items' => 'Ok(1)|Warn(2)|Failed(3)|Inactive(4)|Unk(5)',
            'oid' => '.1.3.6.1.4.1.7779.3.1.1.2.1.10.1.2.25',
            'get_iid' => '',
            'oidn' => 'IB-PLATFORMONE-MIB::ibNode1ServiceStatus.25',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_SOLID',
            'vlabel' => 'estado',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'IB-PLATFORMONE-MIB::ibNode1ServiceStatus.25',
            'enterprise' => '7779',
            'esp' => 'MAP(1)(1,0,0,0,0)|MAP(2)(0,1,0,0,0)|MAP(3)(0,0,1,0,0)|MAP(4)(0,0,0,1,0)|MAP(5)(0,0,0,0,1)',
            'params' => '',
            'itil_type' => '4',
            'apptype' => 'NET.INFOBLOX',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'ib_status_fan2',
            'class' => 'INFOBLOX',
            'lapse' => '300',
            'descr' => 'ESTADO SERVICIO FAN2',
            'items' => 'Ok(1)|Warn(2)|Failed(3)|Inactive(4)|Unk(5)',
            'oid' => '.1.3.6.1.4.1.7779.3.1.1.2.1.10.1.2.26',
            'get_iid' => '',
            'oidn' => 'IB-PLATFORMONE-MIB::ibNode1ServiceStatus.26',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_SOLID',
            'vlabel' => 'estado',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'IB-PLATFORMONE-MIB::ibNode1ServiceStatus.26',
            'enterprise' => '7779',
            'esp' => 'MAP(1)(1,0,0,0,0)|MAP(2)(0,1,0,0,0)|MAP(3)(0,0,1,0,0)|MAP(4)(0,0,0,1,0)|MAP(5)(0,0,0,0,1)',
            'params' => '',
            'itil_type' => '4',
            'apptype' => 'NET.INFOBLOX',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'ib_status_fan3',
            'class' => 'INFOBLOX',
            'lapse' => '300',
            'descr' => 'ESTADO SERVICIO FAN3',
            'items' => 'Ok(1)|Warn(2)|Failed(3)|Inactive(4)|Unk(5)',
            'oid' => '.1.3.6.1.4.1.7779.3.1.1.2.1.10.1.2.27',
            'get_iid' => '',
            'oidn' => 'IB-PLATFORMONE-MIB::ibNode1ServiceStatus.27',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_SOLID',
            'vlabel' => 'estado',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'IB-PLATFORMONE-MIB::ibNode1ServiceStatus.27',
            'enterprise' => '7779',
            'esp' => 'MAP(1)(1,0,0,0,0)|MAP(2)(0,1,0,0,0)|MAP(3)(0,0,1,0,0)|MAP(4)(0,0,0,1,0)|MAP(5)(0,0,0,0,1)',
            'params' => '',
            'itil_type' => '4',
            'apptype' => 'NET.INFOBLOX',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'ib_status_power',
            'class' => 'INFOBLOX',
            'lapse' => '300',
            'descr' => 'ESTADO SERVICIO POWER-SUPPLY',
            'items' => 'Ok(1)|Warn(2)|Failed(3)|Inactive(4)|Unk(5)',
            'oid' => '.1.3.6.1.4.1.7779.3.1.1.2.1.10.1.2.28',
            'get_iid' => '',
            'oidn' => 'IB-PLATFORMONE-MIB::ibNode1ServiceStatus.28',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_SOLID',
            'vlabel' => 'estado',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'IB-PLATFORMONE-MIB::ibNode1ServiceStatus.28',
            'enterprise' => '7779',
            'esp' => 'MAP(1)(1,0,0,0,0)|MAP(2)(0,1,0,0,0)|MAP(3)(0,0,1,0,0)|MAP(4)(0,0,0,1,0)|MAP(5)(0,0,0,0,1)',
            'params' => '',
            'itil_type' => '4',
            'apptype' => 'NET.INFOBLOX',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'ib_status_ntp_sync',
            'class' => 'INFOBLOX',
            'lapse' => '300',
            'descr' => 'ESTADO SERVICIO NTP-SYNC',
            'items' => 'Ok(1)|Warn(2)|Failed(3)|Inactive(4)|Unk(5)',
            'oid' => '.1.3.6.1.4.1.7779.3.1.1.2.1.10.1.2.29',
            'get_iid' => '',
            'oidn' => 'IB-PLATFORMONE-MIB::ibNode1ServiceStatus.29',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_SOLID',
            'vlabel' => 'estado',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '0',
            'myrange' => 'IB-PLATFORMONE-MIB::ibNode1ServiceStatus.29',
            'enterprise' => '7779',
            'esp' => 'MAP(1)(1,0,0,0,0)|MAP(2)(0,1,0,0,0)|MAP(3)(0,0,1,0,0)|MAP(4)(0,0,0,1,0)|MAP(5)(0,0,0,0,1)',
            'params' => '',
            'itil_type' => '4',
            'apptype' => 'NET.INFOBLOX',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'ib_status_cpu1_temp',
            'class' => 'INFOBLOX',
            'lapse' => '300',
            'descr' => 'ESTADO SERVICIO CPU1-TEMP',
            'items' => 'Ok(1)|Warn(2)|Failed(3)|Inactive(4)|Unk(5)',
            'oid' => '.1.3.6.1.4.1.7779.3.1.1.2.1.10.1.2.30',
            'get_iid' => '',
            'oidn' => 'IB-PLATFORMONE-MIB::ibNode1ServiceStatus.30',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_SOLID',
            'vlabel' => 'estado',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'IB-PLATFORMONE-MIB::ibNode1ServiceStatus.30',
            'enterprise' => '7779',
            'esp' => 'MAP(1)(1,0,0,0,0)|MAP(2)(0,1,0,0,0)|MAP(3)(0,0,1,0,0)|MAP(4)(0,0,0,1,0)|MAP(5)(0,0,0,0,1)',
            'params' => '',
            'itil_type' => '4',
            'apptype' => 'NET.INFOBLOX',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'ib_status_cpu2_temp',
            'class' => 'INFOBLOX',
            'lapse' => '300',
            'descr' => 'ESTADO SERVICIO CPU2-TEMP',
            'items' => 'Ok(1)|Warn(2)|Failed(3)|Inactive(4)|Unk(5)',
            'oid' => '.1.3.6.1.4.1.7779.3.1.1.2.1.10.1.2.31',
            'get_iid' => '',
            'oidn' => 'IB-PLATFORMONE-MIB::ibNode1ServiceStatus.31',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_SOLID',
            'vlabel' => 'estado',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'IB-PLATFORMONE-MIB::ibNode1ServiceStatus.31',
            'enterprise' => '7779',
            'esp' => 'MAP(1)(1,0,0,0,0)|MAP(2)(0,1,0,0,0)|MAP(3)(0,0,1,0,0)|MAP(4)(0,0,0,1,0)|MAP(5)(0,0,0,0,1)',
            'params' => '',
            'itil_type' => '4',
            'apptype' => 'NET.INFOBLOX',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'ib_status_sys_temp',
            'class' => 'INFOBLOX',
            'lapse' => '300',
            'descr' => 'ESTADO SERVICIO SYS-TEMP',
            'items' => 'Ok(1)|Warn(2)|Failed(3)|Inactive(4)|Unk(5)',
            'oid' => '.1.3.6.1.4.1.7779.3.1.1.2.1.10.1.2.32',
            'get_iid' => '',
            'oidn' => 'IB-PLATFORMONE-MIB::ibNode1ServiceStatus.32',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_SOLID',
            'vlabel' => 'estado',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'IB-PLATFORMONE-MIB::ibNode1ServiceStatus.32',
            'enterprise' => '7779',
            'esp' => 'MAP(1)(1,0,0,0,0)|MAP(2)(0,1,0,0,0)|MAP(3)(0,0,1,0,0)|MAP(4)(0,0,0,1,0)|MAP(5)(0,0,0,0,1)',
            'params' => '',
            'itil_type' => '4',
            'apptype' => 'NET.INFOBLOX',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'ib_status_raid_bat',
            'class' => 'INFOBLOX',
            'lapse' => '300',
            'descr' => 'ESTADO SERVICIO RAID-BATTERY',
            'items' => 'Ok(1)|Warn(2)|Failed(3)|Inactive(4)|Unk(5)',
            'oid' => '.1.3.6.1.4.1.7779.3.1.1.2.1.10.1.2.33',
            'get_iid' => '',
            'oidn' => 'IB-PLATFORMONE-MIB::ibNode1ServiceStatus.33',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_SOLID',
            'vlabel' => 'estado',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'IB-PLATFORMONE-MIB::ibNode1ServiceStatus.33',
            'enterprise' => '7779',
            'esp' => 'MAP(1)(1,0,0,0,0)|MAP(2)(0,1,0,0,0)|MAP(3)(0,0,1,0,0)|MAP(4)(0,0,0,1,0)|MAP(5)(0,0,0,0,1)',
            'params' => '',
            'itil_type' => '4',
            'apptype' => 'NET.INFOBLOX',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'ib_status_cpu_usage',
            'class' => 'INFOBLOX',
            'lapse' => '300',
            'descr' => 'ESTADO SERVICIO CPU-USAGE',
            'items' => 'Ok(1)|Warn(2)|Failed(3)|Inactive(4)|Unk(5)',
            'oid' => '.1.3.6.1.4.1.7779.3.1.1.2.1.10.1.2.34',
            'get_iid' => '',
            'oidn' => 'IB-PLATFORMONE-MIB::ibNode1ServiceStatus.34',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_SOLID',
            'vlabel' => 'estado',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'IB-PLATFORMONE-MIB::ibNode1ServiceStatus.34',
            'enterprise' => '7779',
            'esp' => 'MAP(1)(1,0,0,0,0)|MAP(2)(0,1,0,0,0)|MAP(3)(0,0,1,0,0)|MAP(4)(0,0,0,1,0)|MAP(5)(0,0,0,0,1)',
            'params' => '',
            'itil_type' => '4',
            'apptype' => 'NET.INFOBLOX',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'ib_status_ospf',
            'class' => 'INFOBLOX',
            'lapse' => '300',
            'descr' => 'ESTADO SERVICIO OSPF',
            'items' => 'Ok(1)|Warn(2)|Failed(3)|Inactive(4)|Unk(5)',
            'oid' => '.1.3.6.1.4.1.7779.3.1.1.2.1.10.1.2.35',
            'get_iid' => '',
            'oidn' => 'IB-PLATFORMONE-MIB::ibNode1ServiceStatus.35',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_SOLID',
            'vlabel' => 'estado',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '0',
            'myrange' => 'IB-PLATFORMONE-MIB::ibNode1ServiceStatus.35',
            'enterprise' => '7779',
            'esp' => 'MAP(1)(1,0,0,0,0)|MAP(2)(0,1,0,0,0)|MAP(3)(0,0,1,0,0)|MAP(4)(0,0,0,1,0)|MAP(5)(0,0,0,0,1)',
            'params' => '',
            'itil_type' => '4',
            'apptype' => 'NET.INFOBLOX',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'ib_status_bgp',
            'class' => 'INFOBLOX',
            'lapse' => '300',
            'descr' => 'ESTADO SERVICIO BGP',
            'items' => 'Ok(1)|Warn(2)|Failed(3)|Inactive(4)|Unk(5)',
            'oid' => '.1.3.6.1.4.1.7779.3.1.1.2.1.10.1.2.36',
            'get_iid' => '',
            'oidn' => 'IB-PLATFORMONE-MIB::ibNode1ServiceStatus.36',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_SOLID',
            'vlabel' => 'estado',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '0',
            'myrange' => 'IB-PLATFORMONE-MIB::ibNode1ServiceStatus.36',
            'enterprise' => '7779',
            'esp' => 'MAP(1)(1,0,0,0,0)|MAP(2)(0,1,0,0,0)|MAP(3)(0,0,1,0,0)|MAP(4)(0,0,0,1,0)|MAP(5)(0,0,0,0,1)',
            'params' => '',
            'itil_type' => '4',
            'apptype' => 'NET.INFOBLOX',
      );


?>
