<?php

		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'socups_battery_status',
            'class' => 'SOCOMECUPS-MIB',
            'lapse' => '300',
            'descr' => 'ESTADO DE LA BATERIA',
            'items' => 'Estado (2:Normal)',
            'oid' => '.1.3.6.1.4.1.4555.1.1.1.1.2.1.0',
            'get_iid' => '',
            'oidn' => 'SOCOMECUPS-MIB::socoupsBatteryStatus.0',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'estado',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'SOCOMECUPS-MIB::socoupsBatteryStatus.0',
            'enterprise' => '4555',
            'esp' => '',
            'params' => '',
            'itil_type' => '4',
            'apptype' => 'HW.SOCOMEC',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'socups_battery_usage',
            'class' => 'SOCOMECUPS-MIB',
            'lapse' => '300',
            'descr' => 'TIEMPO DE USO DE LA BATERIA',
            'items' => 'socoupsSecondsOnBattery.0',
            'oid' => '.1.3.6.1.4.1.4555.1.1.1.1.2.2.0',
            'get_iid' => '',
            'oidn' => 'SOCOMECUPS-MIB::socoupsSecondsOnBattery.0',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'SOCOMECUPS-MIB::socoupsSecondsOnBattery.0',
            'enterprise' => '4555',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'HW.SOCOMEC',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'socups_time_remaining',
            'class' => 'SOCOMECUPS-MIB',
            'lapse' => '300',
            'descr' => 'TIEMPO ESTIMADO RESTANTE DE LA BATERIA',
            'items' => 'socoupsEstimatedMinutesRemaining.0',
            'oid' => '.1.3.6.1.4.1.4555.1.1.1.1.2.3.0',
            'get_iid' => '',
            'oidn' => 'SOCOMECUPS-MIB::socoupsEstimatedMinutesRemaining.0',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'SOCOMECUPS-MIB::socoupsEstimatedMinutesRemaining.0',
            'enterprise' => '4555',
            'esp' => '',
            'params' => '',
            'itil_type' => '4',
            'apptype' => 'HW.SOCOMEC',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'socups_charge_remaining',
            'class' => 'SOCOMECUPS-MIB',
            'lapse' => '300',
            'descr' => 'CARGA ESTIMADA RESTANTE DE LA BATERIA',
            'items' => 'socupsEstimatedChargeRemaining.0',
            'oid' => '.1.3.6.1.4.1.4555.1.1.1.1.2.4.0',
            'get_iid' => '',
            'oidn' => 'SOCOMECUPS-MIB::socupsEstimatedChargeRemaining.0',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'SOCOMECUPS-MIB::socupsEstimatedChargeRemaining.0',
            'enterprise' => '4555',
            'esp' => '',
            'params' => '',
            'itil_type' => '4',
            'apptype' => 'HW.SOCOMEC',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'socups_voltage',
            'class' => 'SOCOMECUPS-MIB',
            'lapse' => '300',
            'descr' => 'VOLTAJE DE LA BATERIA',
            'items' => 'Voltaje (0.1 Volt DC)',
            'oid' => '.1.3.6.1.4.1.4555.1.1.1.1.2.5.0',
            'get_iid' => '',
            'oidn' => 'SOCOMECUPS-MIB::socoupsBatteryVoltage.0',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => '0.1 Volt DC',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'SOCOMECUPS-MIB::socoupsBatteryVoltage.0',
            'enterprise' => '4555',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'HW.SOCOMEC',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'socups_num_lines',
            'class' => 'SOCOMECUPS-MIB',
            'lapse' => '300',
            'descr' => 'NUMERO DE LINEAS',
            'items' => 'Lineas de Entrada|Lineas de Salida|Lineas de Bypass',
            'oid' => '.1.3.6.1.4.1.4555.1.1.1.1.3.1.0|.1.3.6.1.4.1.4555.1.1.1.1.4.3.0|.1.3.6.1.4.1.4555.1.1.1.1.5.2.0',
            'get_iid' => '',
            'oidn' => 'SOCOMECUPS-MIB::socoupsInputNumLines.0|SOCOMECUPS-MIB::socoupsOutputNumLines.0|SOCOMECUPS-MIB::socoupsBypassNumLines.0',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '0',
            'myrange' => 'SOCOMECUPS-MIB::socoupsInputNumLines.0',
            'enterprise' => '4555',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'HW.SOCOMEC',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'socups_in_voltage',
            'class' => 'SOCOMECUPS-MIB',
            'lapse' => '300',
            'descr' => 'VOLTAJE DE ENTRADA EN LINEA',
            'items' => 'Voltaje (0.1 Volts)',
            'oid' => '.1.3.6.1.4.1.4555.1.1.1.1.3.3.1.2.IID|.1.3.6.1.4.1.4555.1.1.1.1.3.3.1.4.IID|.1.3.6.1.4.1.4555.1.1.1.1.3.3.1.5.IID',
            'get_iid' => 'socoupsInputLineIndex',
            'oidn' => 'socoupsInputVoltage.IID|socoupsInputVoltageMax.IID|socoupsInputVoltageMin.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => '0.1 Volts',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'SOCOMECUPS-MIB::socoupsInputTable',
            'enterprise' => '4555',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'HW.SOCOMEC',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'socups_in_current',
            'class' => 'SOCOMECUPS-MIB',
            'lapse' => '300',
            'descr' => 'CORRIENTE DE ENTRADA EN LINEA',
            'items' => 'Corriente (0.1 Amp)',
            'oid' => '.1.3.6.1.4.1.4555.1.1.1.1.3.3.1.3.IID',
            'get_iid' => 'socoupsInputLineIndex',
            'oidn' => 'socoupsInputCurrent.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => '0.1 Amp',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '0',
            'myrange' => 'SOCOMECUPS-MIB::socoupsInputTable',
            'enterprise' => '4555',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'HW.SOCOMEC',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'socups_out_voltage',
            'class' => 'SOCOMECUPS-MIB',
            'lapse' => '300',
            'descr' => 'VOLTAJE DE SALIDA EN LINEA',
            'items' => 'Voltaje (0.1 Volts)',
            'oid' => '.1.3.6.1.4.1.4555.1.1.1.1.4.4.1.2.IID',
            'get_iid' => 'socoupsOutputLineIndex',
            'oidn' => 'socoupsOutputVoltage.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => '0.1 Volts',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'SOCOMECUPS-MIB::socoupsOutputTable',
            'enterprise' => '4555',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'HW.SOCOMEC',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'socups_out_current',
            'class' => 'SOCOMECUPS-MIB',
            'lapse' => '300',
            'descr' => 'CORRIENTE DE SALIDA EN LINEA',
            'items' => 'Corriente (0.1 Amp)',
            'oid' => '.1.3.6.1.4.1.4555.1.1.1.1.4.4.1.3.IID',
            'get_iid' => 'socoupsOutputLineIndex',
            'oidn' => 'socoupsOutputCurrent.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => '0.1 Amp',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'SOCOMECUPS-MIB::socoupsOutputTable',
            'enterprise' => '4555',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'HW.SOCOMEC',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'socups_out_load_perc',
            'class' => 'SOCOMECUPS-MIB',
            'lapse' => '300',
            'descr' => 'CARGA DE SALIDA EN LINEA',
            'items' => 'Porcentaje de carga (%)',
            'oid' => '.1.3.6.1.4.1.4555.1.1.1.1.4.4.1.4.IID',
            'get_iid' => 'socoupsOutputLineIndex',
            'oidn' => 'socoupsOutputPercentLoad.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => '%',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'SOCOMECUPS-MIB::socoupsOutputTable',
            'enterprise' => '4555',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'HW.SOCOMEC',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'socups_byp_voltage',
            'class' => 'SOCOMECUPS-MIB',
            'lapse' => '300',
            'descr' => 'VOLTAJE DE BYPASS EN LINEA',
            'items' => 'Voltaje (0.1 Volts)',
            'oid' => '.1.3.6.1.4.1.4555.1.1.1.1.5.3.1.2.IID',
            'get_iid' => 'socoupsBypassLineIndex',
            'oidn' => 'socoupsBypassVoltage.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => '0.1 Volts',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '0',
            'myrange' => 'SOCOMECUPS-MIB::socoupsBypassTable',
            'enterprise' => '4555',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'HW.SOCOMEC',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'socups_byp_current',
            'class' => 'SOCOMECUPS-MIB',
            'lapse' => '300',
            'descr' => 'CORRIENTE DE BYPASS EN LINEA',
            'items' => 'Corriente (0.1 Amp)',
            'oid' => '.1.3.6.1.4.1.4555.1.1.1.1.5.3.1.3.IID',
            'get_iid' => 'socoupsBypassLineIndex',
            'oidn' => 'socoupsBypassCurrent.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => '0.1 Amp',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '0',
            'myrange' => 'SOCOMECUPS-MIB::socoupsBypassTable',
            'enterprise' => '4555',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'HW.SOCOMEC',
      );


?>
