<?php

		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'f5big_tcp_active',
            'class' => 'F5-BIGIP',
            'lapse' => '300',
            'descr' => 'CONEXIONES TCP ACTIVAS',
            'items' => 'sysTcpStatOpen.0',
            'oid' => '.1.3.6.1.4.1.3375.2.1.1.2.12.2.0',
            'get_iid' => '',
            'oidn' => 'F5-BIGIP-SYSTEM-MIB::sysTcpStatOpen.0',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'F5-BIGIP-SYSTEM-MIB::sysTcpStatOpen.0',
            'enterprise' => '3375',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.F5NETWORKS',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'f5big_tcp_inactive',
            'class' => 'F5-BIGIP',
            'lapse' => '300',
            'descr' => 'CONEXIONES TCP INACTIVAS',
            'items' => 'sysTcpStatCloseWait|sysTcpStatFinWait|sysTcpStatTimeWait',
            'oid' => '.1.3.6.1.4.1.3375.2.1.1.2.12.3|.1.3.6.1.4.1.3375.2.1.1.2.12.4|.1.3.6.1.4.1.3375.2.1.1.2.12.5',
            'get_iid' => '',
            'oidn' => 'F5-BIGIP-SYSTEM-MIB::sysTcpStatCloseWait|F5-BIGIP-SYSTEM-MIB::sysTcpStatFinWait|F5-BIGIP-SYSTEM-MIB::sysTcpStatTimeWait',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'F5-BIGIP-SYSTEM-MIB::sysTcpStatCloseWait',
            'enterprise' => '3375',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.F5NETWORKS',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'f5big_pools_tot_mem',
            'class' => 'F5-BIGIP',
            'lapse' => '300',
            'descr' => 'MIEMBROS TOTALES EN POOLS',
            'items' => 'ltmPoolMemberNumber.0',
            'oid' => '.1.3.6.1.4.1.3375.2.2.5.3.1.0',
            'get_iid' => '',
            'oidn' => 'F5-BIGIP-LOCAL-MIB::ltmPoolMemberNumber.0',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '1',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'F5-BIGIP-LOCAL-MIB::ltmPoolMemberNumber.0',
            'enterprise' => '3375',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.F5NETWORKS',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'f5big_cpu_temp',
            'class' => 'F5-BIGIP',
            'lapse' => '300',
            'descr' => 'CPU - TEMPERATURA',
            'items' => 'sysCpuTemperature',
            'oid' => '.1.3.6.1.4.1.3375.2.1.3.1.2.1.2.IID',
            'get_iid' => 'sysCpuIndex',
            'oidn' => 'sysCpuTemperature.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'F5-BIGIP-SYSTEM-MIB::sysCpuTable',
            'enterprise' => '3375',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.F5NETWORKS',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'f5big_cpu_fans',
            'class' => 'F5-BIGIP',
            'lapse' => '300',
            'descr' => 'CPU - VELOCIDAD VENTILADORES',
            'items' => 'sysCpuFanSpeed',
            'oid' => '.1.3.6.1.4.1.3375.2.1.3.1.2.1.3.IID',
            'get_iid' => 'sysCpuIndex',
            'oidn' => 'sysCpuFanSpeed.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'F5-BIGIP-SYSTEM-MIB::sysCpuTable',
            'enterprise' => '3375',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.F5NETWORKS',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'f5big_chas_fans',
            'class' => 'F5-BIGIP',
            'lapse' => '300',
            'descr' => 'CHASIS - VELOCIDAD VENTILADORES',
            'items' => 'sysChassisFanSpeed',
            'oid' => '.1.3.6.1.4.1.3375.2.1.3.2.1.2.1.3.IID',
            'get_iid' => 'sysChassisFanIndex',
            'oidn' => 'sysChassisFanSpeed.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'F5-BIGIP-SYSTEM-MIB::sysChassisFanTable',
            'enterprise' => '3375',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.F5NETWORKS',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'f5big_chas_fan_stat',
            'class' => 'F5-BIGIP',
            'lapse' => '300',
            'descr' => 'CHASIS - ESTADO DE LOS VENTILADORES',
            'items' => 'sysChassisFanStatus',
            'oid' => '.1.3.6.1.4.1.3375.2.1.3.2.1.2.1.2.IID',
            'get_iid' => 'sysChassisFanIndex',
            'oidn' => 'sysChassisFanStatus.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'F5-BIGIP-SYSTEM-MIB::sysChassisFanTable',
            'enterprise' => '3375',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.F5NETWORKS',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'f5big_chas_power_stat',
            'class' => 'F5-BIGIP',
            'lapse' => '300',
            'descr' => 'CHASIS - ESTADO DE LA FUENTE ALIMENTACION',
            'items' => 'sysChassisPowerSupplyStatus',
            'oid' => '.1.3.6.1.4.1.3375.2.1.3.2.2.2.1.2.IID',
            'get_iid' => 'sysChassisPowerSupplyIndex',
            'oidn' => 'sysChassisPowerSupplyStatus.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'F5-BIGIP-SYSTEM-MIB::sysChassisPowerSupplyTable',
            'enterprise' => '3375',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.F5NETWORKS',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'f5big_chas_temp',
            'class' => 'F5-BIGIP',
            'lapse' => '300',
            'descr' => 'CHASIS - TEMPERATURA DE SENSOR',
            'items' => 'sysChassisTempTemperature',
            'oid' => '.1.3.6.1.4.1.3375.2.1.3.2.3.2.1.2.IID',
            'get_iid' => 'sysChassisTempIndex',
            'oidn' => 'sysChassisTempTemperature.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'F5-BIGIP-SYSTEM-MIB::sysChassisTempTable',
            'enterprise' => '3375',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.F5NETWORKS',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'f5big_pool_active',
            'class' => 'F5-BIGIP',
            'lapse' => '300',
            'descr' => 'MIEMBROS ACTIVOS EN POOL',
            'items' => 'ltmPoolActiveMemberCnt|ltmPoolMemberCnt',
            'oid' => '.1.3.6.1.4.1.3375.2.2.5.1.2.1.8.IID|.1.3.6.1.4.1.3375.2.2.5.1.2.1.23.IID',
            'get_iid' => 'ltmPoolName',
            'oidn' => 'ltmPoolActiveMemberCnt.IID|ltmPoolMemberCnt.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'F5-BIGIP-LOCAL-MIB::ltmPoolTable',
            'enterprise' => '3375',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.F5NETWORKS',
      );



		$CFG_MONITOR_SNMP[]=array(
            'subtype' => 'f5big_pool_avail_stat',
            'class' => 'F5-BIGIP',
            'lapse' => '300',
            'descr' => 'ESTADO DEL POOL',
            'items' => 'ltmPoolStatusAvailState|ltmPoolStatusEnabledState',
            'oid' => '.1.3.6.1.4.1.3375.2.2.5.5.2.1.2.IID|.1.3.6.1.4.1.3375.2.2.5.5.2.1.3.IID',
            'get_iid' => 'ltmPoolStatusName',
            'oidn' => 'ltmPoolStatusAvailState.IID|ltmPoolStatusEnabledState.IID',
            'oid_info' => '',
            'module' => 'mod_snmp_get',
            'mtype' => 'STD_BASE',
            'vlabel' => 'num',
            'mode' => 'GAUGE',
            'top_value' => '1',
            'cfg' => '2',
            'custom' => '0',
            'include' => '1',
            'myrange' => 'F5-BIGIP-LOCAL-MIB::ltmPoolStatusTable',
            'enterprise' => '3375',
            'esp' => '',
            'params' => '',
            'itil_type' => '1',
            'apptype' => 'NET.F5NETWORKS',
      );


?>
