---
# This playbook contains common plays that will be run on all nodes.
- include_vars: /cfg/cnm_vars.yml

# Add specified repository into sources list.
- name: Se asigna repositorio
  apt_repository: repo="{{ cnm_apt_repo }}" state=present
  tags: layout
  

- name: Verify base directories [/store, /store/data, /cfg, /opt/cnm-mibs]
  file: path={{ item.path }} state=directory owner={{ item.owner }} group={{ item.group }} mode={{ item.mode }}
  with_items:
    - { path: '/store', owner: 'root', group: 'root', mode: '0777' }
    - { path: '/store/data', owner: 'root', group: 'root', mode: '0777' }
    - { path: '/store/data/app-data/remote_cfgs', owner: 'www-data', group: 'www-data', mode: '0775' }
    - { path: '/cfg', owner: 'root', group: 'www-data', mode: '0770' }
  tags: layout

- name: Verify base symlinks
  file: path={{ item.path }} src={{ item.src }} state=link owner=root group=root mode=0640
  with_items:
    - { path: '/opt/data', src: '/store/data' }
  tags: layout


- name: Legacy link [/opt/crawler -> /opt/cnm/crawler]
  file: path=/opt/crawler src=/opt/cnm/crawler state=link owner=root group=root mode=0755
  tags: layout

#- name: Legacy link [/var/www/html/onm -> /opt/cnm/onm]
#  file: path=/var/www/html/onm src=/opt/cnm/onm state=link owner=root group=root mode=0755
#  tags: layout

#- name: Legacy link [/var/www/cgi-bin -> /opt/cnm/cgi-bin]
#  file: path=/var/www/cgi-bin src=/opt/cnm/cgi-bin state=link owner=root group=root mode=0755
#  tags: layout

#- name: Legacy link [/var/www/html/tphp -> /opt/cnm/tphp]
#  file: path=/var/www/html/tphp src=/opt/cnm/tphp state=link owner=root group=root mode=0755
#  tags: layout

- name: Legacy link [/opt/data/mibs -> /opt/cnm-mibs]
  file: path=/opt/data/mibs src=/opt/cnm-mibs state=link owner=root group=root mode=0755
  tags: layout

#- name: Legacy link [/opt/data/xagent -> /opt/cnm/xagent]
#  file: path=/opt/data/xagent src=/opt/cnm/xagent state=link owner=root group=root mode=0755
#  tags: layout

- name: Legacy link [/update -> /opt/cnm/update]
  file: path=/update src=/opt/cnm/update state=link owner=root group=root mode=0755
  tags: layout

...
