---
# This playbook contains common plays that will be run on all nodes.
- include_vars: /cfg/cnm_vars.yml

# Add specified repository into sources list.
- name: Verify repository
  apt_repository: repo="{{ cnm_apt_repo }}" state=present
  tags: ldap
  
- name: Install packages
  apt: name={{item}} state=installed force=yes
  with_items:
   - slapd
   - ldap-utils
   - libldap-2.4-2
   - libldap2-dev
   - libnss-ldap
   - libpam-ldap
   - php5-ldap
  tags: ldap

- name: Check directory /etc/ldap
  file: path=/etc/ldap state=directory owner=root group=root mode=0755
  tags: ldap

- name: /etc/ldap/ldap.conf
  copy: src=ldap.conf dest=/etc/ldap/ldap.conf  owner=root group=root mode=0644
  tags: ldap

...
