---
# This playbook contains common plays that will be run on all nodes.
- include_vars: /cfg/cnm_vars.yml

- name: Update scheme IP
  command: php /opt/cnm/update/db/update/update_scheme_ip.php ip={{ ipaddress }}
  when: ipaddress is defined
  tags: cnm-change-ip

...
