# This playbook contains common plays that will be run on all nodes.
- include_vars: /cfg/cnm_vars.yml

- name: Check /usr/local/bin/snmpsimd.py
  stat: path=/usr/local/bin/snmpsimd.py
  register: snmpsim_file

- name: Remove /tmp/src/snmpsim
  file: path=/tmp/src/snmpsim state=absent
  when: snmpsim_file.stat.exists is defined and snmpsim_file.stat.exists==0
  tags: snmpsim

- name: Create /tmp/src/snmpsim
  file: path=/tmp/src/snmpsim state=directory owner=root group=root mode=0640
  when: snmpsim_file.stat.exists is defined and snmpsim_file.stat.exists==0
  tags: snmpsim

- name: Install packages
  apt: name=python-dev state=present force=yes update_cache=yes
  tags: snmpsim

- name: Extract from source
  command: tar -C /tmp/src/snmpsim -xzvf "/os/deb8/updates/0005_snmpsim/{{ item }}"
  with_items:
    - pyasn1-0.1.7.tar.gz
    - pycrypto-2.6.tar.gz
    - pysnmp-4.2.4.tar.gz
    - snmpsim-0.2.3rc0.tar.gz
  when: snmpsim_file.stat.exists is defined and snmpsim_file.stat.exists==0
  tags: snmpsim

- name: Install
  shell: "cd /tmp/src/snmpsim/{{ item }} &&  python setup.py install"
  with_items:
    - pyasn1-0.1.7
    - pycrypto-2.6
    - pysnmp-4.2.4
    - snmpsim-0.2.3rc0
  when: snmpsim_file.stat.exists is defined and snmpsim_file.stat.exists==0
  tags: snmpsim

#  shell: "{{ item }}"
#  with_items:
#    - cd /tmp/src/wmic/wmi-1.3.14
#    - make DESTDIR=/usr "CPP=gcc -E -ffreestanding"   
#  tags: wmic



#  command: "cd /tmp/src/wmic/wmi-1.3.14 , make DESTDIR=/usr 'CPP=gcc -E -ffreestanding'"
#  tags: wmic

#- name: Build net-snmp
#  shell: "{{ item }}"
#  args:
#    chdir: /tmp/src/net-snmp/net-snmp-5.7.3
#    register: out
#    debug: var=out.stdout_lines
#  with_items:
#    - ./configure --with-perl-modules --prefix=/opt/snmp --with-sys-contact="cnm-admin" --with-sys-location="CNM Room" --with-default-snmp-version="3" --with-logfile="/var/log/snmpd.log" --with-persistent-directory="/var/net-snmp"
#    - make
#    - make install

