<?php

$CFG_REPORT = array(
/*
	array(
      'id_cfg_report' => '1',
      'subtype_cfg_report'=>'00000001',
      'title' => 'Informe ejecutivo de alertas',
      'description' => 'Informe ejecutivo de las alertas producidas.',
      'custom' => '0',
      'itil_type' => '1',
      'apptype' => 'app.generic',
      'store' => '1',
	),

*/
   array(
      'id_cfg_report' => '2',
      'subtype_cfg_report'=>'00000002',
      'title' => 'Informe Global del Sistema CNM',
      'description' => 'Incluye los datos básicos sobre el sistema provisionado. Número de dispositivos, métricas...',
      'custom' => '0',
      'itil_type' => '1',
      'apptype' => 'app.generic',
      'store' => '0',
   ),
   array(
      'id_cfg_report' => '3',
      'subtype_cfg_report'=>'00000003',
      'title' => 'Detalle de alerta producida (normal)',
      'description' => 'Muestra la información relevante de la alerta producida.',
      'custom' => '0',
      'itil_type' => '1',
      'apptype' => 'app.generic',
      'store' => '0',
   ),
   array(
      'id_cfg_report' => '4',
      'subtype_cfg_report'=>'00000004',
      'title' => 'Informe detallado de alertas',
      'description' => 'Informe detallado de las alertas producidas.',
      'custom' => '0',
      'itil_type' => '1',
      'apptype' => 'app.generic',
      'store' => '1',
   ),
   array(
      'id_cfg_report' => '7',
      'subtype_cfg_report'=>'00000007',
      'title' => 'Detalle de alerta producida (remota)',
      'description' => 'Muestra la información relevante de la alerta producida.',
      'custom' => '0',
      'itil_type' => '1',
      'apptype' => 'app.generic',
      'store' => '0',
   ),
   array(
      'id_cfg_report' => '8',
      'subtype_cfg_report'=>'00000008',
      'title' => 'Detalle de alerta producida (sin respuesta snmp o agente)',
      'description' => 'Muestra la información relevante de la alerta producida.',
      'custom' => '0',
      'itil_type' => '1',
      'apptype' => 'app.generic',
      'store' => '0',
   ),
   array(
      'id_cfg_report' => '9',
      'subtype_cfg_report'=>'00000009',
      'title' => 'Detalle de alerta del histórico',
      'description' => 'Muestra la información relevante de la alerta del histórico.',
      'custom' => '0',
      'itil_type' => '1',
      'apptype' => 'app.generic',
      'store' => '0',
   ),
	// Informe de la parte mobile
   array(
      'id_cfg_report' => '10',
      'subtype_cfg_report'=>'00000010',
      'title' => 'Detalle de métrica',
      'description' => 'Muestra la información relevante de una métrica.',
      'custom' => '0',
      'itil_type' => '1',
      'apptype' => 'app.generic',
      'store' => '0',
   ),
   array(
      'id_cfg_report' => '11',
      'subtype_cfg_report'=>'00000011',
      'title' => 'Detalle de alerta producida (mobile)',
      'description' => 'Muestra la información relevante de la alerta producida.',
      'custom' => '0',
      'itil_type' => '1',
      'apptype' => 'app.generic',
      'store' => '0',
   ),
   array(
      'id_cfg_report' => '12',
      'subtype_cfg_report'=>'00000012',
      'title' => 'Detalle de alerta producida (remota y mobile)',
      'description' => 'Muestra la información relevante de la alerta producida.',
      'custom' => '0',
      'itil_type' => '1',
      'apptype' => 'app.generic',
      'store' => '0',
   ),
   array(
      'subtype_cfg_report'=>'00000100',
      'title' => 'Informe de tareas del Sistema CNM',
      'description' => 'Incluye los datos sobre las tareas que se están ejecutando.',
      'custom' => '0',
      'itil_type' => '1',
      'apptype' => 'app.generic',
      'store' => '0',
   ),

);
?>
